nvim-telescope/telescope.nvim

lua/telescope/builtin.lua
Prior to this commit, there looks to have been some missed renames and cleanup for variables for the `quickfix` builtin function. Was referencing the `LSP Reference` builtin variables and labels.
=> Renames the quickfix-related builtin variables from lsp references

lua/telescope/mappings.lua
`<cmd>` doesn't trigger `InsertLeave`.
=> Fix mapping prefix

lua/telescope/actions.lua, lua/telescope/pickers.lua
This PR adds mappings for open in split, vsplit and new tab.
The mappings were adopted by [fzf](https://github.com/junegunn/fzf.vim) and [vim-clap](https://github.com/liuchengxu/vim-clap).
<C-x> opens in new horizontal split.
<C-v> opens in new vertical split.
<C-t> opens in new tab.
=> Adds split and tabedit mappings. Adopted by fzf.vim

lua/telescope/mappings.lua
Modes now use lowercase keys, mappings use the internal representation via `nvim_replace_termcodes()`.
=> Normalize mappings

lua/telescope/config.lua
Meaning case insensitive unless query contains upper case.
=> Add smart case to vimgrep arguments

lua/telescope/builtin.lua
Add `--type f` to `fd`/`fdfind` in `builtin.find_files` to only return actual files (and not directories, which the previewer can't handle anyway)
=> Restrict builtin find_files to files

README.md, lua/telescope/actions.lua, lua/telescope/builtin.lua, lua/telescope/make_entry.lua
Fixes the remarks i made in #30.
Adds shorten_path opt.
Add show all buffers opt, this will also show unloaded buffers.
Fixes alignment with a dynamic solution. This means that the bufnr field adapts to the largest possible bufnr.
Previously I had a field size of 3 hardcoded but this makes it ugly when only single digit bufnr are displayed.
=> Adds shorten_path, show_all_buffers opts and fixes alignment (buffers builtin)

lua/telescope/builtin.lua
This makes it possible to use `find_files` like this
```lua
builtin.find_files {
find_command = { "rg", "-i", "--hidden", "--files", "-g", "!.git" }
}
```
BTW why is it showing old commits in this PR? Can I somehow only have the relevant commit(16817eb) shown in the PR?
=> Add find_command option for find_files

lua/telescope/pickers.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/themes.lua
Add a starting point with themes. 
Add center layout strategy.
Would like to finalize down the theme API but this is a good start I think.
I think you'd normally just set your theme in your opts table.
`require'telescope.builtin'.find_files{ theme = "dropdown" }`
Which doesn't exist currently.
--
This is how I am using it right now.
```
local opts = GetTheme("dropdown", { winblend = 3 })
require'telescope.builtin.find_files(opts)
```
Clip of it in action:
https://clips.twitch.tv/VictoriousYawningAnacondaWOOP
See #65
=> feat: Themes

README.md, lua/telescope/actions.lua, lua/telescope/pickers.lua, lua/telescope/previewers.lua
This PR tries to add a member function `scroll_fn` to Previewer. For previewer like `bat` you can use `chansend` to send termcodes of `<c-u>` or `<c-d>` to scrolling. For now this only works for `bat` but similar things should be able to port to vim buffer or other previewer.
Todo:
=> feat: add scrolling in preview window

lua/telescope/builtin.lua, lua/telescope/previewers.lua
fix issue #71 
Add double dash when calling underlying programs to prevent mixing of options and arguments.
This should fix all problems with filenames like '--my-file-with-strange-name'
=> use double dash to fix special filenames

lua/telescope/builtin.lua
Even if the matching is exact, the sorting is still helpful when multiple results are found.
=> Add sorter to live_grep

lua/telescope/actions.lua
Respect `sp`, `vsp` and `tabe` mappings.
Maybe just a hack. I have to think about this later again.
=> Respect sp, vsp, tabe mappings for buffers builtin

lua/telescope/make_entry.lua
Before this change, when using the `buffers()` builtin, the full path of the buffer filename was always shown because the `vim.api.nvim_buf_get_name()` API function is used (and that function always returns the full path).
I don't know lua at all so this may be a very naive solution, but it worked for me :laughing: .
=> buffers(): Trim cwd from bufname if possible

lua/telescope/previewers.lua
When the window is too narrow for a preview window - state is nil and causes the below error and doesn't allow the pop up window to close.
I added a simple nil check and this seems to work fine but please advise if something more involved is required
=> Nil check for no preview window

lua/telescope/actions.lua
Fixes problem mentioned in https://github.com/nvim-lua/telescope.nvim/pull/107#issuecomment-697346324
=> fix: refresh `bufnr` after executing edit command

lua/telescope/make_entry.lua
Follow up of https://github.com/nvim-lua/telescope.nvim/pull/104 that introduced a bug in which if `vim.fn.getcwd()` returns a string with a trailing path separator `/`, it causes the bufname path to be wrongly trimmed (e.g. `$(pwd)/foo/bar -> /foo/bar` instead of `$(pwd)/foo/bar -> foo/bar`).
This patch just checks the cwd trailing char and applies an offset.
@tjdevries I'm noticing that so far working with paths in lua has been quite hacky which in turn makes the appearence of these bugs easier. Is there a proper way to work with paths?
I have looked at [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) , and more concretely at  [path.lua](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/path.lua) which according to the projects README it's suppose to be the …
=> Fix issue with trimming path separator '/' for buffers()

lua/telescope/actions.lua
After the lastest changes in 3592b1f, this if branch is no longer reachable.
3592b1f still works but now we run `:edit #bufnr`, rather than `nvim_win_set_buf`.
This would be a valid choice but then we should remove the if clause. 
Regardless I would still vote for `nvim_win_set_buf` because the `edit` is not necessary here.
=> Fix if-clause after latest changes

lua/telescope/previewers.lua
This gets rid of a slightly annoying difference between files that fit
in the preview pane and ones that don't: hitting the scroll-preview
mappings would complain about a closed stream. Always using the pager
ensures there's always a process at the other end, even if asking it
to scroll doesn't actually do anything.
=> fix: Pass --paging=always to bat

lua/telescope/config.lua, lua/telescope/pickers.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/themes.lua
`get_dropdown{ border = false, results_height = 5})`
=> fix: Results height configurable. Properly collapse on border = false

lua/telescope/pickers/layout_strategies.lua, lua/telescope/themes.lua
width makes more sense in this case (also was previous behavior)
=> fix: Use width not results_width

lua/telescope/builtin.lua
Adds the stock `find` command to give those who don't have/want `rg` or `fd`.
(And fix a typo)
=> Add `find` command support

lua/telescope/actions.lua, lua/telescope/previewers.lua
This fixes an issue with no preview content because `vim.o.tags` did not include correct path.
Also adds highlighting  in the preview window to the help_topic/query
=> Fix help preview and add highlighting to search result

lua/telescope/builtin.lua
The current git command only shows the git files inside the working directory, not for the complete project. This seems to be the same functionality as the find_files command, this change will show all the files inside the project.
=> WIP: Changed git command to show all files inside project

lua/telescope/themes.lua
Preview should now work properly for the dropdown theme by default.
=> fix: preview_cutoff to always show on dropdown theme

lua/telescope/pickers/layout_strategies.lua
The problem Im trying to fix is the following: I set up a with of 120, but end up with a width of 43 (number of lines in my nvim window). By reading the code on `resolve.lua`, `resolve_width` is going to pick the minimum between `val` and the values passed to the function returned by `resolve_width`. In this case, it is going to select the min value between 120 (my desired width), 158 (number of cols) and 43 (number of lines), and therefore the width is set to 43.
Im not sure if the fix is correct though. The comments on `resolve.lua` seem to imply that its correct to pass `(col, lines)` so, if thats the case, then the fix should be changing the `_resolve_map` functions so that it picks the minimum between `val` and `lines` or `cols` (depending on what is resolving), but not the 3 of them
=> fix picking height as width

lua/telescope/previewers.lua
Adds the `-R` flag to `less` for the other code path as well, which is called for `grep` and `workspace_symbols`.
=> Make all other previews not bad, too.

lua/telescope/builtin.lua, lua/telescope/utils.lua
This sets the cwd option of the git_files builtin to use the root of the
git directory when the cwd option doesn't already exist. When git lists
files, it is relative to the root of the git directory, rather than the
current working directory. This caused problems when using git_files in
a subdirectory of the git root (see #174).
This commit fixes the issue by always setting the cwd as the root of the
git directory. I feel there is probably a better solution to extracting shell output
than writing the utils.capture function, however that is the solution I could find.
=> Ensure git_files uses the git root directory as cwd

lua/telescope/pickers.lua
For this snippet of code:
```vim
lua <<EOF
require'telescope'.setup{
defaults = require('telescope.themes').get_dropdown{}
}
EOF
nnoremap <leader><space> <cmd>lua require'telescope.builtin'.find_files{}<CR>
```
The results_height from `get_dropdown` was not applied to the `find_files` function.
This fix uses `results_height` and `results_width` from `config` as it has the same defaults.
=> Use results_height and results_width from config

lua/telescope/actions.lua, lua/telescope/builtin.lua
My attempt at providing something akin to :Clap providers, a.k.a. a telescope prompt that lets you summon any other available telescope prompts. This would resolve Issue #40
=> Shortcut from the popup to dynamically use other telescope functionality. #40

lua/telescope/previewers.lua
This PR checks the environment for a BAT_THEME variable and if present sets the `--theme` flag to the bat previewer command.
Related: #196
=> feat: Get BAT_THEME var from environment

lua/telescope/builtin.lua
Fix #193
The MacOs [manpage](https://www.unix.com/man-page/osx/1/find/) says that a path is expected. This is not expected on Linux because `find` assumes `.`, if no starting-point is specified ([Ref](https://man7.org/linux/man-pages/man1/find.1.html)).
I can't test it because i don't own a Mac, so it must be confirmed by the author of the original issue.
=> Fix find_command for find_files when using find executable

README.md, lua/telescope/actions.lua, lua/telescope/mappings.lua
Close #182
This PR enables adding up actions.
I have never overloaded operators in lua, so I'm not sure if this is what you had in mind.
I tested this with center.
So my test setup was i had a file open(middle of a big file so zz actually does something) with my cursor at the bottom of the screen. When i now run `live_grep` i was looking for a string which can be found at the top of the screen.
When I searched for a string outside the screen, it was already centered, even though actions.center was not set.
Missing:
=> Actions can now be summed up and center action

README.md, plugin/telescope.vim
like `find_command` it's a table type in lua ,so we should use a vimscript list type, now we can use `,` to connect each command string ,then split it by `,` and pass to lua code. eg:
```vim
:Telescope find_files find_command=rg,--ignore,--hidden,--files prompt_prefix=XXX
```
=> fix options bug when options is table type in lua

lua/telescope/previewers.lua
Fix #223 
Will not affect systems without `file`
=> Cat will no longer display binary files

lua/telescope/entry_manager.lua, lua/telescope/pickers.lua
Fixes the "wanky" behavior of 'row'. With that i mean, when i manually select entry 10 and than start typing and entry 10 is no longer available because only 8 elements are displayed, we will not have a selection and because of this
https://github.com/nvim-lua/telescope.nvim/blob/051aefdb8cea71294e6e62e8a4a1e051c48e4edd/lua/telescope/pickers.lua#L685-L688
we cant move the selection. So now it will stick to the last element when this happens.
I don't this we have to wrap `self:get_row(self.manager:num_results())` in `self:_handle_scroll_strategy`.
Fixes `follow` by changing `manager:find_entry`. I think we can even just compare elements, which would do a pointer comparison which is way faster than comparing with `ordinal`. I tested it and it works but let me know if you think it has some …
=> Fix selection_strategies row and follow

lua/telescope/builtin.lua, lua/telescope/previewers.lua, lua/telescope/utils.lua
Fix #226 
Edit: I will hijack this pr for #226 .
It also fixes the if condition. Its so easier than opening a new pr :laughing: 
It will also show directories. If i recall correctly find_files will only return files but when a directory buffer is opened buffers will show this buffer and preview the directory with `ls -la`
We could change find_files back to also show directories but i don't think its usefull. I don't know. Kinda need input on the whole directory suff @tjdevries
=> Fixes previews for files beginning with ~/ and Previewer will now show directories

lua/telescope/builtin.lua
It appears that the `git_files` picker is supposed to throw an error in a non-git directory, but is not doing so correctly (see commit message for why it happens). This PR fixes the issue. 
Also fixes a consequential issue that the error function was called with the wrong parameters (since the condition was never being met, it was probably missed)
=> Fix git files in non-git directories

lua/telescope/builtin.lua
I get an error message executing builtin.lsp_code_action when there's no code action available:
E5108: Error executing lua ...telescope.nvim/lua/telescope/builtin.lua:232: attempt to get length of local 'results' (a nil value)
The reason is that the results variable can be nil when there's no code action available,
check for nil results before checking the length
=> fix lsp_code_action error when no code action available

lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua, lua/telescope/pickers/entry_display.lua, lua/telescope/previewers.lua
Close #209 
~~Written in a coffee break, so WIP.~~
~~Currently has to be generated with `--fields=n` to get the line numbers. So `ctags -R --fields=+n`~~
default | hide_filename | show_line | hide_previewer
:-------------:|:-------------------------:|:-------------------:|:-----------------:
Available options:
```lua
only_current_file = true -- default is false, setting this to true will only show tags for the current file
hide_filename = true     -- default is false
show_line = true           -- default is false
```
=> Add tags builtin

lua/telescope/builtin/git.lua
The original implementation of set_opts_cwd calls git command twice if current dir is a git dir:
1. `git rev-parse HEAD` : to determine if current dir is a git dir
2. `git rev-parse --show-toplevel`: to find root of git dir
Can we remove the first call and just call `git rev-parse --show-toplevel` instead? It  returns an error message if not we are not in a git dir anyway.
=> refactor set_opts_cwd function so that git is called only once if cwd is a git dir

lua/telescope/builtin/git.lua
Let's say I'm working in a git dir, and I open a vim help buffer.
If I run `builtin.git_files()` now, it will report we are not in a git dir because `git_files` detects cwd by `expand('%:p:h')`, which is expanded to `/usr/share/nvim/runtime/doc`
`getcwd` is a better way to detect current working dir.
=> fix cwd detection of builtin.git_files

README.md, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua, lua/telescope/previewers.lua
@sharksforarms @clason 
Please try it out thanks :)
Adds a preview window in which we can put any content which is specified in a `preview_command` function.
Is useful for `dap` extensions, so we can basically display any lua table in a preview window.
=> Add highlights builtin

README.md, lua/telescope/config.lua, lua/telescope/previewers.lua
Fix #228
Fix #253
- Set env vars for previewer with set_env({ key = value } #228)
- Set pager for git previewes (default is GIT_PAGER=less so users can scroll see #253, but we can't just use the configured pager from `gitconfig` because pager's like `delta` which have a `split` view. That does not look good)
- Use less for people who don't have bat but less installed (see https://github.com/nvim-telescope/telescope.nvim/pull/216#discussion_r525067979)
- Reset less env to only '-RS' because '-X' will break scrolling(#253 thanks @eth3lbert)
- Scrolling for buffer previewer(thanks @tami5 for helping)
- Also new function to create buffer previewers (which has scrolling by default). Used for tags and help_tags previewer.
- Add new setting set_env to readme
@smartding @ThomasFeher
Add `set_env …
=> Various previewer fixes

README.md, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
Not super happy with the user experience so far.
Need nicer ways for editing, and more control over how you paste.
Putting the finder specific actions in `actions/init.lua` also feels strange, when everything else there is relatively generic.
Suggestions welcome
=> Register finder

README.md, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua, lua/telescope/pickers.lua, lua/telescope/previewers.lua
Close #179
Close #245
~~This is currently WIP. Basically it is hacked together.~~
This reworks `builtin.buffers`, so that we also display the indicators.
I'm currently parsing the output of `:buffers`. I'm not sure if i can get the indicators on another way.
~~This currently shows all buffer, also unloaded buffers. (So `show_all_buffers = true` does nothing)~~(Should now work as before)
This also adds a function, which could help us display outputs in a more table like format, like suggested in #118.
This does not change the other builtins to be to a table format. (I plan to do this in another pr).
~~I also briefly looked into  #179 and i think we can use `unpack(vim.fn.getbufinfo(tonumber(bufnr))).lastused` to sort the buffers list. (I think this should be configurable. either pick the …
=> Buffers rework (indicators and sorting)

plugin/telescope.vim
I like it better when the first letter filters out the candidates, don't you?
*before*:
*after*:
=> Filter the completion of the command

lua/telescope/mappings.lua
Previously, if e.g. `:` was remapped, Telescope would be unclosable with its mappings (`<Esc>`).
=> Use noremap when mapping.

lua/telescope/actions/init.lua, lua/telescope/builtin/git.lua
This pull request creates three actions: "git_restore_staged_worktree", "git_restore_staged" and "git_restore_worktree".
I based my work on git add and go_to_file_selection
@Conni2461 Let me know how i can improve this PR. I also think that the git add/restore actions shouldn't close the prompt_buffer? This would allow multiple edits of the index.
=> Add git staging toggle to git_status builtin

lua/telescope/actions/init.lua
Similar to https://github.com/nvim-telescope/telescope.nvim/pull/116 and https://github.com/nvim-telescope/telescope.nvim/issues/115
It seems that this was removed in some refactoring. Without this, any autocmds for filetypes will not run.
=> add back filetypedetect on edit

lua/telescope/make_entry.lua, lua/telescope/pickers/entry_display.lua
@sunjon Does this help?
@tjdevries Do we wanna talk about the interface. I think this is the best way to do this, so people can change the `hl_group` based on the specific value. Like sunjon wants to do: `if x == 'opts' then hl_group1 else hl_group2 end`. 
The other idea i had was to specify the `hl_group` when we create the `displayer`. But that would limit our flexibility.
Separator Example: When creating the displayer
```lua
local hl = 'Visual'
local displayer = entry_display.create {
separator = " ",
separator_hl = hl, -- New
items = {
{ width = opts.bufnr_width },
{ width = 4 },
{ remaining = true },
},
}
```
Elements Example: When submitting data
```lua
local hl_group = x == y then 'Normal' or 'Visual'
return displayer {
entry.bufnr,
{ entry.indicator, hl_group },
display_bufname .. …
```
=> Displayer now supports highlights

lua/telescope/builtin/init.lua, lua/telescope/utils.lua
Fixes #105.
This does the "blunt" seeming just set-and-unset report whilst deleting buffers, which seems to fix the issue for me (in that no message for buffer deletion is shown).
Lemme know if this makes sense to y'all or if there's some obvious issue with it.
=> Set and unset report to what's needed when deleting buffers.

README.md, lua/telescope/builtin/files.lua, lua/telescope/builtin/git.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/config.lua, lua/telescope/path.lua, lua/telescope/previewers.lua
Fix #163
Close #206 
Close #257
Note: This branch will receive force pushes.
~~More builtins soon.~~ 
Also its currently slower than bat. Especially when scrolling though the results list. I hope i can fix this. Some thoughts on speed:
- Vim buffers as previewer will be way fast for things like `grep`, because we usually have the same file multiple times. With `bat` we have to reload this file every single time, with vim buffers, we have to load it once and can use it as often as we want.
- For `files` and `git_files` we have unique files. Every entry is a new file that we have to load. In this case i am currently losing.
Enable with:
```lua
defaults = {
file_previewer = previewers.vim_buffer_cat.new,
grep_previewer = previewers.vim_buffer_vimgrep.new, …
```
=> Vim Buffers everywhere we look

README.md, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
~~Modified this [file](https://www.unicode.org/Public/emoji/13.1/emoji-test.txt). Is there a better file?~~
More sources (open for suggestions):
Fix Me:
Usage:
`:lua require'telescope.builtin'.symbols{} -- all sources`
`:lua require'telescope.builtin'.symbols{ sources = { 'math' } } -- only math`
`:lua require'telescope.builtin'.symbols{ sources = { 'emoji' } } -- only emoji`
`:lua require'telescope.builtin'.symbols{ sources = { 'kaomoji' } } -- only kaomoji`
`:lua require'telescope.builtin'.symbols{ sources = { 'math', 'emoji' } } -- both math and emoji`
Download:
`:lua require'telescope.script'.get_all_sources()`
`:lua require'telescope.script'.get_x_source() -- with x ∈ { 'emoji', 'math', 'kaomoji' }`
Source file format(3 spaces are used because of the fact that kaomoji can include …
=> Symbol Picker

README.md
👋 
I found this while trying to override the default finder so I can search hidden files in my project.
Would you mind providing an example for `.vimrc`?
I'm quite ignorant of how nvim works to load the file. I tried `lua :Telescope find_files find_command=rg,--ignore,--hidden,--files` but that didn't quite work.
=> [documentation] fix typo

lua/telescope/previewers.lua
Fix #318
When a bat theme contained spaces it would crash the bat previewer as described in #318.
=> fix: fix non escaped bat theme

lua/telescope/pickers.lua
Fixes the cycle scroll when num_results is smaller than max_results.
=> fix: cycle scroll when num_results is small

lua/telescope/pickers.lua, lua/telescope/pickers/scroller.lua, lua/tests/automated/scroller_spec.lua
Fix: #328
Should be math.max for sorting_strategy = "descending" and other stuff if list is smaller(not sure about that).
Edit: Before that we would lose the selection, now it doesn't cycle for `descending`. ~~Needs more work. Not the correct solution.~~ Should work now
~~Edit: Will add test asap~~
=> Fix scroller for descending

lua/telescope/builtin/internal.lua
Stops errors should you start the buffer finder on a startup screen that runs in a hidden buffer and there are no buffers to list.
=> fix: don't error when no hidden buffers are available

lua/telescope/builtin/files.lua, lua/telescope/make_entry.lua
Adds functionality for finders to get files from multiple directories. Currently tuned only for the three supported finders, but shouldn't be too hard to add more, as long as the command itself supports searching from multiple directories. This PR adds a search_dirs option, which is injected into the command args to search from multiple directories
Fixes #238
=> Allow finder to find from multiple dirs

lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua, lua/telescope/path.lua, lua/telescope/pickers/entry_display.lua, lua/telescope/previewers.lua, plugin/telescope.vim
@sunjon 
I updated the highlights previewer as you suggested.
I also updated the autocommand previewer so we don't have to set all lines for every new entry, we just have to set them once per autocmd group and then use that buffer and jump back and forth. Result more speeeeeeeed 🤣 
Edit: Also you didn't jump before, so if the group was huge we ended up not even showing the correct result. Example `filetypedetect`
Edit 2: Also fixed a crash when `find_files` or similar wants to read a directory. Happens with `git_files` and submodules.
Edit 3: Also make help_tags super fast :)
=> Update autocommands/highlights and help_tags previewers

lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/make_entry.lua
add more colors to finders that would benefit from it now that highlighting is fixed/improved.
Previously I've assigned hl_groups as I'd seen appropriate -  Comment for less important text, Number for numbers..
This isn't ideal, and I'm wondering if/how the current Telescope* groups can be expanded to allow a reasonable amount of customisation without finder specifc configs.
I've altered the LSP_*_symbol finder to be a bit more readable and tried to relate the display colour to the hl_group used in Vim. As this will change per langauge, I'm not sure what the best way to do this will be. If we decide on a way forward, the Treesitter and perhaps ctags finders can use this display method.
All input welcome
=> Add more colour

README.md
Both `find_files()` and `help_tags()` were bound to `<leader>ff`. This resulted in `<leader>ff` not opening the `find_files()` dialog
=> README.md | fix lua example configuration

lua/telescope/builtin/files.lua, lua/telescope/builtin/git.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/make_entry.lua
This will allow for more customization and make telescope more fun to use!
```lua
require('telescope.builtin').buffers {
...
entry_maker = my_entry_maker.gen_from_buffer_better(),
...
}
```
Should it be possible to override it with other pickers?
=> fix: builtin.buffers to override entry_maker

README.md, lua/telescope/config.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/previewers/utils.lua, plugin/telescope.vim
Missing:
Also requires https://github.com/nvim-lua/plenary.nvim/pull/37 to work perfectly
=> More faster previewers

lua/telescope/previewers/utils.lua
Add detection of a proper buffer language by `ts_parsers.ft_to_lang` as `ts_parsers.has_parser` works with `language` but not with `filetype`.
https://github.com/nvim-treesitter/nvim-treesitter/issues/796
=> Add ts_parsers.ft_to_lang to detect buffer's lang

lua/telescope/builtin/files.lua
fixed #347. Also fixed an issue with `(` or `)`.
=> fix: live_grep throws an error if you insert `\`

lua/telescope/builtin/files.lua
@Conni2461 nope, you were right :laughing:. We should escape it instead. This escapes `\`, `()`, and `[]`, I don't know what other characters that can cause an error. It also fixes `grep_string`. Follow up of #378
=> fix: escape chars instead of resetting the prompt

lua/telescope/actions/init.lua
Add commands to cmd-history. Fixes https://github.com/nvim-telescope/telescope.nvim/issues/367
=> add selected command to cmd-history

plugin/telescope.vim
Call the extension from command line when user register extension to telescope
```vim
-- before
lua require"telescope".extensions.dotfiles.dotfiles{path=os.getenv("HOME").."/.dotfiles"}
lua require"telescope".extensions.project.project{}
-- now
Telescope dotfiles path=xxxx
Telescope project
```
=> add extension in telescope command

lua/telescope/actions/init.lua, lua/telescope/pickers.lua
This can be useful for example if the user has typed in something that does not match any entry. Then we want to perform something else. A use case is for [neuron.nvim](https://github.com/oberblastmeister/neuron.nvim) where the user can query for notes. If the user has typed in something that does not match any entry, we want to create a new note, kind of like Notational Velocity. I would need to be able to get the current line for that to work.
=> allow actions.get_current_line in addition to actions.get_selected_entry

lua/telescope/builtin/internal.lua
previous commit left a trailing quote and did not exit insert mode
=> fix: remove quotes from spell suggestions

lua/telescope/command.lua
if the user options does not exist in default options but need in extensions. just covert the user options that in default options.
=> fix bug with custom extensions opts

lua/telescope/previewers/term_previewer.lua
I found `live_grep` picker shows corrupted previews when `cwd` option is used.
```vim
lua require'telescope.builtin'.live_grep{cwd = '/foofoo/barbar'}
```
When this command is executed in `/foo/bar`, and it founds `some-file/found.txt`, preview window will be corrupted because `/foo/bar/some-file/found.txt` does not exist.
=> Use valid paths to preview considering cwd

lua/telescope/previewers/buffer_previewer.lua
Edit: Should work. Just not in general. We need to determine for each file which line endings are used. I think you can also use linux line endings on windows and these change would break it
Edit 2: Should be better now
=> Previewer windows fix

lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua
Should be better now i terms of maintainability.
New: 
- We stop highlighting a file that is now longer seen. That means when we are loading the file async and the loading is dones, it might happen that the file is no longer selected. So there is no point in attaching a highlighter and doing the highlighting because we have to do it the next time this file is selected again. Matters only really when an entry is selected the first time.
CC @yujinyuz
~~Edit: F CI~~
=> Update file_maker signature and fix scrolling

lua/telescope/builtin/git.lua
Before this, branch names such as `feature/foo` became `foo`. Fix it.
=> Do not remove a part of branch names

lua/telescope/builtin/internal.lua
Hello,
this adds a new option `ignore_current_buffer` to the builtin `buffers`.
When `ignore_current_buffer` is set to `true`, the current buffer won't get listed.
The option also disables setting the `default_selection_idx`, since it is not needed in that case.
This change greatly improves buffer switching for me.
I'm also welcome for suggestions on how to handle this differently.
Also please correct me if I made a mistake while converting the boolean statement, or if you feel it's uneccecary.
=> add ignore_current_buffer options to builtin buffers

lua/telescope/from_entry.lua
I have a weird case where I need to open a file with `$` in its filename so we need to escape it.
=> fix: escape filename before opening it

lua/telescope/from_entry.lua
if `entry.path` is nil `vim.fn.fnameescape` will return null which results
in all other option no longer being checked
=> hotfix: fnameescape in from_entry

lua/telescope/previewers/buffer_previewer.lua
This PR simply checks if `cend` evaluates to false, if it doesn't, it will add the highlight to the line.
Unfortunately, I don't have steps to reproduce or any more information like screenshots as I was only able to reproduce this on my current work repo.
=> Fix: error when repo has a lot of branches, forks and merges

README.md
I found a missing comma in README, Mapping section. ref: #485
=> Correct a missing comma in README, Mapping section

README.md, lua/telescope/config.lua, lua/telescope/previewers/term_previewer.lua
Fix #484
Remove workaround for https://github.com/neovim/neovim/issues/11751 because https://github.com/neovim/neovim/pull/12937 was merged.
I tested it and it still works. I will merge that in 2 or 3 days
=> Remove env workaround for term_previewer

lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua
In maacOS apropos needs args and outputs differently.
=> Set valid commands for apropos in macOS

lua/telescope/actions/init.lua
Given that Telescope has a picker for quickfix items, opening its window automatically isn't that useful, so this commit removes the call from send_to_qflist and send_selected_to_qflist. Some users may prefer the old behaviour though so a new action open_qflist was created.
=> Open quickfix list on it's own action

lua/telescope/make_entry.lua
I want to show all sections in `:Telescope man_pages` some time, but it cannot be achieved with the current `sections` option. I introduced a syntax for this.
```vim
" Show all sections in man pages
:Telescope man_pages sections=ALL
```
```lua
-- for the same purpose
require'telescope'.builtin.man_pages{sections={'ALL'}}
```
I'm worrying that some man pages have odd sections in macOS at least, such as `3tiff`, `n` and `ntcl`.
```
apropos ' ' 2> /dev/null | perl -nle '/\([^)]+\)/; $sections{$&}++; END { print for sort keys %sections }'
(1)
(1m)
(1tcl)
(3)
(3tiff)
(4)
(5)
(6)
(7)
(8)
(9)
(n)
(ntcl)
```
So possibly any page have `ALL` section, and we cannot see it with `:Telescope sections=ALL`. (We can see it with `:Telescope sections=ALL,` (the last comma), then)
I think it rarely occurs …
=> Enable to show all sections in man_pages

lua/telescope/utils.lua
Neovim in Windows cannot detect C funcs that are called here.
=> Do not use C binding in Windows

lua/telescope/previewers/buffer_previewer.lua, plugin/telescope.vim
Need help with color groups otherwise should be done.
Also probably we should create Telescope hl_groups for that. I am open for default links :)
Also i need to think about the code 😆 Just wrote that in 30 mins so might not be optimal in terms of everything
| Before | After |
|--------|-------|
| ![2021-02-06_13-18](https://user-images.githubusercontent.com/15233006/107117943-08ef4a80-687e-11eb-9807-4d84fd68b2a9.png) | ![t0NvTME](https://user-images.githubusercontent.com/15233006/107117948-10165880-687e-11eb-839b-3f3690f7f74f.png) |
Edit: new idea plenary already has the sections so why not use that 🤣
=> Buffer previewer ls colorized

README.md, lua/telescope/config.lua, lua/telescope/previewers/init.lua
This can be done as soon as:
Ref: #415
=> Make buffer previewer default and deprecate bat previewer

README.md
We now use buffer previewer as the default, might as well update the readme demo. Also, I'll add the rest of the builtins demo for the wiki later
=> docs: update outdated gif + more demo

lua/telescope/previewers/buffer_previewer.lua
This pull request changes the `-P` option given to `git` to `--no-pager` in git commit/file/branch previewers because the latter is more backwards compatible.
The `-P` option was added to `git` around three years ago as a shorthand for `--no-pager` (relavant commit: https://github.com/git/git/commit/7213c288187bd9ef1e32e4f86c20c55436f1ae90). My lab server (remarkably) uses `git 2.17.1` and the preview window for git commits displayed nothing. This patch fixed the problem.
Thank you for the great plugin!
=> Change git -P to --no-pager

lua/telescope/pickers/entry_display.lua, lua/telescope/utils.lua
Use `utils.strdisplaywidth` to count the displayed width instead of using Lua `string.format`. 
Before
After
=> fix: proper multibytes chars alignment

lua/telescope/builtin/git.lua
Hi, thanks for the amazing work!
I work in a pretty large git repo and spend my time in a nested folder. What I wanted was an option for `git_files` to only show the git files from my cwd - not the whole project.
I _think_ the only other `git_*` command this might be relevant to is `git_commits` (maybe `git_status`?). I'm not too bothered about those but happy to add it to them.
=> Allowed git_files to use vim pwd over git root

.github/workflows/docgen.yml, CONTRIBUTING.md, README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/git.lua, lua/telescope/builtin/lsp.lua, lua/telescope/config.lua, lua/telescope/init.lua, lua/telescope/pickers.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/utils.lua
Close #552
Close #565
Close #568
- Change from systemlist to plenary.job
- print result message with clangd when using workspace-symbols. Clangd returns `{ { result = {} } }`
- fix some odd formatting in contributing.md (because it got copied out of a github thread and also some informal things don't belong in that file)
- Docgen is now running
```lua
defaults = {
selection_caret = ' > ', -- default '>'
}
}
```
or:
```lua
require'telescope.builtin'.find_files({ selection_caret = ' >' })
```
CC @yamatsum
=> make selection caret configurable and more small things

lua/telescope/mappings.lua
Use Shift+Tab to match fzf's keymappings.
Seems like a reasonable functionality, which will also make it easier for people coming from fzf.vim.
=> Add ability to select in reverse direction

lua/telescope/pickers.lua
Fix this issue. I just got the length of the wrong string. Bad rebase by me.
CC @weilbith
=> fix: entry_prefix if caret > prefix

README.md, doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers/layout_strategies.lua
This is a feature that I have been wanting for a while now in Telescope, but never really got around to opening an issue for it for whatever reason. Finally decided I might as well see if I can figure out how to do it myself by poking around the codebase 🙂. I would love if the horizontal layout allowed for a config option to let you mirror the default horizontal layout. Here's a visual:
Current horizontal layout (new config option would be set to `false`):
```
+-----------------+---------------------+
|                 |                     |
|     Results     |                     |
|                 |       Preview       |
|                 |                     |
+-----------------|                     |
|     Prompt      |                     | …
```
=> Modified horizontal layout to allow mirroring of the default layout, added new config value to toggle behavior on/off

lua/telescope/builtin/git.lua
close #579 
do we want to provide a flag just for this option or do we want to make the entire `cmd` overridable? and I'm not sure if this should be the default or not, I like this better but idk about what other people opinion about it.
also, is there any reason why we use `table.getn(tbl)` instead of just `#tbl`? [This thread](https://stackoverflow.com/questions/31452871/table-getn-is-deprecated-how-can-i-get-the-length-of-an-array) said it's deprecated so I tested them both and they have the same result.
cc @Conni2461 @kristijanhusak
=> feat: add expand_dir opts for git_status

lua/telescope/command.lua, plugin/telescope.vim
Fixed subcommand completion for each extension.
@glepnir If there is a reason why the subcommands for all extensions are being completed, I would appreciate it if you could let me know.
https://user-images.githubusercontent.com/16581287/109809572-c85fd280-7c6b-11eb-8398-062ba1827eca.mp4
https://user-images.githubusercontent.com/16581287/109809677-f0e7cc80-7c6b-11eb-80bb-db6359856bb6.mp4
=> fix: subcommand completion for each extension

plugin/telescope.vim
Motivation:
Sometimes it's nice to use "g:loaded_<smth>"-flags to check if plugin is installed/used.
Implementation examples:
- https://github.com/tpope/vim-fugitive/blob/9cba97f4db4e0af4275f802c2de977f553d26ec6/plugin/fugitive.vim#L6-L9
- https://github.com/mhinz/vim-startify/blob/f2fc11844b234479d37bef37faa7ceb2aade788b/plugin/startify.vim#L7
- https://github.com/neovim/nvim-lspconfig/blob/470b0cf45a7e60243e97628c21b05804088dfbf5/plugin/lspconfig.vim#L1
=> Add loading guard

lua/telescope/builtin/files.lua
Hoping to be able to see hidden files in `file_browser`, disabled by default
=> Add ability to show hidden files in file_browser

lua/telescope/make_entry.lua
This should fix #603  as per discussion in the issue, specifically
- The signs if empty default to {E, W, I, H}
- `opts.no_sign` can be used to turn off the sign entirely
- Additionally: line header width is automatically set and now also respects 1'000s of lines adequately
=> fix: error from unset LspDiagnosticSign & introduce opts.no_sign

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/set.lua, lua/telescope/pickers/layout_strategies.lua
continuing @Conni2461's work #606
you can now do something like this to customise the scrolling speed, the default is `preview_height / 2`
```lua
layout_defaults = {
horizontal = {
scroll_speed = 5
},
vertical = {
scroll_speed = 2
},
}
```
=> feat: define scroll speed + smart_send to qflist

lua/telescope/actions/init.lua, lua/telescope/mappings.lua, lua/telescope/sorters.lua, lua/telescope/utils.lua
This PR adds simple insert mode completion to `tag` prefiltering to both (a) cycle through (in e.g. empty prompt or prompt merely comprises a tag) or (b) incrementally complete `tags` by
1. Collecting `tags` in a set table during scoring
2. Trigger `action` to set insert completion for prompt with `complete` **
https://user-images.githubusercontent.com/39233597/110256294-57385c00-7f98-11eb-86e9-9f647bb2a659.mp4
Accepting a match currently is done via (a)`<C-y>` (standard vim binding), (b) continue typing with open menu or (c) `ESC` as `<CR>` is of course bound to jumping to line of entry. 
Known issue:
- Backspace freezes after going into normal mode (e: i.e. accepting completion with `ESC`): one can still cycle through but only delete prompt from normal mode (i.e. `cc`) which I guess is …
=> feat: add completion to pre-filtering

lua/telescope/builtin/internal.lua
This adds options to the `oldfiles` finder to make it optionally more useful as a MRU (most recently used) finder.
- `include_current_session`
- Normally `v:oldfiles` only lists files from past vim sessions. This option will include recently accessed files in the current vim session using `:buffers! t` (the `!` bang shows unlisted buffers after they are closed, and the `t` modifier sorts the list by MRU).
- `cwd_only`
- This option filters the results to only show files within the cwd. This makes for a nice project-specific-MRU finder.
At the moment both options don't change default `oldfiles` finder behaviour, as they are both opt-in. I might argue making `include_current_session=true` a default, having to restart vim to see new entries populated into `v:oldfiles` is kind of weird. …
=> Improve oldfiles finder

lua/telescope/builtin/files.lua, lua/telescope/builtin/git.lua, lua/telescope/pickers/highlights.lua
Show short informations for all branches.
for: #569
=> Show committer, upstream and date in branch finder

doc/telescope.txt, lua/telescope/builtin/internal.lua, lua/telescope/config.lua, lua/telescope/pickers.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua, lua/telescope/previewers/utils.lua
And some other small things i noticed in the past week:
- fix docgen formatting
- fix in_fast_even when overriding file_maker
- fix filtering for space in keymaps with fzy (close #658)
- remove count of files ignored by `file_ignore_patterns` (fix #247)
- don't write to invalid prompt (fix #640)
=> fix: no longer leaking one buffer previewer in some occasions

lua/telescope/builtin/files.lua, lua/telescope/make_entry.lua, lua/telescope/pickers/entry_display.lua, scratch/buffer_highlights.lua, scratch/short_buf.lua
Don't know why the picture is weird, but gives you the right idea at least.
=> feat: buf highlights for current buffer fuzzy find

lua/telescope/builtin/internal.lua
This PR is the implementation for a new option in `buffers listing` which allows viewing of `buffers` which are in the `current working directory` which resolves #733 
@tami5 Could you kindly give me some feedback :)
=> Add option to display buffers which are in cwd 

lua/telescope/actions/init.lua, lua/telescope/builtin/git.lua
- Added a new action called `actions.git_create_branch` that will allow the user to create and checkout a new branch if it doesn't already exist
- Added some basic docstrings for the other git actions
I set the default binding to `<C-a>` to trigger this action when using the `git_branches` picker, but am happy to change that if people don't like it. The best mnemonic keymapping I could think of was `<C-c>` as in **checkout** or **create**, but that obviously will not work as a binding lol. I'm very much open to suggestion on the binding, my thought process was `<C-a>` could be thought of as **add new branch**, even if that doesn't really match the git command itself (since I used `git checkout -b [new-branch]`).
=> git action for creating and checking out a new branch

README.md, lua/telescope/builtin/files.lua
No idea if I've implemented this correctly at all.. however it works.
I wanted to be able to grep just the currently open files, and then put
the results into a quick-list.
All feedback appreciated, and happy to refactor as required.
=> picker(live_grep): add option to grep only over open files

lua/telescope/actions/set.lua
Fixes a bug where files with the same name could not be opened. This PR implements the change as discussed in the related issue #697.
=> Fix: open files with the same name (#697)

README.md, lua/telescope/builtin/files.lua, lua/telescope/make_entry.lua
I noticed that as part of #666 (coincidence???) that sometimes we end up with entries that include the current working directory concatenated with an already absolute path. This would break passing `search_dirs` to `live_grep` as of that commit due to the change in how we were calling `flatten`, which would now mean the search directories weren't a table of their own, but included in the returned arguments. Regardless, this broke something downstream of that picker where the entries would have a path like:
```
/home/amasquelier/.local/share/nvim/site/pack/packer/start/telescope.nvim/lua/telescope/state.lua
```
and we'd prepend them with the `cwd`, resulting in:
```
/home/amasquelier/.local/share/nvim/site/pack/packer/start/telescope.nvim/lua/telescope//home/amasquelier/.local/share/nvim/si …
```
=> fix: live_grep prepending cwd to paths that are already absolute

README.md, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/tests/manual/all_defaults.lua
Adding a history picker analogous to fzf.vim's `History/`. There is no Lua api like `vim.search` as far as I can tell, so I just send the keys a la `/foo<CR>` when selecting a row. Is that the best/acceptable way to do that? I also have not found any tests for command history so haven't wrote any of my own, I am missing something here?
=> feat: add search history picker

doc/telescope.txt, lua/telescope/actions/init.lua
This fixes the max-query treesitter issue in the actions documentation that was caused by #755's docs additions, and is replacing #759 as that PR got messy quickly. @Conni2461 I think the diff looks correct now.
=> Git actions docs fix

lua/telescope/builtin/files.lua
This will fix the problem where the filetype is different than the treesitter lang name. Eg., filetype -> "sh", language name -> "bash"
Ref:
- https://github.com/nvim-telescope/telescope.nvim/issues/795#issuecomment-826043348
- https://github.com/nvim-telescope/telescope.nvim/issues/795#issuecomment-826086757
Fix suggestion by @Conni2461: https://github.com/nvim-telescope/telescope.nvim/issues/795#issuecomment-826769060
=> fix: use treesitter language name instead of ft if available

lua/telescope/builtin/files.lua
File Browser: Instead of adding the parent directory as `../` we could add it as `..\\`.
This tiny change would allow us to navigate to the parent directory.
Otherwise, it would open the parent direcotry in netrw.
=> feat: file browser navigate to parent directory

lua/telescope/builtin/lsp.lua, scratch/clason_finders.lua
If `buf_request_sync` runs into an error, or timeout, it'll return `(nil, err)`.
=> fix(lsp): handle errors from buf_request_sync calls

lua/telescope/make_entry.lua
=> feat: Add only_sort_tags option

lua/telescope/builtin/internal.lua
Fixes an issue that stops the `cwd_only` option working for `oldfiles` when the `cwd` includes backslashes.
---
The results table has filenames with double escaped backslashes, but the cwd has only single escaped backslashes.
This problem stopped this option from working at all on Windows.
=> Fix oldfiles cwd_only that include backslashes

lua/telescope/make_entry.lua
Symbol names can get very long, e.g. when namespaces are involved in C++. I thought it would be a nice addition to make the default values customizable here.
=> Add option to configure width of items in gen_from_lsp_symbols()

README.md, lua/telescope/actions/set.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua
First time developer for lua, neovim plugin, and open source. Please help me in this learning experience.
Partially address #715 
1. Create a `jumplist` picker
2. Jump to row/col on existing buffers (helps for jumplist and also some existing pickers ie. quickfix)
The major limitation right now is that vim `getjumplist()` does not include file text. `vim.api.nvim_buf_get_lines()` does not work because some jump targets are in unloaded buffers. I decided to only include the filename and row/col in the entries, and rely on the previewer to view contents. Open to any suggestions here.
=> Jumplist picker and jump to row/col on existing buffers.

lua/telescope/pickers.lua
I think this fixes #822 and other related cleanup issues.
_(Note: I haven't tested all the setups in the related issues, but it seems to fix all the issues I have encountered.)_
---
**What I think the problem was:**
- On closing the picker, the autocommand defined [here](https://github.com/nvim-telescope/telescope.nvim/blob/e2907fc0f225a7bf33ace6915bc6b55ed1e10b31/lua/telescope/pickers.lua#L451) would be activated.
- This calls `pickers.on_close_prompt`, which calls `Picker.close_windows`
- In layouts without a preview, `status.preview_win` would be nil.
- `del_win` would be called for the preview window, using the nil `win_id`.
- The check for valid win_id [here](https://github.com/nvim-telescope/telescope.nvim/blob/e2907fc0f225a7bf33ace6915bc6b55ed1e10b31/lua/telescope/pickers.lua#L505) …
=> fix: Cleanup on picker close

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/git.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua
Adds git_stash picker
Resolves https://github.com/nvim-telescope/telescope.nvim/issues/799
=> feat: add git_stash picker

lua/telescope/previewers/buffer_previewer.lua
There's a slight lag on the first preview loading (during preview buffer creation).
It is not visible the next time a user chooses a file for preview because a scratch buffer
for the file already exists. This lag *and* setting preview window to display the newly
created buffer before its fully initialized causes a brief flash of a blank terminal background.
This change delays setting preview window to display the new preview buffer and consequently
eliminates the flash. It should improve user experience since flickering can be distracting.
=> prevent fouc on the first preview loading

lua/telescope/pickers.lua
When providing the current Picker with a new finder in Picker:refresh(), the Picker's MultiSelect would still contain the entries from the old finder. This would lead to unexpected behavior when multi-selecting new items after the refresh. To fix this, let's just reset the MultiSelect when the finder is switched out.
=> fix: Reset multi-selection in Picker:refresh()

lua/telescope/builtin/internal.lua
This fixes an issue with the `builtin.buffers` `only_cwd` option that occurs when the `cwd` has an `-` in the name (or any other character that triggers pattern matching).
`string.find()` defaults to _pattern_ matching (rather than string literal matching).
This fix asks `string.find()` to interpret the arguments as literal strings rather than patterns.
Reference: https://stackoverflow.com/a/15258515/181902
=> Fix string.find() matching for only_cwd option

lua/telescope/pickers.lua
When the finder is slow to populate the list of items, I noticed that clicking <up> or <down> quickly after opening a Telescope would error because self.manager wasn't available yet.
`E5108: Error executing lua ...im/pack/mse/opt/telescope.nvim/lua/telescope/pickers.lua:652: attempt to index field 'manager' (a nil value)`
=> fix: abort picker set_selection if no manager

README.md
This is tiny commit; I was setting up the plugin and noticed this discrepancy between the comment in the config and the actual config.
=> Make comment match with config

lua/telescope/make_entry.lua
Fix #763 #874. I'm also hitting the same error when I attempt to `:Telescope treesitter` in .c files.
=> fix: attempt to concatenate when entry.kind == nil or symbol_type == nil

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
We've had several people open issues with this problem recently, I figured we should probably just change this as it's a pretty trivial adjustment. Also added some more docs about the `buffers` picker's specific options. I'll be adding more docs for the rest of the pickers too where I missed their specific options soon now that I have a better idea of where to check. I know that we were going to add this to #415 but I figured we might consider just adjusting this one now with all the recent issues regarding it.
Closes #368 
@Conni2461 thoughts on just making this default, as you and I have responded to several issues lately with people requesting this?
=> Change the `show_all_buffers` option to true by default for `buffers` picker

doc/telescope.txt, lua/telescope/builtin/init.lua
Two options from within the `buffers` function were not
documented. Added documentation for these two options.
=> docs: Add documentation for function `buffers`

doc/telescope.txt, lua/telescope/builtin/init.lua
Removes the unsued `search_dirs` option, and adds `cwd` and `depth`.
=> docs: update builtin.file_browser options

.luacheckrc, README.md, doc/telescope.txt, lua/telescope/actions/mt.lua, lua/telescope/builtin/init.lua, lua/telescope/config.lua, lua/telescope/init.lua, lua/telescope/mappings.lua
Close https://github.com/nvim-telescope/telescope.nvim/issues/582
Its so long that i wrote telescope code. LUL 
I don't like the idea of custom pickers, the one that @tami5 proposed. I think for that people should just continue to go with own wrapper functions. But this helps clean up other things. Like this e.g.
```lua
local actions = require('telescope.actions')
require("telescope").setup {
pickers = {
buffers = {
show_all_buffers = true,
sort_lastused = true,
theme = "dropdown",
previewer = false,
mappings = {
i = {
["<c-d>"] = actions.delete_buffer,
},
n = {
["<c-d>"] = actions.delete_buffer,
}
}
}
}
}
```
I am not sure if this is the best way to implement this feature
=> feat: set defaults for each picker in telescope setup

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/pickers.lua
This will allow users to delete entries  from the picker without closing telescope.
Discussion ref: https://github.com/nvim-telescope/telescope.nvim/pull/803#pullrequestreview-654985978
fixes: #689 
fixes: #621 
fixes: #672  
This function in and of itself will just remove the entry, what I'm proposing next is:
Idea: Should we provide a callback parameter which will be called with the removed entry, so that the user or the specific picker can do exactly what needs to be done outside of telescope? Eg., delete the buffer, delete the file, etc.
The selection strategy is temporarily set to "row" as that will help keep the selection in the same position instead of resetting to the top. If there is any other way to achieve this, do suggest :)
Thanks @Conni2461 for helping! …
=> feat: delete entry from the picker without closing telescope

README.md
Fixes the broken "LSP" hyperlink in the "built in support" section of the README
=> Fix navigation link for LSP pickers

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua, lua/telescope/utils.lua
Closes #846 
This PR adds various flags to enable explicit selection of diagnostics by severity. This preferred over passing `default_text` as the flag is buggy (see issue) and does not allow to group diagnostics.
For instance, you can now filter for "Error" with
`lua require 'telescope.builtin'.lsp_workspace_diagnostics{severity='error'}` or `lua require 'telescope.builtin'.lsp_workspace_diagnostics{severity=1}` 
and limit the search to `Error` and `Warning` with `lua require 'telescope.builtin'.lsp_workspace_diagnostics{severity_threshold='warning'}`
Further, the PR
* Improves sorting: by bufnr (incl. prioritize current buffer), severity, and line number -- bufnr corresponds to hierarchical file tree of project with highest level files having lowest bufnr (though the initially opened …
=> feat: improved configuration and sorting of lsp_{document,workspace}_diagnostics

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/lsp.lua, lua/telescope/utils.lua
Closes #901 
If we have something like this for diagnostics eventually, might as well have it for lsp symbols I suppose.
e: thanks @Conni2461  -- docgen for multiple types seems to work nicely :)
=> feat: add filtering by symbol(s) to lsp_{document,workspace}_symbols

lua/telescope/make_entry.lua
- Problems occured when a register contained newlines
- Caused issues in `Picker:set_selection`
- Couldn't move selection when a register with newlines was selected
I think that this problem wasn't noticed due to the clean-up for entries with newlines in `Picker:entry_adder`.
=> fix: display issues in `:Telescope registers`

.github/ISSUE_TEMPLATE/bug_report.md, README.md, doc/telescope.txt, doc/telescope_changelog.txt, lua/telescope/builtin/init.lua, lua/telescope/config.lua, lua/telescope/config/resolve.lua, lua/telescope/deprecated.lua, lua/telescope/make_entry.lua, lua/telescope/pickers.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua, lua/telescope/themes.lua, lua/tests/automated/layout_strategies_spec.lua, lua/tests/automated/pickers/find_files_spec.lua, scripts/gendocs.lua
Moving to this PR from https://github.com/nvim-telescope/telescope.nvim/pull/823 because of some problems with being able to merge back, but I didn't want to lose the history from that PR.
This should also hopefully make it easier for people to comment on the PR and give us some feedback before merging.
cc @l-kershaw @Conni2461
=> feat: Consistent and sensible layout_config

README.md, doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers.lua
I use the builtin buffers command a lot to switch between buffers. I like it to preselect the previous buffer but when I start typing it'd be nice to have it select the closest match over `default_selection_index`
```lua
require('telescope.builtin').buffers {
sort_lastused = true,
show_all_buffers = true,
selection_strategy = "closest"
}
```
This is perhaps what I'd expect `"reset"` to do but I don't want to mess up anyone's experience.
=> feat: `selection_strategy` closest

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/utils.lua, lua/telescope/mappings.lua, lua/telescope/pickers.lua, scripts/gendocs.lua
This PR closes #900 and implements
* toggling, selecting, and dropping all entries from multi selection
* carves out sugar to apply functions (and collect the result) on entries and multi-selections
* furthermore includes `vim-bbye` action from #906
=> feat: syntactic sugar to map funcs over entries & selections

lua/telescope/actions/init.lua, lua/telescope/builtin/internal.lua
Provide option to `include_extensions` in the `builtin.builtin` picker
- add option `include_extensions` which defaults to `false`
- if `include_extensions` is `true` then add functions from extensions to results
- update `actions.run_builtin` to check if extension function provided
---
Resolves #925
=> feat: option to `include_extensions` in `builtin` picker

README.md
This PR highlights the latest stable release of neovim (v.0.5 is not nightly).
=> Removed comment on nightly in `README`

README.md, doc/telescope.txt, doc/telescope_changelog.txt, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/config.lua, lua/telescope/deprecated.lua, lua/telescope/make_entry.lua, lua/telescope/utils.lua
1. Default overridable values for `hide_filename`, `shorten_path`, and `tail_path`
2. Consistent use of aforementioned values across entry makers
3. extract copy pasted path transformations into a common utility function
* This will probably change filepath display for some pickers for many users.
* I tried some basic manual testing for many of the affected pickers, but may have missed some
* I am not sure how to deal with some of the existing pickers that have default values for `shorten_path` and `tail_path`
* ie. lsp references sets `shorten_path` to true by default
* IMO, these pickers should instead follow global values, and the user can just pass in options to override defaults as needed
=> Consistent filepath display and code cleanup.

doc/telescope.txt, lua/telescope/actions/history.lua, lua/telescope/actions/init.lua, lua/telescope/actions/mt.lua, lua/telescope/actions/set.lua, lua/telescope/actions/state.lua, lua/telescope/config.lua, lua/telescope/pickers.lua, scripts/gendocs.lua
Close #520
Showcase: https://streamable.com/w3wpri
Enabled on default you only need to add mappings
```lua
defaults = {
mappings = {
i = {
["<C-Down>"] = require('telescope.actions').cycle_history_next,
["<C-Up>"] = require('telescope.actions').cycle_history_prev,
},
},
}
}
```
For more information `:help telescope.defaults.history`
CC @saragiotto
=> Cycle prompt history

lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua
When I authored #839, I didn't include the jumplist text because we wouldn't be able to get text for closed buffers. This is a non-issue because I've found in my workflow that that recent entries on the jumplist are always open in a buffer. I think that having the buffer text feels a little better when going through the jumplist picker. For entries that aren't open in a buffer, we include empty text, but we expect it to not be surfaced to the user very often.
Another benefit is that the jumplist picker now reuses the quickfix entry maker, as many other pickers already do. This means we can delete the jumplist entry maker.
This is all opinionated. Open to ideas.
=> Jumplist picker uses quickfix entry maker. Delete jumplist entry maker.

lua/telescope/builtin/internal.lua
When there is an tagstack entry for a closed buffer, there is a `nil` error in [make_entry.lua#L312](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/make_entry.lua#L312) because entry.text is nil. 
```
ordinal = (
not opts.ignore_filename and filename
or ''
) .. ' ' .. entry.text,
```
This fix enters empty text for entries with closed buffers. I think it makes sense, because most people are not regularly closing buffers, especially recently open ones, during their workflow. Therefore, people are unlikely to see entries for closed buffers high up on their Telescope list. So we use empty text as a way to avoid nil errors, but don't expect the empty text to be surfaced to the user often.
Steps to repro:
1. open buffer `A`
2. create a tagstack entry in `A` ie. …
=> Empty string text for closed buffer in tagstack picker.

README.md
Define the undefined variable “action_state”, which is used in a code
example for replacing picker mappings in the README.
The new definiton is added 7 lines above the usage of that variable:
``` lua
local entry = action_state.get_selected_entry()
```
I haven't tested this yet. I just stumbled across this, while reading the documentation, and i wondered: “Where does this variable come from?”
=> Fix: Define undefined variable in config example

lua/telescope/builtin/files.lua
Adds the Windows `where` command as a default file finder.
Note, since `where` doesn't have many options:
- `hidden` and `follow` flags will not change anything
- `search_dirs` only supports a single search directory
I also added an extra check for the `find` command as it is different on Windows and Linux.
---
This allow Windows users to have a usable experience without installing external dependencies that are currently labelled as optional.
=> feat: add Windows `where` file finder command

lua/telescope/builtin/files.lua
- changes check for Windows OS, as 0 is truthy, so `not 0` and `not 1` are both `false`
---
Fixes [this](https://github.com/nvim-telescope/telescope.nvim/commit/999fad2ce514d869b736aa5d948d355fad89be8d#commitcomment-53467463)
=> fix: builtin `find_files`, `find` command `win32` check == 0

doc/telescope.txt, lua/telescope/actions/set.lua, lua/telescope/algos/fzy.lua, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua, lua/telescope/path.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/utils.lua
=> move from telescope/path to plenary/path

lua/telescope/command.lua
Closes #985.
I might need some feedback on if this is the correctly way to deal with a new split keyword since we also have `command.register_keyword` but it isn't being used anywhere. Maybe it's for extensions only and since `search_dirs` is for builtins, it should be in the `split_keywords` table?
=> add `search_dirs` to split_keywords table

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/path.lua, lua/telescope/utils.lua
WIP
Adding option to provide a length for `shorten_path`, not just a boolean, as suggested in #880.
Implemented using `Path:shorten` from plenary as the function in telescope had gotten out of date in comparison.
Todo:
---
Feedback welcome 🙂
=> feat: Add length option for `shorten_path`

lua/telescope/actions/set.lua
In some pickers there is no preview buffer available (e.g. symbols). Pressing <C-d> or <C-u> then results in an error.
Adding a check to make sure a previewer is available and it can scroll to prevent the throwing of an error.
=> fix: prevent error if preview scroll is triggered but no preview is available

lua/telescope/pickers/layout_strategies.lua
This should fix the bug added to master in #847 where `layout_defaults.bottom_pane` is defined twice
=> fix for #847

lua/telescope/pickers.lua
**Why** is the change needed?
So that it can be targeted with specific settings. These could include disabling
plugins for the buffer (as in #840) or disabling folding (as per #991).
**How** is the need addressed?
- Add a filetype to the buffer after it has been created.
Closes #991
=> Set a filetype for the results buffer

lua/telescope/utils.lua
Saw a reddit post where people got confused when they gave a string for `path_display`.
Thought it would be a good idea to check for people.
---
Had to have `hidden` as a separate case, as it allows `path_display` to be the string "hidden".
=> feat: check type of `path_display` and warn user if wrong

lua/telescope/pickers/layout_strategies.lua
- Don't include tabline in the height of the window when present.
- Only applies to `horizontal`, `vertical` and `center` strategies (also inherited by `flex`)
- ~~Tweaks height calculation for `center` strategy~~
Closes #995
=> fix: check if tabline is present when calculating certain layouts

lua/telescope/actions/init.lua
When using git_files and sending the to the qflist, it's not possible to cycle through them using `:cnext`. This PR should fix the path issues by making the path absolute with plenary. It looks like the quickfix-list handles relative path so it doesn't show the entire path if it doesn't need to
=> fix: make path for send to qflist correct

lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
This will allow find_files to find files ignored by .gitignore
and other ignore files. This is supported by fd, rg, and fdfind.
=> feat: add no_ignore option to find_files

README.md, lua/telescope/actions/init.lua, lua/telescope/builtin/git.lua, lua/telescope/builtin/init.lua
**Adding a [git reset](https://git-scm.com/docs/git-reset) action and making it available in the `git_commits` picker.** 
This PR:
- Adds a `git_reset` action
- Adds the above action to the `git_commits` picker
- Maps `<c-r>` to call the action in either normal or insert mode
Like similar actions, the `git_reset` action has a confirmation along with handling of the error and success cases and their messages. The default for git reset is [--mixed](https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---mixed). That behavior is continued here. If this PR is accepted, I'd like to follow-up with [--soft](https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---soft) and [--hard](https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---hard) options in a future PR. I …
=> feat: add git reset action for git commits picker

lua/telescope/builtin/git.lua
fixes #1055 
Problem is that we previously had `vim.fn.expand("%")`, which sometimes returns a relative path. We create a new job, which executes a command from the correct correct working directory, but then the relative path is no longer accurate. We should be using an absolute path with `vim.fn.expand("%:p")
I'm not exactly sure what the behavior of `%` is. From `:h cmdline-special`:
> Note that these, except "#<n", give the file name as it was typed.  If an
absolute path is needed (when using the file name from a different directory),
you need to add ":p".  See |filename-modifiers|.
So I guess if you try to edit a file with `:e <some relative path>`, then git_bcommits() would break.
=> git_bcommit use absolute path for current file.

doc/telescope.txt, lua/telescope/actions/set.lua, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
This prevents an issue caused by [this](https://github.com/nvim-telescope/telescope.nvim/blob/8c3f2b630be0241fe10709e61ee9dab473518f32/lua/telescope/actions/set.lua#L116) on Windows, as filepaths will often contain ":", e.g. "C:\foo\bar". The result was that in the `file_browser` any time you open a file on the C drive, it will instead open a file called "C" 🤣.
=> fix: set a filename for entries in `file_browser`

doc/telescope.txt, lua/telescope/actions/init.lua
When entry.cwd is nil, filename was set to vim's cwd for the quickfix entries
This happens for example with `lsp_references` which returned entries like
```
filename = "/some/absolute/path.hpp",
cwd = nil
```
`Path:new(nil, "/some/absolute/path.hpp")` would turn into `Path:new(nil)` which turns into vim's current working directory with `:absolute()`, leading to the quickfix list items not jumping to the right place.
This should handle the edge-cases correctly, though I didn't find anything that produced a relative `entry.filename` and a `nil` `entry.cwd` at the same time, so I didn't test that explicitly.
=> fix(entry_to_qf): handle nil entry.cwd and absolute filenames

doc/telescope.txt, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua, lua/telescope/config.lua
Add the ability to have runtime additional args to live_grep via a user configurable function. This allows the user to add additional arguments to the grepper program based on custom logic. Example logic that filters search results automatically based on buffer filetype:
```lua
require("telescope").setup {
defaults = { 
-- your defaults for telescope
},
pickers = {
live_grep = {
-- your defaults for live_grep
additional_args = function(opts)
if opts.search_all == true then
return {}
end
local args_for_ext = {
["cs"]  = "-tcs",
["cpp"] = "-tcpp",
["c"]   = "-tcpp",
["h"]   = "-tcpp",
["rs"]  = "-trust",
["lua"] = "-tlua"
}
return { args_for_ext[vim.bo.filetype] }
end
}
}
}
```
The custom logic allows for reverting back to searching all files by passing search_all = true:
:lua …
=> Auto file mask in live grep via additional args function in live_grep

lua/telescope/builtin/lsp.lua
_Logs:_
```
[DEBUG Sat Jul 17 09:36:33 2021] ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:898: Failed to set lines... String cannot contain newlines
[DEBUG Sat Jul 17 09:36:33 2021] ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:898: Failed to set lines... String cannot contain newlines
[DEBUG Sat Jul 17 09:36:33 2021] ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:797: ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:786: String cannot contain newlines
```
_Before:_
_After:_
---
There's also the case where the code action title is very long and the entire Neovim gets frozen and the CPU usage gets high:
=> fix: escape newlines in code action title

lua/telescope/builtin/init.lua
doesn't work correctly if there is a `require("telescope.builtin")` before `telescope.setup`
=> fix: picker config

lua/telescope/pickers.lua
I guess it's orthogonal enough to #987 to be able to merge it right away. Hope there's nothing more to it :sweat_smile: 
More generally, some lower-lever picker functions (specifically, `default_text`, `on_complete`, or that some options can also be passed to pickers individually like `file_ignore_patterns`)  useful to end users are not yet documented though we should document these options at least after #987 or as part of #1024.
Examples: #1095, #1042, frecency's usage of `on_input_filter_cb`, and gitter discussion from which this PR evolved
=> feat: api for clearing completion cb in userspace

README.md
When looking for a way to disable devicons, there's nothing about it on the readme, had to look into the [source code](https://github.com/nvim-telescope/telescope.nvim/blob/ca195e32e0d6e9238fb2dd405e2f794ab8c90819/lua/telescope/builtin/files.lua#L322) in order to find it, it's also not documented on help pages, might be interesting to include this one
=> Add missing disable_devicons option

lua/telescope/builtin/lsp.lua
This PR fixes the bug described in issue #1068 
The `list_or_jump` function could only handle responses in a list format, however servers can also send a single result without surrounding table. This resulted in the jump function not working on some servers, such as zls and clojure_lsp.
=> Builtin `list_or_jump` now handles non list replies from the server.

lua/telescope/builtin/git.lua
Change the formatting of datetime for git_branches for more readability.
=> add separation between date and time

README.md
Fix the reference to neovim LSP pickers by correcting the linked heading name.
=> Fix broken reference in README.md

doc/telescope.txt, lua/telescope/command.lua, scripts/gendocs.lua
This PR allows users to pass vimscripts lists and dictionaries (which are converted to lua tables) when using the vimscript commands for telescope.
For example:
- `:Telescope find_files layout_config={'prompt_position':'top'}` will now move the prompt to the top
- `:Telescope find_files search_dirs=['~/foo','~/bar']` will set the `search_dirs` to `~/foo` and `~/bar`
- `:Telescope find_files search_dirs=~/foo,~bar` will still work too
Implementation:
- The implementation relies on `vim.fn.eval`, as it seemed better to me to rely on a robust existing method for converting between vimscript objects and lua objects, rather than try to make my own and miss some edge cases.
- This choice of implementation can cause some unusual methods of configuration for some things, e.g. `:Telescope …
=> feat: allow tables in vimscript command parser

lua/telescope/builtin/lsp.lua, lua/telescope/command.lua, plugin/telescope.vim
This fixes #1119 which was caused by lacking range support for the command parser `:Telescope`. 
Based on the documentation for `:h command-range`, it should not have any side-effect apart from allowing ranges on the command. I also forward the line numbers to the command parser and store the values in the `opts` table. Any function can access these values later on.
With this patch it works both with visual select (`:<,>Telescope lsp_range_code_actions`) and with direct range numbers (`:13,15Telescope lsp_range_code_actions`).
=> Allow range parameters on command parser

lua/telescope/command.lua
Found another mistake immediately after we merged #1124, sorry guys 😅
Currently `master` doesn't work if you use lua syntax for tables.
---
I feel like we should have some sort of tests for the command parser to avoid this happening in the future, but not really sure how to set it up. Is there a good way of testing if a picker has loaded correctly with the current testing framework?
@tjdevries / @Conni2461 any ideas?
=> fix(command parser): evaluate valid lua expressions

lua/telescope/mappings.lua
Partially fixes https://github.com/nvim-telescope/telescope.nvim/issues/429
default mapping change: `["<CR>"] = actions.select_default + actions.center` -> `["<CR>"] = actions.select_default`
When selecting to edit an empty entry, the telescope floating window does not close. Then, `actions.center` changes the prompt buffer to normal mode triggering prompt buffer bugs in https://github.com/nvim-telescope/telescope.nvim/issues/429 and https://github.com/nvim-telescope/telescope.nvim/issues/852.
I also think its awkward that by default, `select_default` mapping is followed by `actions.center`, while `select_(horizontal|vertical|tab)` default mappings are not. This change brings some consistency. The `actions.center` action is kept around in case users want to map to it.
If we want, we could …
=> Remove center action after select_default action in default mappings.

plugin/telescope.vim
Should close #1132
When no arguments are passed to a command, `<f-args>` is simply removed from the definition, which causes `:Telescope` command to fail because of bad syntax (it calls `lua require('telescope.command').load_command(<line1>, <line2>, <count>, )`)
With `unpack({<f-args>})`, if no arguments are provided it returns `nil` by default, and then when arguments are provided, they are expanded correctly
=> fix(command_definition): default to nil on empty <f-args>

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
Closes #1072
- keep insert
- also look in `.local/share/nvim/telescope/symbols/*.json` for symbols
can be overriden with `symbol_path`
The only thing that is currently bothering me is that you end up in insert mode even if you started in normal mode. 
- Done this with actions `:enhance` good interface
CC @clason better late than never :rofl:
=> fix: for telescope.symbols

lua/telescope/builtin/init.lua
Fixes #1145
This happens because we removed our packed deepcopy. So i refactored
this part to not do a deepcopy
=> fix: pickers config mappings

lua/telescope/sorters.lua
@mroavi does this fix your problems? This will make sure that initial sorting isnt touched for any sorter. 
@fdschmidt93 mentioned that he wants to work on a pr that makes element inserting more configurable so you can say always respect initial sorting and probably we can configure this correctly for some builtins.
But i would still push for this hotfix because it restores that initial default behavior for internal sorters we had prior to async_v2
=> fix: for default sorters how we insert data if #prompt == 0

lua/telescope/builtin/files.lua
Since #288 was abandoned, it would be nice to have `&tags` used appropriately without the additional changes that were difficult to implement there. Here, there's just a loop over the tag files to read. Resolves #909
=> Add support for &tags

lua/telescope/actions/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua, lua/telescope/previewers/previewer.lua, lua/telescope/previewers/term_previewer.lua
Would close #714 by introducing a new previewer that reuses existing buffers.
@Conni2461 Idk, personally a bit torn on this. While `previewers.new_buffer_previewer` feels backward for `builtin.buffers` that we already have, though now ofc the buffer for `actions.delete` has to be replaced prior to deletion and the solution generally feels bloat. I'm not sure there are other side effects (that's why I abstained touching `new_buffer_previewer`, as we'd have conflicting logic ala creating buffers vs using existing ones).
I'm personally fine with terminal buffers not being highlighted ;)
=> fix: (terminal) buffer previewer

lua/telescope/builtin/internal.lua
In #1120, builtins.buffers added an `attach_mappings` function, but didn't return a value from it.
This causes an error in:
```
E5108: Error executing lua ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:178: Attach mappings must always return a value. `true` means use default mappings, `false` means only use atta
ched mappings  
```
=> fix(pickers): attach_mappings on builtins.buffers needs return

lua/telescope/previewers/buffer_previewer.lua
Flex previewer (I guess?) may lead to the previewer not being shown and therefore `preview_fn` is never called and `state` is never set up. This ensures we only teardown `state` if it's actually created.
Edge case I've of course ran into coming home and using the buffer picker (which I never use) once again :laughing:
=> fix: safe teardown of buffer previewer

lua/telescope/previewers/buffer_previewer.lua
=> fix: autocommands cursor outside of buffer

lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua, lua/telescope/utils.lua
The [tpope/vim-vinegar plugin](https://github.com/tpope/vim-vinegar) offers great file/directory navigation and creation features. This is particularly helpful when you want to make edits to files in close proximity to your open buffer. 
It accomplishes this using the builtin `netrw` vim script. Telescope's `builtin.file_browser` does basically all I want in regards to file manipulation and navigation. The only thing that is missing is that it does not have the option of opening up in a *relative* location to your open buffer.
Add a `relative (boolean)` option to `builtin.file_browser` function. So when `true`, the file browser will open at current buffer's directory (overriding `cwd` option):
```lua
require('telescope.builtin').file_browser({ relative = true })
```
Add `buffer_dir()` …
=> feat: add utility for fetching buffer directory

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/algos/linked_list.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/config.lua, lua/telescope/make_entry.lua, lua/telescope/pickers.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua
Will close #751
What?
- Introduce `resume` (resume last picker) and `pickers` (picker over cached pickers) `builtin` pickers
How?
- Modify `pickers.lua`  so picker attributes are not `nil`-ed on detach but stored in global `cached_pickers` table-stack instead
- `cache_limit` > 0 reduces # of cached entries via `LinkedList:truncate` (primarily to reduce size)
- New buffer previewer that writes original results in preview
Showcase
https://user-images.githubusercontent.com/39233597/127784598-e3d32413-2957-4fc5-8a1e-8ea6598b42b2.mp4
=> feat: allow caching and resuming picker

doc/telescope.txt, lua/telescope/actions/generate.lua, lua/telescope/actions/init.lua, lua/telescope/actions/utils.lua, lua/telescope/mappings.lua, lua/telescope/utils.lua, scripts/gendocs.lua
Will close #1062
E: I've hid a lot of discussions to improve readability.
Previews v5 w/ popups and right titles (mode hint with `opts.only_show_current_mode`)
Prompt at bottom
Prompt at top
=> feat: show keymaps for builtin actions

README.md
3-4 people look at the PR and of course I only think of it right after merging :laughing:
=> chore: add `action.which_key` to README

lua/telescope/previewers/buffer_previewer.lua
Thankfully a very easy fix to close #1200 by clearing out the previous state adequately.
@ram02z would you please confirm that it fixes the issue for you as well? I realize change seems trivial and it does everything it's supposed to on my end, but just to make sure it works elsewhere just as well :)
=> fix: clear buffer previewer fully for caching

README.md
Looks like 618e0e6075b4215e43c6a848daa37ef4e354b5dc dropped this entry, just adding it back.
=> Add builtin.jumplist back into README.md

lua/telescope/actions/init.lua
Fixing overriding of numbers passed as `opts` being overridden with the result of a repeated string (causing errors on subsequent calls)
---
When using `telescope.actions.generate`, the same table reference is passed. From this, if we override a value in that table (originally a number) with a string, we get errors later. To replicate this, setup a mapping that uses `require("telescope.actions.generate").which_key({ only_show_current_mode = false })`, toggle the `whichkey` popup on, then try to toggle it off again.
CC: @fdschmidt93
=> Fix whichkey overriding opts

lua/telescope/builtin/files.lua
This PR adds the word to the prompt title for grep string. Example when `use` is searched for:
=> Add word to prompt title for grep string

lua/telescope/builtin/init.lua
This adds a layer when requiring the builtin submodules to be loaded
only when a picker is actually invoked.
Ref: https://github.com/tjdevries/lazy.nvim
Talked about this on gitter with @fdschmidt93 
This is a direct copy of the function from `lazy.nvim`, we can update the name if necessary but I don't think it should be as it is self explanatory.
=> perf: load builtin submodules when a picker is invoked

lua/telescope/pickers.lua
Closes #1203 
@dhruvmanila testing to confirm whether this PR also fixes the issue on your end would be very welcome :)
@Conni2461 happy to get your sign off,  we now check whether `window` or `_completion_callbacks` are already in `opts` and add `scroll_strategy`, such that all of these options inherit adequately while allowing to user to override them
=> fix: restoring picker table/function opts 

lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua
Closes #1226 
@Akinsho does this also work for you? Your hunch is correct and I can reproduce this when resuming a buffer previewer to jump to a buffer for which the lnum for the respective buffer became stale in the mean time (eg from deleting bottom).
Not 100% sure about your tabpage log buffer scenario though :sweat_smile: I've tried to keep it simple and practical.
=> fix: stale lnum in buffer previewer

README.md, doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/lsp.lua
Adds `lsp_type_definitions`, similar to `lsp_definitions` and `lsp_implementations`.
=> feat: lsp type definitions

lua/telescope/builtin/files.lua
This matches the behavior of fzf, if a user needs to pass additional
arguments they can use additional_args or change vimgrep_arguments.
See #1211 for discussion of this solution, this fixes bugs that were introduced by #987
=> [Fix] Add no more flags delimiter for ripgrep

lua/telescope/finders.lua, lua/telescope/finders/async_oneshot_finder.lua
`from_string` doesnt exist. Its called `gen_from_string`
=> fix: default make_entry

.github/workflows/ci.yml, .github/workflows/docgen.yml, .github/workflows/lint.yml
continuation of what i liked in #970 
- no more appimage
- ubuntu and mac os
- release and nightly
Also works in `act` now (stylua action does not work in act, but that is no big deal)
=> chore: rewrite ci

lua/telescope/builtin/lsp.lua
Fix implemented based on the discussion at https://github.com/neovim/nvim-lspconfig/pull/429#discussion_r537110059
And the code snippets in the [jdtls implementation](https://github.com/neovim/nvim-lspconfig/blob/486f72a25ea2ee7f81648fdfd8999a155049e466/lua/lspconfig/jdtls.lua#L62) 
If merged with the [code_actions_fixup](https://github.com/nvim-telescope/telescope.nvim/pull/735) branch, would fix the problem of Java users not being able to use codeactions
=> feat: Remove version field if zero from codeaction calls

.github/ISSUE_TEMPLATE/bug_report.yml, LICENSE, README.md, developers.md, doc/telescope.txt, lua/telescope/actions/generate.lua, lua/telescope/actions/utils.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/command.lua, lua/telescope/config.lua, lua/telescope/init.lua, lua/telescope/make_entry.lua, lua/telescope/pickers.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/previewers/init.lua, lua/telescope/themes.lua
Ready for Review :)
Rework of readme and wiki (live) + more stuff for vimdoc.
Now that we have vimdocs it makes sense to move some of the more specific documentation in the readme to the vimdocs. That affects mostly setup defaults and other stuff. `vimdoc` > `README`
Basically we need a better introduction for new users.
Todo:
vimdoc. But we need to make that people can put configurations in the wiki, so i need to clean it up)
Close #506 (its clearer now that it is required to have ripgrep installed)
Close #806 (same)
Close #780 (document that it is a lua regex with lua documentation link)
Close #277 (this is mostly already done, after the documentation changes we can close it)
Close #596
Close #1197
Close #1204
CC @tami5 @smithbm2316 @rockerBOO 
Shorthand to new rendered documents:
- …
=> Rework documentation

lua/telescope/actions/set.lua
When opening a file under swap from the "fd" finder results an error was
printed after the file was opened, wrapping the call to "vim.cmd" in a
pcall avoids the error.
Issue: #445
=> fix: wrap vim.cmd in pcall to avoid error

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua
Addresses #623 
Allows premature skipping previewing when filesize is too large or reading file + parsing of lines exceeds timeout.
What's primarily missing is to make timeout and filesize limit configurable.
=> feat: skip/timeout preview if file cannot be easily previewed

lua/telescope/previewers/utils.lua
Slight logical error that syntax highlighting fallback doesn't kick in in case treesitter test returns false while having `preview = { treesitter = true}}`.
@clason I think that should fix your issues if I understood them correctly. Apologies, my bad.
=> fix: fallback to syntax hl if treesitter fails

lua/telescope/previewers/buffer_previewer.lua
Closes #1252 
Does that fix it for you @Akeboshiwind? Sorry, copied from the wrong one where return slipped in the else clause. Wasn't an issue for `mime_hook`.
=> fix: stacked hooks in buffer previewer

lua/telescope/builtin/internal.lua
After changes on &rtp in neovim/neovim it's neccessary to use `nvim_get_runtime_file` instead https://github.com/neovim/neovim/pull/15632 
Checked the rest of the codebase and the issue pattern `globpath(&rtp ...)` is not present anywhere else.
=> fix(builtin): internal.help_tags not finding all tags

lua/telescope/pickers.lua
Hi again @fdschmidt93 .
So, the diff is just two lines and it's pretty much exactly what you suggest on #1182 issue. I'm ready to make any changes if needed.
=> Fix #1182: pickers use entry.filename as default and fallback to entry.value

lua/telescope/themes.lua
Adjust the sizing options for themes since [this PR](https://github.com/nvim-telescope/telescope.nvim/pull/1039) has been merged.
Discussed in comments of the PR starting [here](https://github.com/nvim-telescope/telescope.nvim/pull/1039#issuecomment-922489474).
=> fix: update themes after `layout_strategies` refactor

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/make_entry.lua, lua/telescope/utils.lua
**WIP**
Use the new left truncation of strings from plenary to truncate paths.
Currently just a minimal implementation that doesn't take stuff like "are there icons" or "how long is the selection_caret" into account.
Also think it _could_ be a bit of a performance hit with this implementation, but haven't thought about it properly yet.
Demo:
Could be useful for [this issue](https://github.com/nvim-telescope/telescope.nvim/issues/1167) and similar to implementation in [this comment](https://github.com/nvim-telescope/telescope.nvim/issues/1167#issuecomment-921268416).
=> feat: `truncate` option for `path_display`

lua/telescope/builtin/lsp.lua
The code added in #738 attempts to access `action.command.arguments[1]` unconditionally, but the [LSP specification](https://microsoft.github.io/language-server-protocol/specification#command) defines `arguments` as optional. This PR adds a check to make sure `action.command.arguments` is not `nil` before accessing it.
=> fix(lsp): check if action.command.arguments is nil

lua/telescope/previewers/buffer_previewer.lua, plugin/telescope.vim
Add a highlight group to be used when displaying a message in the ```buffer_previewer``` with the function [```set_timeout_message```](https://github.com/nvim-telescope/telescope.nvim/blob/4816a27d7680feed293d21a945c476947af20d29/lua/telescope/previewers/buffer_previewer.lua#L59).
=> feat: add highlight group: TelescopePreviewMessage

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua, plugin/telescope.vim
~~I think some users will appreciate this `head` example using plenary (which I used b/c I wasn't sure whether `head` command is fully OS-agnostic, whereas plenary implementation looks like it is).~~
PR got quite a bit broader:
- Improve docs
- Introduce filetype_hook
- Allow setting highlight groups for `TelescopePreviewMessage` and `TelescopePreviewMessageFillchar`
- Allow setting `msg_bg_fillchar` via `preview` in `telescope.setup`
- factor out `set_timeout_message` to `set_preview_message`
And closes #1288
=> feat: filetype_hook & improved docs; fix preview partial override

plugin/telescope.vim
I was testing the plugin with the lastest merge in the master and noted the highlight 'TelescopePreviewMessageFillchar' was incorrectly declared as 'TelescopePreviewFillchar'.
I also think it should by default link to 'TelescopePreviewMessage', so the user can choose to set 'TelescopePreviewMessage' to change both or to set each one individually.
=> fix highlight declaration of 'TelescopePreviewMessageFillchar'

lua/telescope/actions/init.lua, lua/telescope/builtin/internal.lua
This continues the fixes done in 4816a27d7680feed293d21a945c476947af20d29 (ref #1283).
The only picker that shows this error now (of those I tested) is `Telescope buffers` - I did not fix this one because there is already a message saying "[telescope] Nothing currently selected" above the nil error message (not sure why it's shown twice).
=> fix: show error message when nothing is selected

lua/telescope/actions/init.lua
@l-kershaw could it be that one of the recent plenary popup PRs might have broken positioning of `actions.which_key`? :sweat_smile:  Judging by one of the PR titles alone I tried this fix and seems to work. If you could please confirm this should be fine, that'd be great :) thanks
=> fix: which key float positioning

README.md
This came up on Gitter. You can make the argument `telescope.setup` per README is not "clean" anymore, but it's not intended as a COPYME. Nevertheless, it's an outlier. I don't really have an opinion, whatever works.
~~(Created the PR right from GH, there's a slight error that `<C-h>` needs to be a string, don't behead me just yet ;)~~
cc @clason
=> chore: highlight which_key on README

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/themes.lua
This PR adds the `prompt_position` option for the following layout stratgies:
- `vertical`
- `bottom_pane`
- `center`
`vertical` was noted as being "planned" in the code
`bottom_pane` was requested in [this comment](https://github.com/nvim-telescope/telescope.nvim/issues/765#issuecomment-851753342)
---
EDIT: I have now also added some more flexibility to the `get_dropdown` and `get_ivy` themes if the user customises the `prompt_position`
=> feat: more prompt position strategies

lua/telescope/previewers/buffer_previewer.lua
Closes #1213 
This is a slightly (but totally ok) hacky solution because we'd otherwise need `hl_mode` to affect `hl_group` in `nvim_buf_set_extmark`.
@lcrockett does it now work as expected for you? For me it seems to work as expected with your minimal config.
=> fix: stacking highlights in buffer previewer

README.md
This really killed me when I was looking at this plugin for the first time. I spent like 20 minutes googling how to get search results into the quickfixlist because ctrl-F for "quickfixlist" on the README yielded no results!
There's nothing wrong with using the abbreviation in some places, but it should appear at least once in the form of `abbreviation (abbr.)`. That is, spelling it out next to the abbreviation at least once shows the reader the abbreviation they can search for next to learn more.
Note that most of the changes are whitespace; the only content change is on line 211; `qflist` => `quickfixlist (qflist)`
=> doc: clarify quickfixlist abbreviation in README

.github/workflows/ci.yml, README.md, lua/telescope/builtin/init.lua, plugin/telescope.vim
Neovim 0.5.1 is required for #1403 or it will cause a segfault.
=> breaking: bump nvim version requirement to 0.5.1

doc/telescope.txt, lua/telescope/config.lua
Closes #1404, #1263
Binary filetype detection with `file` should be opt-in for Windows users as they don't have it by default, and if they have it, it seems to be causing some issues.
=> fix: deactivate binary ft detection for Win32

lua/telescope/actions/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua, lua/telescope/previewers/term_previewer.lua
This essentially reverts #1120 (my mortal enemy :laughing: ) because of a multitude of issues and unexpected behavior.
To elaborate:
- very tedious to apply highlights to the actual buffer without interfering with the actual buffer
- mru is unfixably broken because the previewer defacto uses the buffer
- Unexpected behavior with autocmds (see also https://github.com/nvim-telescope/telescope.nvim/issues/1345)
- Some other stuff I don't remember/can easily trace right now
Closes https://github.com/nvim-telescope/telescope.nvim/issues/1300
=> fix: revert buffers previewer

doc/telescope.txt
Think the docgen didn't run for some reason on #1403.
=> docs: generate docs for `hl_result_eol`

lua/telescope/actions/init.lua
`actions.git_checkout_current_buffer` should call `action_state.get_selected_entry` instead of `actions.get_selected_entry`.
=> Fix actions.git_checkout_current_buffer calling wrong method

lua/telescope/previewers/init.lua
While trying out generating documentation on my local machine I have noticed PR #1433 has modified the documentation file but not the source file the content is being generated from.
=> fix typo in previewers documentation

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/set.lua, lua/telescope/mappings.lua
WIP
Doesn't look quite right to me when scrolling upwards as the selection looks like it is alternating between the top and the middle of the results window. Any suggestions to fix this would be appreciated 🙂
Fixes #1430
Fixes #1326
=> feat: results scrolling actions

doc/telescope_changelog.txt, plugin/telescope.vim
Adds a changelog explaining the version bump and points users to it when they don't have the right version.
I can't think of a way of checking if someone has an old version of nightly to give them the error on launch as well.
If anyone can think of one, then that would be helpful.
Fixes #1443
=> docs: add a changelog entry for updated version requirements

doc/telescope.txt, lua/telescope/themes.lua
There seems to be a typo in the themes section of the help text.
=> Fix typo in telescope.txt

lua/telescope/builtin/lsp.lua
After https://github.com/nvim-telescope/telescope.nvim/pull/738 was merged, codeactions stopped working with some language servers. They work correctly e.g. for elmls, but fail for purescriptls and haskell-language-server.
Actions popup shows up, but when an action is selected, no changes are applied.
The problem seems to be with the `transform_action` function:
https://github.com/nvim-telescope/telescope.nvim/blob/782d802d44077e07f80189560f91c86370f11e39/lua/telescope/builtin/lsp.lua#L258-L272
An example code action payload that I get from purescriptls is:
```lua
{
"title": "Remove unused references",
"command": "purescript.replaceSuggestion",
"arguments": {
"file:///path/to/Main.purs",
"import Some.Module (xx)",
{
"end": {
"line": 16,
"character": 60,
},
"start": {
"line": 16, …
```
=> Fix LSP code actions not working for some language servers

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/utils.lua
Requires nvim-lua/plenary.nvim#268
Users can specify which parts of the path to exclude from shortening.
Still defaults to shortening everything except the tail of the path.
Will probably mostly be used as `exclude = {1,-1}`, which shortens everything except the first folder, and the tail.
Resolves #880
=> feat: `exclude` option for `shorten` in `path_display`

lua/telescope/pickers.lua
This PR exposes the `{prompt, results}_border` to the picker, such that the title can be changed on the fly with `picker.prompt_border:change_title` which is a nicety of the upcoming file browser extension.
In addition, it allows possibly maintaining multi selections when a finder is refreshed.
=> feat: allow changing results/prompt title & persisting multi on picker:refresh

lua/telescope/builtin/files.lua
Unclear to me at first sight as to why stylua job on `master` [fails](https://github.com/nvim-telescope/telescope.nvim/runs/4215016043?check_suite_focus=true) with a 4 months old change :sweat_smile: 
Testing how CI reacts if we were to make that change.
E: That's fine, though my local stylua keeps formatting it the same way.. probably stylua has change somehow? I'll update the binary once I'm home.
=> chore: reformat files.lua after stylua update

lua/telescope/builtin/internal.lua
Little fix for error message on `builtin.resume` when trying to resume a picker past the cache size
=> fix: use `string.format` on `builtin.resume` error message

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/layout.lua, lua/telescope/config.lua, lua/telescope/pickers.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/utils.lua, scripts/gendocs.lua
This is a combination of #1305 and #1383.
Big thanks to @johnybx for the implementation of the preview toggle.
Demo:
`toggle_preview`
`toggle_prompt_position`
`toggle_mirror`
`cycle_layout_next`/`cycle_layout_prev`
=> feat: layout actions (including `toggle_preview`)

CONTRIBUTING.md, developers.md
Some spelling / grammar fixes
Ironically misspelling `grammar` in the commit message... :hand_over_mouth:
=> docs(spelling/grammer): fix spelling and some minimal grammer changes

lua/telescope/pickers.lua
Fixes a small error I was getting after updating today.
```
packer.nvim: Error running config for telescope.nvim: ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:1244: attempt to index local 'opts' (a nil value)
```
=> fix: error when opts is nil

lua/telescope/actions/init.lua, lua/telescope/actions/mt.lua, lua/telescope/mappings.lua, lua/telescope/pickers.lua, lua/tests/automated/action_spec.lua
Closes #684
- without actually changing the public interface
- without having a local table that keeps track of all actions
I could write more tests for this but its Friday evening and it was a long day ...
My take on https://github.com/nvim-telescope/telescope.nvim/pull/1093
=> fix: action mt so we can again concat actions from two different tables

lua/telescope/make_entry.lua, lua/telescope/pickers/entry_display.lua
This PR extends `entry_display.create` to allow passing functions or fractional values to `width` option.
It also adjusts one of the widths in `make_entry.gen_from_quickfix`.
The widths in other `make_entry` functions can also be adjusted in the same way, but I am less familiar with them, so don't know what good choices would be for them.
This PR is aimed at reducing issues like #1380, where the hardcoded values for widths aren't optimal for some screen/picker sizes. That being said I'm not 100% sure if this resolves #1380. @wellcomez does this (or something along these lines) fix your issue?
=> feat: extend functionality of `entry_display.create`

lua/telescope/pickers.lua
In a GUI that follows the multigrid UI, `winblend` must be set for all overlapping float windows in order to make them transparent. 
Since the current telescope.nvim does not have `winblend` set for border windows, the winblend setting in the telescope is disabled in the multigrid GUI. Thus, there is a border window that is not set to be transparent behind each float window.
This PR also sets `winblend` for the border float window generated by telescope.nvim, which fixes this problem.
=> fix: Border window also need to be winblend due to window overlap in multigrid UI

lua/telescope/pickers.lua
Fixes issue pointed out by Conni [here](https://github.com/nvim-telescope/telescope.nvim/pull/1480#issue-1060554567)
Before:
After:
=> fix: keep previewer `winid` state updated on layout changes

lua/telescope/previewers/utils.lua
The function just replicated the logic from is_enabled and assumed the
`disable` setting is always a table. This is no longer the case (https://github.com/nvim-treesitter/nvim-treesitter/pull/2009), it can now also be a function.
Do I understand this correctly that the only reason telescope does not use `ts_configs.attach_module` and writes its own `treesitter_attach` is that `attach_module` does not return a boolean indicating success?
=> fix(highlight): Use TS built-in is_enabled function

lua/telescope/make_entry.lua
Because Elixir source code can contain `|`, the removed substitution sometimes broke `lsp_document_symbols()`.
Example:
```
E5108: Error executing lua ...packer/start/telescope.nvim/lua/telescope/make_entry.lua:392: attempt to concatenate local 'symbol_name' (a nil value)
...packer/start/telescope.nvim/lua/telescope/make_entry.lua:392: in function 'entry_maker'
...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: in function 'new_table'
...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:137: in function 'v'
...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:500: in function 'v'
...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:496: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:467> …
```
=> fix: Remove symbol_msg substitution

lua/telescope/builtin/files.lua
fix #1504
this happens if parsers are installed but highlight is set to false.
So parsing the buffer with treesitter will automatically apply them to
the buffer but because treesitter highlighting is disabled it will
change the buffer. Its stupid and i dont know why you want parser
installed but highlighting disabled but whatever.
We just dont calculate highlights for people who have highlight set
to false
=> fix: dont change highlights when using current_buffer_fuzzy_find

lua/telescope/finders/async_oneshot_finder.lua
The use case for this in `telescope-file-browser` is prepending the current directory in the folder browser when using `fd`, since `fd` of course blocks a lot less than scan dir in large repos.
The canonical shell equivalent of that would be `echo "." && `fd -t d` (see also https://github.com/sharkdp/fd/issues/364) but I don't think plenary Jobs supports that.
I guess it's a bit of an edge case and I honestly couldn't think of other good uses. At the same time it should be pretty harmless because `finders` yells if `results` are passed, so you'd have to user the lower level api anyways.
=> feat: allow results in async_oneshot_finder

lua/telescope/make_entry.lua
Check if Windows drive letter (e.g. "C:") is present when parsing vimgrep
Fixes #1396
@younger-1 does this work for you?
=> fix: check for Windows drive letter when parsing vimgrep

doc/telescope.txt, lua/telescope/config.lua
Now matches the description and has space for a preview above the central block
Fixes #1481
=> defaults: change `center` layout default size

lua/telescope/builtin/lsp.lua
```
Error executing vim.schedule lua callback: ...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:52: attempt to concatenate local 'err' (a table value)
...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:52: in function 'handler'
...w/Cellar/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp.lua:957: in function 'cb'
vim.lua:285: in function <vim.lua:285>
```
`err` is a table value for lsp-handler.
https://github.com/neovim/neovim/blob/master/runtime/doc/lsp.txt#L212-L215
lsp log
```
vim/lsp/rpc.lua:451    "rpc.receive"   {  error = {    code = 0,    message = "no packages returned: packages.Load error"  },  id = 11,  jsonrpc = "2.0"}
```
=> fix concatenate err

doc/telescope.txt, lua/telescope/builtin/git.lua, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
Currently entry items in git stash aren't displayed properly. Here's an example:
_Before_
Note that:
1. There is a space before the entry item text
2. The whole entry is not displayed (because this commit message contains a colon)
Here is the equivalent output from `git stash --no-pager list`
This commit fixes this issue by changing the split delimiter and including everything after the second '`:`' in the displayed entry text.
_After_
As an aside, I do think it would be useful to also show the branch name, as you get with the command line output. Happy to add this into the PR if you agree.
=> fix: git stash entry formatting

lua/telescope/pickers/layout_strategies.lua
@max397574 does this PR fix your issue?
Fixes #1557
=> fix: `bottom_pane` remove `results` border next to `prompt`

lua/telescope/previewers/buffer_previewer.lua
The module name was being calculated as 'init' but the pickers are all prefixed with 'builtin'.. the directory name for 'builtin', not the 'init.lua' filename.
=> Fixed module name for builtin picker, correctly jump to description

doc/telescope.txt, lua/telescope/pickers/layout_strategies.lua
Adds `mirror` option to `center` layout
This switches the position of the preview window to below the central block, rather than above.
=> feat: `center` layout `mirror` option

lua/telescope/_extensions/init.lua, lua/telescope/builtin/internal.lua
`:Telescope builtin include_extensions=true` currently errors when the `telescope-file-browser.nvim` extension is being used, as it exports some stuff as tables (e.g. actions) which breaks `debug.getinfo`. I don't think we want to stop extensions from exporting actions and things, so I've added a check for the `func_obj` actually being a function.
@fdschmidt93 just pinging as an FYI, in case this comes up as an issue over on the `file-browser` repo.
Also, in the case of `file-browser`, I'm not sure if we want both `file_browser` and `picker` to be included, so we could maybe add a check for beginning with a "_" to exclude from the builtin `picker`. This way extension creators can choose which exported functions to include here?
=> fix: `builtin` only have entries for extension functions

lua/telescope/builtin/diagnostics.lua
This PR is the minimum viable solution to disambiguate between "Workspace" and "Document" diagnostics (ie once `bufnr`) is passed.
Of course we could also add some more info in the prompt title.
One other way I like, which would be a departure from how we've been doing it would be:
* Prompt title: "Diagnostics"
* Results title: "Workspace" or filename (or buf number)
Any thoughts/preferences here?
=> feat: workspace & document diag in title

lua/telescope/actions/init.lua
required after upstream changes to prompt buffer behavior (see https://github.com/neovim/neovim/commit/28134f4e78819c2bbf0344326b9d44f21eb0d736)
Fixes #1608
(I doubt anyone besides me has ever used this action... @Conni2461)
=> fix(actions): force insertmode after inserting symbol

lua/telescope/finders/async_oneshot_finder.lua
Fully complete #1461, forgot to process the entry.
~~E: On second thought, it begs the question a bit on whether the entry should be added preprocessed to results or not. Preprocessing makes sense I suppose, in which case we could just close this.~~
E2: Forget what I said, I forgot the difference of `process_result` and preprocessing (or more accurately, why I did this PR :laughing:) because I intermediately thought it just worked. The problem is that on the first rendering the added `results` are not shown because `process_result` is otherwise not called.
=> fix: actually generate entries for passed result

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
Remove `run_builtin` as it's really not that useful, as per the discussion in https://github.com/nvim-telescope/telescope.nvim/pull/1544#issuecomment-991623542
=> chore: remove redundant run_builtin action

lua/telescope/utils.lua
Sometimes i get with live_grep:
```
Finder failed with msg:  ...nfig/nvim/plugged/telescope.nvim/lua/telescope/utils.lua:324: bad argument #1 to 'match' (string expected, got nil)
```
This happens when rg runs on a binary file, like a pdf. Then the parsing fails. We should maybe also make sure that we dont do anything if the line parsing fails. Regardless `transform_path` should not error if filepath is nil
=> fix: transform_path nil input

lua/telescope/builtin/files.lua
We added this for rg 13.0 release because it was needed but it doesnt
seem to be needed anymore. Weird
This might be due to some changes in neovim or due to changes to jobs.
I'll build 0.5.1 and test it with that right now. If it doesnt work on 0.5.1 we move this PR back after the 0.6 bump.
Edit: also seems to work for 0.5.1 What am i missing.
=> chore: remove dot at the beginning

doc/telescope.txt, lua/telescope/_extensions/init.lua, lua/telescope/init.lua
This is a mundane fix for a stupid issue with extensions. For instance, when trying to set mappings from telescope-file-browser or telescope-hop with extension actions, one `require`s the extensions module prior to setup and then user configuration is not applied.
This is a minimal fix within the existing API. I'm curious, what substantive value does `require "telescope".load_extension $EXTENSION` actually add? Alternatively, we could just invoke set up when the extension config is forwarded.. otherwise any extension within telescope interface just has it's default config.
Generally speaking, this is not the most prettiest fix, but maybe more intended to get the ball rolling on a discussion as I didn't want to break the `load_extension` interface just yet.
Once something along these lines …
=> fix: too early setup on initial extension access

lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
I'm sure it'll get users to switch. They have to press `<CR>` for the notice to go away :sweat_smile:
=> chore: deprecation notice for builtin.file_browser

lua/telescope/builtin/internal.lua
With the new API for keymaps, the picker errors on trying to concatinating the `rhs` if a Lua function is used. This fixes the error and also uses the `desc` opt if it is specified.
=> fix: picker for keymaps error with new api for keymaps

lua/telescope/mappings.lua
As described in https://github.com/nvim-telescope/telescope.nvim/issues/1579, this adds `<C-w>` to the default mappings.
=> feat: Add <C-w> to default mappings

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers.lua, lua/telescope/pickers/highlights.lua, plugin/telescope.vim
Adds an icon next to multi-selected entries in a picker.
Icon defaults to "+". Functionality disabled by setting to "".
The corresponding highlight group is called `TelescopeMultiIcon`.
Demo:
Resolves #1551
=> feat: multiselect icon

lua/telescope/pickers/highlights.lua
@deryrahman @gegoune does this fix your issue?
See [comment](https://github.com/nvim-telescope/telescope.nvim/commit/f285599440fcdbf97a7f44d120d403c80316f576#commitcomment-63007223) for details of problem
=> fix: allow `selection_caret` to be entirely whitespace

doc/telescope.txt, lua/telescope/builtin/init.lua
The current documentation accidentally used start_line for both fields, making the documentation both incomplete and confusing.
Renaming the second field will bring this in line with the intended documentation, as well as the behaviour of the function.
Hopefully this is the correct file to change, as the docs/telescope.txt seems to be generated from this.
=> Fix documentation for lsp_range_code_actions

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/entry_manager.lua, lua/telescope/pickers.lua, lua/tests/automated/entry_manager_spec.lua
`opts.fzf_tiebreak()` can be set to a function which is passed the ordinal of the entry we're checking and the ordinal of the existing result when they have identical scores.
The default value sorts them based on the length of the ordinal, this is the default for fzf.
If you want to sort them in the order they appear in the file then you could use this:
```
opts.fzf_tiebreak = function( current_entry, existing_entry ) return false end
```
FZF allows a tiebreak to choose based on where the matched pattern is in the string. I need to check if we have access tot he search word or if we need to pass it as a 3rd parameter to this function.
=> Added an opts parameter to be used when entry scores are tied

README.md, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
The `builtin.file_browser` will be spun off into its own extension: https://github.com/nvim-telescope/telescope-file-browser.nvim (not yet accessible to public) The extension will incorporate a lot of demanded features and essentially constitutes #1257.
Hence, it makes sense to cut out the picker from `telescope-core`. Note that the PR should not yet be merged but is a prep for the initial release of the extension, which will happen throughout the upcoming week.
(Cutting out is also necessary, such that `:Telescope file_browser` adequately forwards to the extension.)
=> breaking: remove file browser

lua/telescope/config.lua, lua/telescope/pickers.lua
Adds a counter for the number of entries in the multi-selection.
Example:
Note: new counter isn't displayed when nothing in the multi-selection
=> feat: adds multiselect counter in prompt status_text

lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua
Updated the result pane of the builtin picker `keymaps` to be more coherent with some other pickers by using the `|` to seperate information for each entry (e.g. like `commands`, `quickfix`). The width of the middle column is adjusted dynamically so the lhs of the keymap doesn't get cut off.
Before:
After:
Some feedback if everything is ok, would be nice, as I'm still a bit new to lua.
=> feat: make results pane of builtin `keymaps` more readable

doc/telescope.txt
On the PR #1453 the `file_browser` has been remove from the builtint, it was remove from almost all places but the documentation, so it still part of the help when checked from neovim.
=> Update doc to remove file browser

lua/telescope/make_entry.lua
Fixes #1604
@dagle does this work for you?
---
The only time that I can think of this new regex breaking would be if there are sequences of exclusively digits between colons in the filename or the text. However, I'm not the best with regexes, so it would be good if someone else could have a look at it. 
Do we want to add `^` and `$` to the regex too? Can't find a circumstance where doing this breaks anything, but, again, I'm not the best with regexes 😅
This change also means that we don't need to have separate functions for windows/non-windows users, as I introduced in #1494. So its good that we can simplify the code a bit too 🙂
=> fix: handle filenames with colons in `live_grep`

lua/telescope/command.lua
For a week I've been typing `:Telescope lsp_reference` instead of `:Telescope lsp_references` and wondering why it stopped working, then I found out that typo.
=> feat: show a message for unknown command

lua/telescope/actions/init.lua
followup to #1618, ensure insert after cursor
(turns out bang means `A`, not `a`. classic reading fail 🤦🏻 )
=> fix(action): insert symbol in insert mode

lua/telescope/builtin/internal.lua
When using this picker I noticed that some autocommands where not showing. From my own setup, calling `:verbose au *` retrieves 4 kinds of metadata (from most common to least common):
1. `Last set from {filepath} line {linenr}`
2. `Last set from anonymous :source`
3. `Last set from anonymous :source line {linenr}`
4. `Last set from {filepath}`
Case 2 and 4 are now also picked up and defaulted to the first line in the document (even tho the `anonymous :source` one doesn't go anywhere)
=> fix: picker `autocommands` doesn't show all autocommands

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
This pull request adds the following:
- Add visual mode to the default keymap modes
- Make the shown keymap modes a configurable option
- Add a configuration option to not show <Plug> keymaps (by default it will show them, which is the same behaviour as before this pull request)
- While implementing this, I found out there are duplicates present in this picker (also present before this pull request) which happens when for example for "!" mode keymaps is added twice because it is both a "i" and "c" mode keymap
=> feat: add configuration options to builtin `keymaps`

lua/telescope/builtin/internal.lua
`z=` works even when `spell` is not set. I think it would be nice if Telescope would behave the same.
If you think this should be a setting, I'll look into how they work in telescope an add it.
=> feat(spell_suggest): ignore spell setting

lua/telescope/actions/init.lua
Changes functions that use `setqflist` in `r` mode to instead use
` ` mode. This makes the Telescope quickfix list action send results
to a new list in the quickfix stack instead of overwriting the
entries in the current list. Doing so enables `:chistory`, `:colder`
and `:cnewer` functions to review results of previous Telescope
queries.
The location list uses a similar API and is updated in this PR also
(ie this also enables `:lhistory`, `:lolder` and `:lnewer`).
=> fix(actions.qflist): make it work with vim quickfix commands

lua/telescope/previewers/buffer_previewer.lua
Resolves: #1727
The issue seems to be that this snippet in `new_buffer_previewer` is sometimes scheduled after setting the cursor in the `define_preview` function.
https://github.com/nvim-telescope/telescope.nvim/blob/f262e7d56d37625613c5de0df5a933cccacf13c5/lua/telescope/previewers/buffer_previewer.lua#L366-L370
This will result in an error when going from a small preview buffer to a large preview buffer and trying to set the cursor at the end of the larger buffer, because it will try to set the cursor in the smaller buffer.
I tried to quickly replicate the issue with other previewers using `nvim_win_set_cursor`, but wasn't able to do so, so I didn't change anything to them.
But since this is kinda an easy mistake to make and hard to debug, maybe the `define_preview` function call in …
=> fix: builtin `autocommands` throws error

doc/telescope.txt, lua/telescope/builtin/diagnostics.lua, lua/telescope/builtin/files.lua, lua/telescope/builtin/git.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/make_entry.lua
When buffer/window specific pickers are selected from the `:Telescope builtin` picker, the current buffer & window becomes Telescope itself making many of the pickers practically useless.
This PR sets `opts.bufnr` and `opts.winnr` when `:Telescope builtin` is ran. Buffer and window sensitive pickers can then reference those values when called via the `builtin` picker (if not set, use the current bufnr/winnr via `vim.api.nvim_get_current_buf/win()`).
closes #1678
Considering the builtin picker is probably where many new users try out the various builtin pickers, I think getting all the pickers functional from within the builtin picker is quite important.
Fixes or tweaks to allow for fix:
- `files.treesitter`
- `files.current_buffer_fuzzy_find`
- `files.current_buffer_tags`
- `git.bcommits` …
=> fix: add opts.bufnr and opts.winnr to builtin picker

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers.lua
Added a config option `wrap_results` to wrap the results in all pickers. Requested in #701  and #1296.
Default option is false. Same as current behavior. If user chooses, they can set this value true in setup call and see the results wrapped.
Unwrapped behavior:
Wrapped behavior:
On a git_commits picker
=> feat: allow user to wrap picker results (#701, #1296)

lua/telescope/previewers/buffer_previewer.lua
im `pcall` ing it as per the suggestion of @Conni2461
i also removed the vim.schedule as the other previewers didn't need it either
Fixes: #1754
=> fix builtin.autocommands throwing error

doc/telescope.txt, lua/telescope/pickers/layout_strategies.lua
Affects `telescope.pickers.layout_strategies.center` that is used by dropdown (`telescope.themes.get_dropdown`) theme, allowing more customization for dropdown theme, i. e. setting it in the top with mirrored preview.
Some may argue that it is already possible to do that with vertical layout, although vertical layout uses fixed height, so toggling preview squeezes the result prompt, while center layout has dynamic height and shows the preview without squeezing the result prompt.
[Example of the initial proposal](https://i.imgur.com/9LHjKT3.gif) (obsolete)
EDIT: 
As discussed (see comments), beyond changing the center layout to allow vertical anchoring, I updated the change to make preview window fill the rest of the screen (which is the original purpose of center layout) and also changed …
=> Change center layout strategy to allow vertical anchoring

README.md
Required adding a new section for mandatory dependencies.
I can rename things if you don't like the name.
=> Link plenary.nvim dependency in README.

lua/telescope/actions/init.lua, lua/telescope/from_entry.lua
Items added to the quickfix list should not have their paths escaped because then Neovim can't open them.
My specific case is paths such as `src/routes/api/trackables/[trackable_id]/index.ts`, where the brackets would be escaped when adding to the quickfix list. 
I think #1700 is the same problem but I don't have a Windows box to test on so can't be 100% sure. I did also test this fix on MacOS with a filename containing spaces and it works fine.
1. Create a file with some escapable character such as a space or `[`.
2. Open neovim in that directory, use a telescope picker to show the file in the list, and hit `<c-q>`.
3. Notice the extra backslashes in the escaped filename in the quickfix list, and that trying to open the file from the quickfix list fails. Neovim tries to open the path …
=> Skip path escaping when adding items to quickfix list

lua/telescope/pickers.lua
Checks if the picker entry selected exists before actually selecting it.
Resolves #1751.
=> Fix: error on select empty picker entry (#1751)

lua/telescope/make_entry.lua
Hi
I was suffering some dire performance around showing `rg` results. I've tracked it down to some large files with unusual content, specifically content with sequences like `2:3:1:0`.
With content like this the initial greedy matching captures more than the filename which went on to cause the poor performance.
This should fix that by making the matcher non-greedy.
```lua
local line = [[a/file/path:12:99:text with a time (kinda) :08:10: not a real time]]                                                                                                                                                         
local _, _, filename, lnum, col, text = string.find(line, [[(.+):(%d+):(%d+):(.*)]]) …
```
=> Make `make_entry` filename parser non-greedy

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/lsp.lua
~I don't know why this isn't default, but I added an option `include_declaration` in case someone, for some reason want to have the current line from which the lsp-references was called be the first item in the picker.~
Recent changes will just ignore current line from the result by default. Which is sufficient. `include_declaration` will still be an option though default to true.
=> feat(lap_references): exclude current line

lua/telescope/pickers.lua
Some extensions (e.g. `dap`) use integer numbers for their selector options instead of strings.
Before this commit, the interface for these plugins breaks when using `ui-select` with a stack trace like the following:
```
Error detected while processing function StartDebugger:
line   33:
E5108: Error executing lua .../telescope.nvim/lua/telescope/pickers.lua:1359: Should be string, found: number
[C]: in function 'assert'
.../.vim/bundle/telescope.nvim/lua/telescope/pickers.lua:1359: in function 'new'
...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:22: in function 'pick_one'
.../nvim-dap/lua/dap/ui.lua:32: in function 'pick_if_many'
.../nvim-dap/lua/dap.lua:225: in function 'select_config_and_run'
.../nvim-dap/lua/dap.lua:551: in function 'continue'
[string …
```
=> Number type should be allowed for option keys

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/command.lua, lua/telescope/utils.lua
Adds new option to ignore symbols. Essentially same as `opts.symbols` but only ignores given symbols and doesn't do any checking whether the symbol is valid or not.
extracted from #1449.
=> feat(lsp): ignore_symbols

lua/telescope/builtin/files.lua
This doesn't work
`$ find . -type f -L`
find: -L: unknown primary or operator
But this works well
`$ find -L.  -type f`
=> fix: follow with find command

doc/telescope.txt, lua/telescope/builtin/diagnostics.lua, lua/telescope/builtin/init.lua
Adds support for filtering diagnostics by:
1. A root directory. Useful to browse only project-scoped diagnostics.
2. `buflisted` status. Useful to exclude diagnostics from unlisted buffers, which are created by language servers that analyze the entire project/workspace (e.g. `sumneko-lua`).
=> add filter options for diagnostics builtin

developers.md
The documentation for developers in `devloper.md` references the file
`entry_display.lua`. But the specified path to the file is wrong. It
seems to have been moved some time ago. I found it in the folder
`pickers`.
=> Fix path in documentation

lua/telescope/actions/layout.lua
Fixes #1793
@seblj can you confirm that this fixes the issue for you on your machine?
=> fix: default `layout_config` to `{}` on `cycle_layout` actions

doc/telescope.txt, lua/telescope/config.lua
In the history section of the documentation description (docs/telescope.txt), the warning line sounds like an incorrect grammar:
Warning: If limit is set to nil it will grown unbound.
=> docs: fix typo 'grown' in documentation

lua/telescope/builtin/lsp.lua
Nothing big... just encountered a typo in neovim's status bar. This fixes that.
=> Fix a small typo in a LSP error message

lua/telescope/builtin/files.lua, lua/telescope/previewers/buffer_previewer.lua
This PR fixes both the preview and default action for `tags|btags` when tags contains special characets.
Tested with the below file:
```cpp
#include <stdio.h>
const char s01[] = "[\\[]~$?*|{}()^%-+./'%\"\r\n\t";
const char s02[] = "\\";
const char s03[] = "[";
const char s04[] = "]";
const char s05[] = "~";
const char s06[] = "$";
const char s07[] = "?";
const char s08[] = "*";
const char s09[] = "|";
const char s10[] = "{";
const char s11[] = "}";
const char s12[] = "(";
const char s13[] = ")";
const char s14[] = "^";
const char s15[] = "%";
const char s16[] = "-";
const char s17[] = "+";
const char s18[] = ".";
const char s19[] = "/";
const char s21[] = "\"";
const char s22[] = "'";
const char s23[] = "%";
const char s24[] = "\r";
const char s25[] = "\n";
const char s26[] = "\t";
void …
```
=> fix tags|btags for all special characters

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers.lua
Currently both `results_title` and `prompt_title` can only be changed when a picker is executed. This PR makes those fields global so that they can be set in Telescope setup's `defaults` property.
=> Allow results_title and prompt_title to have global default values

lua/telescope/actions/set.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/pickers.lua
fixes https://github.com/nvim-telescope/telescope.nvim/issues/1038
fixes #1520
Whenever telescope does not sort of edit/selection action, it calls `nvim_win_set_cursor()`, which does not add anything to the jumplist. As noted in the issue, this affects `lsp_references` picker. This PR adds the current location to the jumplist, as [neovim builtin LSP does when jumping to location](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L1015-L1021).
Builtin LSP also adds the current word to the tagstack. I didn't add it in this PR because I don't want to copy and paste code, but if we want it I can quickly add it in.
This change affects all edit/selection actions, and I'm not sure if its desirable in all cases and pickers. Open to discussion.
=> Save position into jumplist before 'edit' action.

lua/telescope/pickers.lua
Setting `tabstop = 1` immediately after creating prompt and result buffers 
fix #1834
=> fix: displayer when tabs are used and ts is != 1

doc/telescope.txt, lua/telescope/actions/generate.lua, lua/telescope/actions/history.lua, lua/telescope/actions/init.lua, lua/telescope/actions/layout.lua, lua/telescope/actions/set.lua, lua/telescope/actions/state.lua, lua/telescope/actions/utils.lua, lua/telescope/builtin/init.lua, lua/telescope/command.lua, lua/telescope/config/resolve.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/previewers/init.lua, lua/telescope/themes.lua
turns out @tjdevries already implemented `module` in tree-sitter-lua some time ago.
Finally `:help telescope.builtin.find_files` is a thing
=> docs: add module prefix

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
Added option to trim results text.
=> feat(lsp): added trim option to make_entry.gen_from_quickfix

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/utils.lua, plugin/telescope.vim
Adds the ability to choose the color that is used for rendering the icon when `color_devicons` is set to `false`.
```lua
local colors = require 'gruvbox.colors'
defaults = {
color_devicons = false,
},
}
vim.api.nvim_set_hl(0, 'TelescopeResultsFileIcon', {fg = colors.neutral_red})
```
_This is ugly but just to illustrate_
=> feat: add default hl group for devicons

lua/telescope/actions/init.lua, lua/telescope/actions/utils.lua, lua/telescope/utils.lua
Out of laziness, I now left `action_mt` docs out, because their main purpose otherwise (apart from originally for `which_key`) I suppose is sufficiently described in `:h telescope.actions`
Works as intended in my tests. If you don't like it @Conni2461 , it's totally fine :sweat_smile:  felt like a challenge and my experiments are running on GPUs now anyways.
Closes #1869 
My test code
```lua
local builtin = require("telescope.builtin")
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")
local M = {}
M.print_prompt = function(prompt_bufnr)
local current_picker = action_state.get_current_picker(prompt_bufnr)
current_picker:_get_prompt(value)
print(prompt)
end
function print_value(prompt_bufnr)
local value = …
```
=> feat: show assigned function in actions.which_key

.github/workflows/ci.yml, README.md, doc/telescope_changelog.txt, lua/telescope/builtin/init.lua, plugin/telescope.vim
I will most likely merge this this Friday and tag the commit prior to this PR with 0.6.1
After this PR is merged we can look at:
=> break: bump minimum required neovim version to 0.7

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/internal.lua, lua/telescope/pickers.lua, plugin/telescope.vim
Ensure that `keepinsert` works correctly in `actions._close()` in nvim-0.7 after https://github.com/neovim/neovim/commit/28134f4e78819c2bbf0344326b9d44f21eb0d736
Fixes #1599
=> fix: make keepinsert work with nvim-0.7

lua/telescope/actions/init.lua, lua/telescope/actions/utils.lua
Some fixups :sweat_smile: 
1. Rightfully trigger notification only if we have `"<anonymous>"`
2. Get full `source` path
3. Clean up table assignment functions (ie `["<C-a>"] = function(...)`) 
(1) Apologies Conni, I too quickly moved the notification last minute inside the loop (in my tests it was always rightfully triggered when it may not be) and (2) we have to get the full path via `source` as paths were otherwise truncated after 60 chars.
As per lua [docs](https://www.lua.org/pil/23.1.html)
> source --- Where the function was defined. If the function was defined in a string (through loadstring), source is that string. If the function was defined in a file, source is the file name prefixed with a `@´.
So, that's why `gsub("@", "")`.
Lastly, (3) is unfortunate because of how mappings …
=> fix(which_key): get full path & handle funcrefs in tables

README.md, doc/telescope.txt, doc/telescope_changelog.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/lsp.lua, lua/telescope/command.lua, lua/telescope/themes.lua, plugin/telescope.lua
i still need to write a changelog entry
=> chore: remove code actions

doc/telescope_changelog.txt
This PR fixes a misspelled reference to `vim.lsp.buf.code_action`.
#1866 removed code actions from telescope and referred to `vim.lsp.buf.code_actions`. There only exists `vim.lsp.buf.code_action`
=> Fix the reference to vim.lsp.buf.code_action

lua/telescope/pickers.lua
Closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/128
Sorry guys, but `initial_mode="insert"` wants another rodeo.
It seems to work appropriately with visual and insert mode in my tests, but can you please also take this once for a spin as I'm aware at least some of you have use cases that would stress test this? That would be very much appreciated :)
`nvim_input` seems to appropriately fit into the event-loop of the finder rather than `nvim_feedkeys`.
@Conni2461 @kylo252 @clason 
E: Summary
+ This fixes that finder loop currently is triggered twice with `initial_mode="insert"` (relevant for `on_complete` callbacks)
- Requires users haven't remapped `<ESC>` and `A` to anything materially otherwise what they are doing by default
=> fix(finder): don't trigger twice w/ inital_mode="insert"

lua/telescope/actions/mt.lua
As per `action_mt` docs 
```lua
...
--- an action is metatable which allows replacement(prepend or append) of the function
---@class Action
---@field _func table<string, function>: the original action function
---@field _static_pre table<string, function>: will allways run before the function even if its replaced
---@field _pre table<string, function>: the functions that will run before the action
---@field _replacements table<string, function>: the function that replaces this action
---@field _static_post table<string, function>: will allways run after the function even if its replaced
---@field _post table<string, function>: the functions that will run after the action
```
which implies `_{pre, post}` should not run if replaced (as opposed to `_static_{pre, post}`)
```lua
local builtin …
```
=> fix(actions): don't exec pre or post if replaced

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
`builtin.commands` should keep the same with `builtin.keymap`: show buffer local commands.
=> Feat: add support for builtin.commands to show buffer commands (update).

doc/telescope.txt, lua/telescope/actions/history.lua
This link didn't have an HTTPS prefix so it wasn't clickable. The other
link to 'telescope-smart-history.nvim' is clickable.
=> docs: add 'https://' prefix to smart history link

lua/telescope/builtin/lsp.lua
Neovim deprecated `resolved_capabilities` in https://github.com/neovim/neovim/pull/17814
Replace with `server_capabilities` and adapted feature table, which is backwards compatible with 0.7.
=> chore: adapt to resolved_capabilities deprecation

lua/telescope/make_entry.lua
Currently `:Telescope treesitter` shows this warning:
`nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text`
This PR changes it to use the upstreamed function (which was added in 2020 https://github.com/neovim/neovim/commit/d7b12e58dfc7303dbc06381a9bedd5c3539d5413)
=> use upstreamed get_node_text() instead of nvim-treesitter's deprecated one

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/pickers.lua, lua/telescope/previewers/init.lua, lua/telescope/previewers/term_previewer.lua
fix #1804
- fixes the buffer leaking
- cleanup termopen previewer
- fix teardown for termopen_previewer
CC @bluz71 can you test this. And i am very sorry for the long wait
=> fix: termopen previewer

lua/telescope/pickers.lua
Um, yeah, not gonna lie, this is satirically stupid but seems to work.
Importantly, this does not work appropriately if startinsert is invoked otherwise (`vim.cmd` or `vim.fn.execute`)
I think we can rely on `<ESC>` though :laughing:
Fixes:
- Code cleanup between initial modes `"normal"` and `"insert"`
- `initial_mode="normal"` wouldn't function properly if original mode was not `"normal"`
- `initial_mode="insert"`: raw input `startinsert!` to avoid `A` which might be mapped otherwise and cannot be fed with `nvim_feedkeys` (see code comments)
Closes #1894
=> fix(pickers): misc inital_mode setting fixes

lua/telescope/pickers.lua
Reverts nvim-telescope/telescope.nvim#1895
Many more people have issues when trying to circumvent `A`.
Sorry @yutkat -- I'll do my best to fix your problem soon in a more universal way.
=> Revert "fix(pickers): misc inital_mode setting fixes"

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua, lua/telescope/builtin/internal.lua
Closes #1877 
Quick showcase for accessibility of PR
1. Showing quickfix history is empty (`:chistory`)
2. Sending some builtin pickers to quickfix list
3. Launching `quickfixhistory` (in lack of better name, in mood to make quick tele PR)
https://user-images.githubusercontent.com/39233597/164985535-7d32b9f2-5b7e-4967-9618-15e8b0064be1.mp4
I'm aware that we are not necessarily interested in builtins, but I think this one would make a rare exception since it deeply relates to `(n)vim` builtin features made more accessible via telescope.
@Conni2461 it seems to work well, but I unfortunately underutilize the qflist. The qflist generally is weird (there is `id`s for more than 10 qflists? But in practice only 10 lists keep the full history? But only tried creating more than 10 lists once, …
=> feat: quickfixhistory picker

doc/telescope.txt, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
- `glob_pattern` string: argument to be used with `--glob`,
e.g. "*.toml", can use the opposite "!*.toml"
- `type_filter` string: argument to be used with `--type`,
e.g. "rust", see `rg --type-list`
```vim
:Telescope live_grep glob_pattern=!*.txt
:Telescope live_grep type_filter=lua
:Telescope live_grep type_filter=make
```
=> feat(rg): add glob and type filter opts by default

lua/telescope/pickers.lua
followup to 544c5ee40752ac5552595da86a62abaa39e2dfa9
fix #1912
fix #1909
@bluz71 I kindly ask you if you could validate that this doesnt break term previewers again :) I tested it and didn't notice any regression but just making sure :laughing:
=> fix: another teardown issue

lua/telescope/pickers/entry_display.lua
@Conni2461 do you mind this diff? b/c https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/118 needs this in scenarios in which `vim.ui.input` intermittently leaves prompt buf. Then I hope that PR is done, it will make interaction a lot more smoother.
A bit stupid, but simplest fix.
=> feat(entry_display): expose prompt_bufnr opt

lua/telescope/utils.lua
Before:
After:
Telescope integration with `nvim-web-devicons` used to work well with most files but not with files like `.bashrc`, `.zshrc`, `CMakeLists.txt` because their extension is different from their filetypes.
Other plugins like barbar, NvimTree and feline display these icons correctly
Also when calling `get_icon` the `extension` parameter is set to `nil` because extension is already computed by `nvim-web-devicons`: https://github.com/kyazdani42/nvim-web-devicons/blob/cde67b5d5427daeecfd7c77cf02ded23a26980bb/lua/nvim-web-devicons.lua#L1531-L1532
=> fix: correctly use nvim-web-devicons

lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua
`:marks` command shows local marks for current buffer and global marks.
However, current buffer is not identical to original buffer when called from `builtin.builtin`, so it won't show buffer local marks.
This P-R uses `vim.fn.getmarklist()` to mimic the behavior of `:marks` command.
=> get mark list from opts.bufnr instead of using :marks

doc/telescope.txt, lua/telescope/actions/set.lua, lua/telescope/config.lua, lua/telescope/pickers.lua
TODO:
- Add utility function or something that can make this easy to pass in "editting_win" only.
When we do that, we can probably close: https://github.com/nvim-telescope/telescope.nvim/pull/531/
And then users can configure how they desire :)
=> feat: Add ability to choose window to edit

lua/telescope/actions/set.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/pickers.lua
Atm telescope doesn't populate the tagstack making it confusing when you jump with a telescope function, where it populates the tagstack if there is only 1 item.
=> Set tagstack when we jump with lsp in telescope

doc/telescope.txt, lua/telescope/builtin/git.lua, lua/telescope/builtin/init.lua
This closes #826, just wanted to put up this PR as a way for us to discuss this. While I don't personally ever have a use case that I _don't_ want to see untracked files by git when fuzzy searching in my projects, I do think that this default does make more sense, considering how fzf.vim's `:GFiles` command and `git ls-files` work by default. We do have a lot of people transitioning from fzf who may find this default confusing. Perhaps it could be documented in more detail as well if we feel that's necessary, I'd be happy to make that happen. 
cc @mhinz @kaddkaka @clason
=> Change default behavior of git_files to be the same as git ls-files' default and fzf.vim's GFiles

lua/telescope/actions/init.lua, lua/telescope/actions/set.lua, lua/telescope/pickers.lua
Closes #1185 
This is quite similar to #1165. If I understand it correctly `vim.cmd [[stopinsert]]` is just too slow. So I guess what happens then is you actually land in the original window in insert mode and only leave it there, which, being on the original cursor position, means you exit insert mode to land in one column to the left. (Conversely, exitting in normal mode works just fine).
The other solution I supposed would be to await `vim.cmd` though this should surely feel faster (& not sure how I'd to that in new plenary async).
=> fix: exiting picker from insert mode

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/pickers.lua
I've recently played a bit around with Emacs magit (blasphemous I know) to see what the fuzz is about (I also started playing with mlua to essentially expose the sync library of [gitui](https://github.com/extrawurst/gitui) which can blow magit diff parsing parallelized out of the water).
Anyways, neither here nor there, but Vertico as a really nicely integrated framework got me thinking whether we can have similar things with telescope (i.e. telescope as `vim.ui.input` with some niceties I suppose). This PR and example code were 20 minutes playing around with the idea (we can polish `attach/detach` later).
Showcase
https://user-images.githubusercontent.com/39233597/164539336-1df5953d-f246-4d91-a52a-9316df4347ee.mp4
Example code
```lua
local builtin = require("telescope.builtin")
local …
```
=> feat: none strategy & control attachment

lua/telescope/actions/init.lua, lua/telescope/builtin/files.lua, lua/telescope/builtin/git.lua, lua/telescope/builtin/internal.lua, lua/telescope/builtin/lsp.lua, lua/telescope/config.lua, lua/telescope/config/resolve.lua, lua/telescope/make_entry.lua, lua/telescope/pickers.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/sorters.lua, lua/telescope/utils.lua
I actually wanna remove it but tj uses it in his configs. So lets throw a bunch of errors for him :rofl: 
I even used his employers software to find the code: https://sourcegraph.com/github.com/tjdevries/config_manager/-/blob/xdg_config/nvim/lua/tj/telescope/custom/live_workspace.lua?L61:28 #ad
=> chore: deprecate get_default

lua/telescope/builtin/internal.lua
close #1755 
Copying over `all_previewers` to `previewer`, so it works if multiple previewers are set. Also set `opts.previewer = false` If previewer was previously hidden
CC @fdschmidt93
=> fix(resume): previewer if toggled

lua/telescope/builtin/internal.lua
=> fix: executing commands with arguments in case of remapping :

lua/telescope/actions/init.lua, lua/telescope/pickers.lua
Closes https://github.com/nvim-telescope/telescope.nvim/issues/1940
Acceptance criteria listed in the issue.
=> Force buffer delete for terminal

doc/telescope.txt, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
`ripgrep`, `fd` and `find` all support the `no-ignore` option, which doesn't obey ignore files present in the local directory. This is currently exposed in the API for `find_files`. A similar option, `no-ignore-parent`, allows the underlying program to not obey ignore files in parent directories.
This adds support for the latter, and covers the cases of other programs that do not support this option.
=> Add support for no-ignore-parent option in find_files.

lua/telescope/builtin/files.lua
This allow to start grepping before having to preprocess all the tagfiles entries.
Can be interested if the tag we are looking for is at the beginning of the tagfile.
Still issues of refresh (https://github.com/nvim-telescope/telescope.nvim/issues/1981).
The `Path:new(vim.fn.expand(ctags_file, true)):iter()` performance hit was not as big as when I first tried to implement it.
This could be because I was on a local machine with a SSD, or that the repo I was using previously used a bunch of hardlink.
=> feat(tags): process tagfiles on the fly

lua/telescope/builtin/git.lua
The diff to parent preview is blank but at least a user can follow a file around various moves and get access to the SHA-ID for the move.
=> Add `--follow` to bcommits

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/lsp.lua, lua/telescope/make_entry.lua
As discussed in https://github.com/nvim-telescope/telescope.nvim/issues/1409, the lsp_document_symbols picker wasn't handling its options properly. The `ignore_filename` option was always set to `true`, and the `show_line` option was effectively ignored. In addition, if `show_line` did work, it would result in the line and column number being displayed, rather than the actual source line (which is what other pickers do, except for the treesitter picker).
This commit fixes both issues. When `show_line` is enabled, the source line is displayed. Line and column numbers are not shown, mostly to keep the behaviour the same as other pickers. If this information should be shown (which didn't work before anyway), it should probably use a separate option.
This fixes …
=> Fix option handling for lsp_document_symbols

lua/telescope/builtin/internal.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua
This is so much cleaner, but we no longer have the source file and linenumber where the autocmd was defined. Currently we get the information with `verbose` and open the appropriate file on `<CR>`
I dont see an open other than parsing `verbose autocmd` again on `<CR>` or removing it or patching neovim. `help nvim_get_option_info()` also returns
```
• last_set_sid: Last set script id (if any)
• last_set_linenr: line number where option was set
```
So i dont think it is that wrong to include it (maybe hide behind a verbose option)
=> chore: cleanup autocmd builtin

README.md, doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/builtin/lsp.lua
=> feat(builtin.lsp): implement builtin handlers for lsp.(incoming|outgoing)_calls

doc/telescope.txt, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
ripgrep supports multiple `--glob` flags. 
This gives us the ability to do interesting queries. A simple example will be: search in all `lua` files that are not in test directory.  
This query in telescope will look like this
```:lua require"telescope.builtin".live_grep{ glob_pattern = {"*.lua", "!**/test/**/*"} }```
=> feat(rg): pass multiple globs to rg by default

lua/telescope/pickers.lua, lua/telescope/previewers/previewer.lua
=> chore: clear previewer if no item is selected

lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/utils.lua
Telescope creates most floating windows with `noautocmd = true`, so
these windows do not trigger autocommands, but preview buffer is set in
window using `nvim_win_set_buf()`, which triggers buffer autocommands.
This may be unwanted, so block them using `'eventignore'`.
=> fix: block autocommands when setting preview buffer

lua/telescope/builtin/git.lua
Fix this "Invalid key: 1" error when we open a diff in vertical/horizontal/tab in the builtin `git_commits` and `git_bcommits`.
Thank you.
=> fix: Error caused by the invalid options in create_autocmd for vimdiff

lua/telescope/builtin/files.lua
This fixes #2023  by addressing the specific crash I was running in to. The generic solution of cleaning up windows on crashes probably would need fixing on the Pleanary side.
```
NVIM v0.8.0-dev+436-g279bc71f3                                                                                                                                                                                                                                                   …
```
=> fix: grep_string crashes when string has newline

lua/telescope/from_entry.lua
`vim.fn.filereadable` returns 1/0 which should be checked explicitly.
```
NVIM v0.8.0-dev+519-g6f6286e4f
Compiled by ustc1314@pop-os
Features: +acl +iconv +tui
See ":help feature-compile"
fall-back for $VIM: "/usr/local/share/nvim"
```
```
Pop OS 21.04
```
=> fix: filereadable should check for 1 or 0

doc/telescope.txt, lua/telescope/builtin/files.lua, lua/telescope/builtin/init.lua
This option offers a simple way to reduce results for a find_files search without taking away functionalities.
The behavior is similar the `grep _ string` functionally but in this case we are searching for file names.
To give just a small example but one most people here should be able to relate we could take the scope of one personal nvim config. Often it contains several files with similar names like `lsp*` or `git*`. With this commit one could use the `search_file` option to show and overview his files with a `lsp*` / `git*` name and then use the given functionalites as usual to preview and further search the results.
For me personally, such an option solves several use cases where I want to list a specific set of files with a keymap.
- New feature (non-breaking change which adds …
=> feat: search_file option for builtin fd command

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/previewers/utils.lua
First of all just say that's my first "contribution" to any open source project. I hope with time the contributions are bigger :). This change makes more sense for me that the logic that it's being use now, but maybe not for everyone. Any feedback welcome.
If the languages exists in the config, only the file-types that match with
the ones on the table will be affected by the treesitter boolean.
The config now will look like this:
```lua
defaults = {
preview = {
treesitter = false,
languages = { "perl", "javascript" },
},
},
```
That will make that only `perl` and `javascript` will use regex for the highlight and any other file-type will use treesitter if possible.
=> feat: languages table to specify treesitter highlighing

doc/telescope_changelog.txt
Small typo and grammatical fixes to the changelog from the dev branch in #1945.
- Documentation change
* Neovim version (nvim --version): NVIM v0.8.0-dev+532-g60604d6a9
* Operating system and version: macOS 11.6.7
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation (lua annotations)
=> docs: fix typos/grammar in PR#1945 changelog

lua/telescope/from_entry.lua
#2030 broke `ls` preview for directories.
`vim.fn.filereadable` returns `0` for folders. Thus, when `validate` is `true` like for our buffer previewers, `nil` rather than directory paths are returned.
**Before**
Open `telescope-file-browser.nvim` and see no preview for directories
**After**
See buffer preview for directories
irrelevant
=> fix(from_entry): treat directories as valid paths

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/__files.lua, lua/telescope/builtin/__lsp.lua
CC @clason 
```lua
telescope.setup {
-- defaults = { },
pickers = {
live_grep = {
mappings = {
i = { ["<c-f>"] = actions.to_fuzzy_refine },
},
},
},
-- extensions = { },
}
```
=> chore: make to fuzzy refine easily configurable

lua/telescope/make_entry.lua
Fixes #2037  
Following the steps from the issue report with and without this fix.
- I've tested with the following commands: `quickfix`, `lsp_implementations` and `lsp_references`.
NVIM v0.7.2
macOS: 12.4
=> fix: `entry_display.create` expects items to be a table not a number

doc/telescope.txt, lua/telescope/builtin/__files.lua, lua/telescope/builtin/init.lua
Allows fuzzy finding over all open buffers. Same as `grep_open_files` for `live_grep`
Fixes #1357
=> feat: grep_open_files for builtin.grep_string

lua/telescope/utils.lua
Fixes #2042 
I have tested with all documented allowed values for **path_display**:
- `{"hidden"}, {hidden = 1}, "hidden"`: hides all the path (empty).
- `{"tail"}, {tail = 1}`: only the filename.
- `{"absolute"}, {absolute = 1}`: shows the absolute path.
- `{"shorten"}, {shorten = 2}`: shows only the defined number of chars of every dir on the path.
- Invalid values tested (3, "invalid_string", true): fallsback to the default value "absolute" with a warning log that `'path_display' must be either a function or a table`. …
=> fix(path_display): allow function on path_display 

lua/telescope/actions/generate.lua
=> fix: push history on refine

lua/telescope/actions/utils.lua
Change `action_utils.get_registered_mappings` to only capture mappings attached to prompt via `telescope` interfaces, as the interface would break otherwise currently anyway (and it's unclear whether other mappings should be showing up.. because then you'd attach them via telescope). 
Fixes #2087 
- Having installed `nvim-surround` (and reproduce with original issue)
- Observing no errors
See above
=> fix(which_key): only get telescope mappings

lua/telescope/actions/init.lua
Fixes typo in which_key options actions/init.lua , was 
```lua
{ width = opts.mode_with },
```
now is
```lua
{ width = opts.mode_width },
```
Ran locally, ran make test.
=> fix: whichkey mode width options typo

lua/telescope/builtin/__internal.lua
=> fix: `Telescope` command lsp_definition call (and potentially more)

lua/telescope/builtin/__lsp.lua
This pr fixes a bug that lead to an error because we tried to
concatenate a table (`err`) to a string. Now we concatenate
`err.message` (a string) to the string.
Fixes #2098 
Due to the simplicity of the change I only did a manual test.
```
NVIM v0.8.0-dev-699-gcbfae548e8
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter …
```
=> Fix error due to concatenating table to string

lua/telescope/config/resolve.lua
We did not check `val ~= nil` in the resolve functions, so config like `{ nil, max = 30 }` will throw a nil error. Also, if the config is `{
padding = _ }`, the logic relies on the function handling the padding is iterated before the one handling min/max in the map, which is not always guaranteed.
Fix the bug by adding nil check in the function handling min/max. Close
Fixes #2091
=> fix(resolve): Check val not nil in resolve funcs

lua/telescope/previewers/buffer_previewer.lua
Recent regression of path validation affects terminal buffer preview as terminal buffers always return invalid paths.
Reddit issue @siduck
Create terminal buffer and open `:Telescope buffers`. It now shows up again.
Irrelevant
=> fix(buffer_previewer): terminal path validation

lua/telescope/previewers/buffer_previewer.lua
Fix regression from #2117 and 
#2118 
Launch `builtin.live_grep`
=> fix(previewer): regression on live_grep

lua/telescope/from_entry.lua
path needs to be expanded for filereadable and isdirectory
fix #2077
Edit: this might be a bad fix with the get_buffer_by_name in mind. Because get_buffer_by_name doesn't validate (i think) and normal does, causing a problem that the result might be difficult and we get a cache miss.
=> fix: previewer if cwd is not curr dir

lua/telescope/builtin/__files.lua
```find_files``` currently returns syntax color characters appended to file names, breaking ability within telescope to open a file from find_files and breaking syntax highlighting in find_files
Fixes #2128
``` lua require("telescope.builtin").find_files { find_command = { "rg", "--color=never", "--files" }, }``` which does not include the extra characters. 
* Neovim version (nvim --version): 
NVIM v0.8.0-dev
macOS 12.5
=> Fix to find_files to force color=never

doc/telescope.txt, lua/telescope/mappings.lua
Change arguments in the table to set mapping.
#2111 
Running configuration with mapping:
```
["<esc>"] = { actions.close, type = "action", opts = { silent = true, nowait = true } }, 
```
Fine.
Running configuration with mapping:
```
["<esc>"] = { action = actions.close, opts = { silent = true, nowait = true } }
```
Error.
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins() …
```
=> docs: change arguments in keymap table (#2111)

lua/telescope/finders.lua, lua/telescope/finders/async_job_finder.lua, lua/telescope/finders/async_oneshot_finder.lua, lua/telescope/finders/async_static_finder.lua
Not setting entry_maker explicitly should fallback gracefully, Currently, it doesn't work, because
it's being set to make_entry.gen_from_string and make_entry.gen_from_string is entry_maker factory.
Ran a script:
```lua
pickers.new(opts, {
finder = finders.new_dynamic({fn=function(_)
return {"a","b","c"}
end}):find()
```
* Neovim version 0.7.2
* Operating system and version: Ubuntu 20.04
=> default entry_maker not set properly

lua/telescope/actions/set.lua
Adds vim's `drop` command for opening buffers:
> :dr[op] [[++opt]](https://vimhelp.org/editing.txt.html#%5B%2B%2Bopt%5D) [[+cmd]](https://vimhelp.org/editing.txt.html#%5B%2Bcmd%5D) [{file}](https://vimhelp.org/editing.txt.html#%7Bfile%7D) ..
Edit the first [{file}](https://vimhelp.org/editing.txt.html#%7Bfile%7D) in [a](https://vimhelp.org/insert.txt.html#a) window.
[-](https://vimhelp.org/motion.txt.html#-) If the file [is](https://vimhelp.org/motion.txt.html#is) [a](https://vimhelp.org/insert.txt.html#a)lready open in a [window](https://vimhelp.org/windows.txt.html#window) change to that
window.
[-](https://vimhelp.org/motion.txt.html#-) If the file [is](https://vimhelp.org/motion.txt.html#is) not open in [a](https://vimhelp.org/insert.txt.html#a) …
=> Add drop command for buffers

lua/telescope/pickers.lua, lua/telescope/pickers/highlights.lua, lua/tests/automated/pickers/find_files_spec.lua
Pulled out as a subset of the changes from #1491
This PR uses extmarks and virtual text instead of typical highlighting and text replacement to consolidate the highlight/rendering logic to `highlights.lua`. This should give us more flexibility in the future when we want to improve rendering of telescope.
- Internal Changes
* Neovim version (nvim --version): NVIM v0.7.2
* Operating system and version: macOS 12.3.1
=> Use extmarks for highlighting and carets

lua/telescope/pickers.lua, lua/telescope/pickers/highlights.lua, lua/tests/automated/pickers/find_files_spec.lua
Reverts nvim-telescope/telescope.nvim#2099
Intermittent "fix" for #2137 as highlighting worked just fine before and there are a few nitty gritty issues with the commit. As neither Conni nor me are sufficiently available right now, we can make our lives easier and restore user experience by just reverting this commit until there's more time.
That said, in my brief subjective tests, I actually think it might also have been faster before? Not sure, but too tedious to benchmark.
=> Revert "Use extmarks for highlighting and carets"

lua/telescope/pickers.lua
Resize telescope picker everytime screen is resized. Currently it set adds once in autocmd opts it triggers only one time
=> fix: pickers: Redraw telescope picker always when screen is resized

lua/telescope/sorters.lua
`sorters.fuzzy_with_index_bias` was missing highlighter.
^ I guess it's one of the above? 🤷🏼‍♂️
=> feat(sorters): add highlighter to fuzzy_with_index_bias

lua/telescope/config.lua
Removing an "if" that is is checking a condition previously tested by the assert().
Not really tested. Only started the plugin.
* Neovim version (nvim --version): NVIM v0.8.0-dev-701-g2a9c9371b 
* Operating system and version: Windows/WSL-Ubuntu 20.04
- [x ] I have performed a self-review of my own code
=> fix: remove un-needed check

lua/telescope/builtin/__files.lua, lua/telescope/builtin/init.lua
https://github.com/neovim/neovim/pull/19931 removed `_get_hl_from_capture(id)` since captures are now implicitly mapped to highlight groups with the same name.
Fixes #2149
(PSA: "Neovim master" always means "latest HEAD" -- this will intentionally break on older nightlies.)
=> fix(preview): update buffer previewer to upstream changes

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/set.lua, lua/telescope/actions/state.lua
This PR adds support for the `tab` modifier of `drop` to open a file in a new tab if it is not currently open in an existing window. Existing functionality did not support the `tab` modifier, so this would always replace the existing window, which was not what was desired for me.
=> feat: added support for tabdrop

README.md, doc/telescope.txt, lua/telescope/builtin/init.lua
- Updating the documentation for `git_files` to match the work done in [PR#842](https://github.com/nvim-telescope/telescope.nvim/pull/842/files).
- Updating the documentation for `live_grep` to match the pattern of the other pickers.
Just searched code base for any documentation that was out of data for `git_files`
=> Update documentation for git_files and live_grep

lua/telescope/builtin/__lsp.lua
Does what it says on the tin really. The current line was being included in the `lsp_references` output, even though `current_line` was `false`. Setting `current_line` to `true` removes the current line.
Bug fix (non-breaking change which fixes an issue)
Ran both `Telescope lsp_references current_line=false` and `Telescope lsp_references current_line=false` and verified that the current line was included / excluded correctly.
* Neovim version (nvim --version): 0.8.0-dev
* Operating system and version: Ubuntu 18.04.6 LTS x86_64
- [✅] My code follows the style guidelines of this project (stylua)
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have made corresponding changes to the …
=> fix(lsp): don't include current line in lsp_references if current_line=false

lua/telescope/actions/set.lua
This avoids an error when scrolling the preview window but the window is not visible (e.g. due to a screen resize).
Manually: 
- `:Telescope help_tags` (preview window is shown)
- make the Neovim window smaller so the preview window disappears
- press `<C-d>` to scroll the preview window
Observe no more error. Before this fix, the following error was shown:
```
E5108: Error executing lua ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:195: Expected Lua number     stack traceback:                                                                                                    
[C]: in function 'nvim_win_get_height' …
```
=> fix: check for window before scrolling previewer

lua/telescope/actions/init.lua
When perform action `git checkout`, run `checktime` for current buffer to get the new content.
=> fix: checktime when git checkout

lua/telescope/builtin/__internal.lua, lua/telescope/make_entry.lua
Now using `:Telescope registers` will sort with register content.
Default `:Telescope registers` does weird stuff like sorting with register names. Change the ordinal to sort on the basis of content of the registers.
This will be much better than the default behaviour I think.
Fixes #(996)
https://github.com/nvim-telescope/telescope.nvim/issues/996
😅. I ran it a few times.
- Neovim version (v0.8.0-dev-1132-g37a71d1f2):
- Operating system and version: manjaro
=> fix: builtin register picker better sorting

README.md
Adding some Lua-only key mapping examples taking advantage of NeoVim 0.7 features
=> docs: Add Lua-only key mappings examples

lua/telescope/builtin/__git.lua
Fixes #2180
* Neovim version (nvim --version): NVIM v0.8.0-dev-1200-gf9228577e
* Operating system and version: Linux Manjaro 22
=> feat(git): notify when not in a git repo instead of error

lua/telescope/make_entry.lua
Currently sorting in builtin register picker will sort with the content of the registers only. But searching over registers names is also useful.
Now it will sort over register names and register content
* Neovim version (nvim --version) NVIM v0.8.0-dev-1132-g37a71d1f2
* Operating system and version: manjaro
=> Search with register name and content in builtin register picker.

lua/telescope/config.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua
=> fix: preview = true

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/utils.lua, plugin/telescope.lua
The background color is off on selected text
- Bug fix 
Locally
* Neovim version (nvim --version): `NVIM v0.9.0-dev-16-g56998feeb`
* Operating system and version: Arch Linux
=> fix: selected icon highlight with color_devicons to false

lua/telescope/builtin/__files.lua
replace `table.insert` with direct indexing for performance gainz
Performance
still works :)
=> perf(builtin): faster list extend for find_files

README.md
Adding \<leader\> to key mapping examples
=> docs: Add <leader> to Lua-only key mappings examples

doc/telescope.txt, lua/telescope/builtin/__files.lua, lua/telescope/builtin/init.lua
Currently you need to wrap additional arguments for live grep (and grep string) in a function that returns a table. This PR allows using just a table too.
Minimal config:
```lua
require 'telescope'.setup {
defaults = {
vimgrep_arguments = { 'rg', '--column' }
}
}
```
Have hidden and non-hidden files in the current working directory. Open live grep with the options specified in the following tests. 
Search for a hidden file to test if telescope used the specified options for grepping.
```lua
require 'telescope.builtin'.live_grep {
additional_args = function(opts) return { '--hidden' } end
}
```
```lua
require 'telescope.builtin'.live_grep {
additional_args = { '--hidden' }
}
```
Test …
=> Allow table as additional args in live grep and grep string

doc/telescope.txt, lua/telescope/builtin/__git.lua, lua/telescope/builtin/__internal.lua, lua/telescope/mappings.lua
like vim.keymap.set
Example:
```lua
attach_mappings = function(prompt_bufnr, map)
map({ 'i', 'n' }, '<C-r>', function() end)
end
```
and refactor: merge map("i") and map("n") into map({"i", "n"}) in telescope/builtin
NVIM v0.8.0
MacOS 12.2 (Apple M1 Pro)
=> feat: the parameter "map" of attach_mappings can be list of modes to create mapping on multiple modes

doc/telescope.txt, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua
Add `jump_type` option to `lsp_references`, since it already exists for other lsp pickers, like `lsp_definitions`.
But the main reason is it was annoying when I know there is only 1 reference, use `lsp_references` and I still get the picker opened instead of immediately jumping to the only reference.
Fixes #2189 (probably)
(for all tests `lsp_references = require 'telescope.builtin'.lsp_references`)
```py
def foo(): # cursor is here, `lsp_references {}` jumps to the only result
foo() …
```
=> Add jump_type option for lsp_references

lua/telescope/builtin/__lsp.lua
When using `telescope.lsp_references` and there are only 2 references (the one where the cursor is on, and another one), telescope will try to jump to the other location without showing a picker. But if the reference is in another file, it will just put the cursor in the correct row/column, but it will stay in the same buffer/file.
I called `telescope.lsp_reference` on a symbol that has 2 references, the one where the cursor is, and one in a different file. After this change, it jumps to the other file, before the change, it did not.
* Neovim version (nvim --version): NVIM v0.9.0-dev-5e1687e-dirty
* Operating system and version: Archlinux
=> Fixes not changing files when request only returns 1 result

doc/telescope.txt, lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua
I've recently start using command history. For sometime I was a bit annoyed of unrelevant commands
like edit/write and others (most likely only used once)
I've considered using lua patterns, however, logical `or` isn't a thing. Additionally, passing a list of lua patterns and checking each pattern for each command history entry felt tedious.
This PR introduce a new optional function to filter command history items.
For example, in my configurations
~~~lua
local command_history_ignore = vim.regex "edit\\|Move\\|write\\|Write\\|e\\s\\|lua\\sI("
overrides.command_history = minimal {
prompt_prefix = "CMDHistory> ",
filter_fn = function(item)
if #item < 3 then
return false
else
return not command_history_ignore:match_str(item)
end
end,
}
~~~
- New feature (non-breaking change which adds …
=> feat(picker): command history filter

lua/telescope/builtin/__git.lua
This pull request sorts the git branches picker by authordate. It is in a draft state however, since the sorting gets lost on input and I feel this is not the "telescope-way" of handling sorting. I feel i should probably annotate some sort of info to the data that gets picked and sort the picker itself based on this, rater than sorting via git's `--sort` flag.
I've used it locally for some weeks.
nvim version:
NVIM v0.9.0-dev-1536+gfa7e1e260-dirty                                                                                                                                                        …
=> Draft: Sort branches by authordate

README.md, lua/telescope/builtin/__internal.lua
Add new action "open the qflist" for the quickfixhistory().
I want to open the quickfix within the quick fix window directly from quickfixhistory().
Fixes #2248
* Neovim version (nvim --version): `NVIM v0.9.0-dev-9d7dc50`
* Operating system and version: `Linux 5.15.74.2-microsoft-standard-WSL2 #1 SMP Wed Nov 2 19:50:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
=> Add new action to open quickfix window from quickfixhistory

lua/telescope/utils.lua
Updates code used to get icons from `nvim-web-devicons` to pass the filename as well as extension.
Set up `nvim-web-devicons` with configuration:
```lua
require('nvim-web-devicons').setup({
override = {
['js'] = {
icon = '',
color = '#efd81d',
cterm_color = '220',
name = 'Js',
},
['test.js'] = {
icon = 'ﭧ',
color = '#ffca28',
cterm_color = '220',
name = 'TestJavascript',
},
},
})
```
Then create a `*.js` and a `*.test.js` file, and open `:Telescope find_file`, and make sure the icons appear as configured.
* Operating …
=> support for multi-part file extensions like *.test.js

lua/telescope/make_entry.lua
Currently if you have at least one command with multiline description the preview for `telescope.builtin.commands()` is broken, ie display an _empty looking_ floating picker.
```
-- init.lua
vim.api.nvim_create_user_command('Kek', function() end, {
desc=[[
foo
bar
baz
]]
})
require('telescope.builtin').commands()
```
With this change the commands preview is displayed as expected
* Neovim version (nvim --version): 0.8.1
* Operating system and version: Macos
=> fix(builtin.commands): no preview for multiline description commands

.github/workflows/docgen.yml, lua/telescope/make_entry.lua
Pretty sure this is my first pull request which only added a single character 🤣 
Fixes #2226
@simonmandlik does this fix your issue?
- Both worked as expected
NVIM v0.9.0-dev-522+g174335923
Compiled by runneradmin@fv-az211-249
Windows 10
=> fix(builtin.live_grep): add spacer ":" even when coordinates disabled

lua/telescope/builtin/__files.lua
if rg option '-g=xxxx' contain 'v' or 'l', will misidentification 
Fixes #2240
=> fix: misidentification invert and files_with_matches (#2240)

lua/telescope/builtin/__internal.lua
jumplist entry text is currently 1 line after
```lua
local lnum = 3
print(vim.api.nvim_buf_get_lines(0, lnum, lnum + 1, false)[1])
-- this will give the text of line 4
print(vim.api.nvim_buf_get_lines(0, lnum - 1, lnum, false)[1])
-- this will give the text of line 3
```
* Neovim version (nvim --version): v0.8.1
* Operating system and version: Arch
=> fix: jumplist picker indexing the line after

doc/telescope.txt, lua/telescope/config.lua
A few places mention `action.foobar` which now are now in `action.layout.foobar`.
=> docs: point to correct lua modules

lua/telescope/builtin/__git.lua, lua/telescope/make_entry.lua
I'd like to see a graph view in git_commits picker, and notice the closed issue (#1041) when I try to find some solutions.
I'm not familiar with the Lua language, so, a little modifications are written to achieve the basic demand.
Feat # (#1041)
show the current branch graph when viewing git_commits
Invoking the git picker function **builtin.git_commits** by a vim key mapping, the the commits log with graph will displayed in the popup window.
_NB._ commit logs showing with graph will insert extra entries with no SHA value, so a error msg will shown in the vim msg bar if these extra entries selected.
=> feat(git): git_commits shows the current branch graph

doc/telescope.txt, lua/telescope/make_entry.lua, lua/telescope/pickers/entry_display.lua
Whilst browsing through the docs about `entry_makers` I noticed some grammar mistakes.
Docs update.
Opened and checked the docs.
=> docs: fix typos/wording

lua/telescope/make_entry.lua
Do not use nvim_buf_line_count on unloaded buffers, as the returned value is always 0
Fixes #2157
opening the buffer picker after restoring from a session now remembers last position
=> Fix #2157: do not use nvim_buf_line_count on unloaded buffers

README.md
As mentioned in issue  #2304 I added a note that the live_grep picker requires ripgrep.
=> Note that live_grep uses ripgrep in README

lua/telescope/builtin/__git.lua, lua/telescope/make_entry.lua
Fixes #2292. This uses `git status -z` instead of `git status --short` (see https://git-scm.com/docs/git-status/2.16.6#_porcelain_format_version_1) of which the output is easier to parse (e.g. filenames are not quoted). 
In a Git repo with some files (`ls` shows `'$hey.txt'  '\esc2.txt'  '\esc.txt'   nenen.txt  'normal_"\renamed.txt'  '"qt.txt'  'two words.lua'`), then running `:Telescope git_status`.
The info from Git seems to be parsed correctly now and the file is opened as expected when pressing enter.
The only things that's not working correctly yet is the previewer but that's a different issue (requiring updates to `from_entry.lua`).
* Neovim version (nvim --version): NVIM v0.9.0-dev-1729+g2d8bbe468     
* …
=> fix: correctly parse filenames with special chars in git_status

lua/telescope/builtin/__files.lua
=> fix: live_grep additional_args parsing

lua/telescope/builtin/__internal.lua
cwd_only would also include unrelated folders, provided the current folder name was a prefix
Example: current folder is /home/user/fold. Telescope would also offer files from /home/user/folder.
Create one folder named fold, another one named folder. Open and save fold/file1.txt and folder/file2.txt. Then run ":cd fold", and invoke `lua require'telescope.builtin'.oldfiles{cwd_only=true}`.
Without the fix, telescope will offer you both file1.txt and file2.txt. With the fix, telescope will offer you only file1.txt.
* Neovim version (nvim --version): NVIM v0.8.0-1210-gd3
* Operating system and version: fedora linux 37
PS: could it be possible to also backport this fix to the 0.1 stable branch?
=> fix(old_files): opts.cwd_only includes similarly named dirs

lua/telescope/builtin/__internal.lua
This is a backport of PR #2308 that was merged by @kkharji to the 0.1.x branch.
cwd_only would also include unrelated folders, provided the current folder name was a prefix
Example: current folder is /home/user/fold. Telescope would also offer files from /home/user/folder.
Create one folder named fold, another one named folder. Open and save fold/file1.txt and folder/file2.txt. Then run ":cd fold", and invoke `lua require'telescope.builtin'.oldfiles{cwd_only=true}`.
Without the fix, telescope will offer you both file1.txt and file2.txt. With the fix, telescope will offer you only file1.txt.
* Neovim version (nvim --version): NVIM v0.8.0-1210-gd3
* Operating system and version: fedora linux 37
PS: could it be possible …
=> fix: cwd_only would not filter enough [0.1.x]

.github/workflows/release.yml, Makefile, scripts/luarocks-upload.sh, scripts/test-luarocks-install.sh, telescope.nvim-scm-1.rockspec
`telescope.nvim` is a common dependency across Neovim plugins. Using luarocks may alleviate the need for users to specify their plugins' dependencies in their plugin manager.
(e.g., vim-plug or packer).
See also:
https://teto.github.io/posts/2021-09-17-neovim-plugin-luarocks.html
```console
luarocks install ./telescope.nvim-scm-1.rockspec --local
```
=> feat: add rockspec + luarocks upload workflow

doc/telescope.txt, lua/telescope/builtin/__git.lua, lua/telescope/builtin/init.lua
Add a new option `show_remote_tracking_branches` to the `git_branches` picker so that the user can hide remote tracking branches like `origin/main` if they only care about local branches. Defaults to true which is the current behaviour.
=> feat(pickers): add opt.show_remote_tracking_branches to git_branches

lua/telescope/builtin/__internal.lua
Fixes  an issue of getting empty results with oldfiles with cwd_only option ON inside Windows OS.
Now it is using `utils.get_separator()` instead of a static string `"/"`.
* Neovim version (nvim --version): v0.9.0-dev
* Operating system and version: Windows 10
- [ x] My code follows the style guidelines of this project (stylua)
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation (lua annotations)
=> fix: use path separator from builtin utils in cwd_only

lua/telescope/actions/set.lua
Fixes an issue with the `drop` command in telescope where filenames with spaces or other special characters are not open properly.
- Ran on local using filenames with spaces
* Neovim version (nvim --version): 0.8.2
* Operating system and version: Windows 11
=> fix: escape filename used in drop commands

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/utils.lua, lua/telescope/builtin/init.lua, lua/telescope/config.lua, lua/telescope/init.lua, lua/telescope/make_entry.lua, lua/telescope/mappings.lua, lua/telescope/pickers/entry_display.lua, lua/telescope/pickers/layout_strategies.lua, lua/telescope/previewers/init.lua, lua/telescope/themes.lua, lua/telescope/utils.lua
Proof-read edits of the help docs. Mostly related to spelling/grammar errors, minor formatting clean ups and other nitpicks.
Read through of the docs - still wip
* Neovim version (nvim --version): NVIM v0.9.0-dev-590+g6ba34e21f
* Operating system and version: Linux archlinux 6.1.2-arch1-1
=> docs: proof-read edits

doc/telescope.txt, lua/telescope/actions/history.lua, lua/telescope/previewers/init.lua
Correct grammar and spelling errors in documentation to improve readability.
Install telescope.nvim plugin using my fork and branch to verify my changes do not break formatting.
* Neovim version (nvim --version): NVIM v0.8.2
* Operating system and version: Darwin 22.2.0 arm64
=> docs: telescope.txt spelling and grammar fixes

lua/telescope/builtin/__internal.lua
In macOS 13 (Ventura), `:Telescope man_pages` shows no results. This is caused by a difference in behavior between the [previous implementation of `apropos(1)`][man-30] up to [macOS 12.5][macos12.5] and the new [`man` package][man-44] used in [macOS 13][macos13], which [comes from FreeBSD][freebsd].
[macos12.5]:https://github.com/apple-oss-distributions/distribution-macOS/tree/macos-125
[macos13]: https://github.com/apple-oss-distributions/distribution-macOS/tree/macos-130
[man-30]:https://github.com/apple-oss-distributions/man/tree/man-30
[man-44]: https://github.com/apple-oss-distributions/man/tree/man-44
[freebsd]: https://github.com/apple-oss-distributions/man/blob/bc98aec579feecce753f2da60345f388f1130aff/.upstream_base_commits
This new `apropos(1)` is implemented as a shell script …
=> fix: man_pages on macOS 13 and FreeBSD #2326

doc/telescope.txt, lua/telescope/actions/history.lua, lua/telescope/config.lua
As noted in the linked issue, cycling the prompt history doesn't wrap around — picking prev on reaching the start of history content, or next on reaching the end, prevents any history from showing up. A common alternative is to wrap back to the start of history, or back to the end of history (depending on direction). This pull request adds that functionality, controlled by a new config option to allow users to decide whether they want this wrapping or not.
Fixes https://github.com/nvim-telescope/telescope.nvim/issues/2301
Installed my own branch in place of `nvim-telescope/telescope.nvim`, and then tested the following cases:
- Standard existing history file with many entries
- …
=> feat: Added support for wrapping history on reaching history begin or end

lua/telescope/previewers/utils.lua
When scrolling through files or typing continuously on a search window, the regex highlighter has a chance to produce this error:
The affected function is rewritten by wrapping `nvim_buf_set_option` in a protected call, and returning whether that call succeeded as a boolean value.
- Open a new `[S]earch [F]iles` window, and type or scroll.
```
NVIM v0.8.2
Compiled by runneradmin@fv-az28-353
Features: -acl +iconv +tui
See ":help feature-compile"
system vimrc file: "$VIM\sysinit.vim"
fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
* Operating system and version: Windows 10 Pro 21H2
=> fix: util regex highlighter producing error when scrolling too fast

.github/workflows/ci.yml, README.md
kyazdani42/nvim-web-devicons has been moved to nvim-tree/nvim-web-devicons.
=> fix: kyazdani42/nvim-web-devicons is now nvim-tree/nvim-web-devicons

lua/telescope/mappings.lua, lua/telescope/pickers.lua
I tried to use the `User TelescopeFindPre` event listed on the [README](https://github.com/nvim-telescope/telescope.nvim#autocmds), but the autocmd was never executed. This PR fixes that.
Autocmds are currently executed like this:
```lua
vim.api.nvim_exec_autocmds("User TelescopeKeymap", {})
```
And to my knowledge the pattern needs to be passed as an option:
```lua
vim.api.nvim_exec_autocmds("User", { pattern = "TelescopeKeymap" })
```
<br>
<br>
1. Add a autocmd:  
`autocmd User TelescopeFindPre echo "-> TelescopeFindPre!"`
2. Open telescope
It should print "-> TelescopeFindPre!".
<br>
* Neovim version: `v0.9.0-dev-912+gfe1e6b82f`
* Operating system and version: macOS 13.1 …
=> fix: execute autocmds correctly

lua/telescope/make_entry.lua
fix: https://github.com/nvim-treesitter/nvim-treesitter/pull/4300
I confirmed that the following command did not show any error message.
`lua require'telescope.builtin'.treesitter()`
* Neovim version (nvim --version): v0.9.0-dev-935+g3a5dddf24
* Operating system and version: Arch Linux
=> fix: rename ts_utils.get_node_range -> vim.treesitter.get_node_range

lua/telescope/builtin/__git.lua
With this PR, `git_staging_toggle:post` will ...
- never `reset_prompt`
- keep selection row as much as possible
- unless selection is removed from the filtered list and
- the selection is formely on the top row when `sorting_strategy == "decending"`
- the selection is formely on the bottom row when `sorting_strategy == "ascending"`
Sometimes, (un-)staging changes the order of filtered items.
In such cases, maybe it would be better to update selection row to track the new position of (un-)staged file.
However, I decided not to do it because
- implementation can be complex
- unexpected changes of selection row may distrub users from continuing to the next actions that users had in their mind
Although I think this is a great change, it is a breaking change at the same time.
If it is not …
=> Let git_status keep selection row and prompt on git_staging_toggle action

lua/telescope/make_entry.lua
When open registers picker,  the expression in `"=` register is evaluated, which might lead to error.
Now specify second arg to `getreg` to get the expression (instead of "evaluated" result) for entry content, like what `:registers` command displays.
This has behavior change, if user still want to see/paste the evaluated result of `"=`, customization will be needed.
However the picker doesn't have detail doc/definition about the behavior, so I guess the break is minor.
Fixes #2228
* Neovim version (nvim --version): v0.8.2
* Operating system and version: Windows 10
=> Avoid eval "= directly in builtin registers picker

doc/telescope.txt, lua/telescope/builtin/init.lua
Add missing documentation for symbol_width and symbol_type_width on lsp_document_symbols and lsp_workspace_symbols.
Documentation for symbol_width and symbol_type_width was missing for telescope.builtin.lsp_document_symbols and telescope.builtin.lsp_workspace_symbols.
Documentation update.
Opening a draft pull request to check the updated documentation.
* Neovim version (nvim --version): NVIM v0.8.2
* Operating system and version: CentOS 7
=> Add missing documentation for builtin lsp symbols

lua/telescope/from_entry.lua
`vim.fn.expand` seems to be interpreting brackets (`[]`) as something special. Escape the filename before trying to expand.
Fixes #2233
Fixes #2315
Create files with brackets in the filename, e.g. `[2023-01-23] Test.md`, and try previewing it.
```
NVIM v0.8.2
Compiled by brew@Ventura
Features: +acl +iconv +tui
See ":help feature-compile"
fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.2/share/nvim"
```
* Operating system and version: macOS Ventura 13.1
=> fix: fix `reverse range in character class` error

doc/telescope.txt, lua/telescope/actions/init.lua
Extends the git_delete_branch action to delete all selected branches. It also keeps the picker open.
The default behavior of deleting the branch on which the cursor stands on still works.
* Neovim version (nvim --version): 0.8.2
* Operating system and version: OSX 12.6
Closes #2363
=> feat: extend git_delete_branch to delete of all selected branches

lua/telescope/pickers.lua
wrap_results option was breaking scroll position of results window when sorting strategy is descending. Because of that users are not able to see the most relevant result on the results window unless manually scrolled. This behavior is now fixed
Fixes  #1757 
```
NVIM v0.8.2
Compiled by brew@HMBRW-A-001-M1-005.local
Features: +acl +iconv +tui
See ":help feature-compile"
fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"
```
* Operating system and version: macos 12.6.2
=> fix: wrap_results option breaking scrolling of results window

.luacheckrc, doc/telescope.txt, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua
Apply `jump_type` rule only if the definition file is different from the current file. I think most people expect open the definition on a new tab (or a split pane) only when we need to go to another file.
Set a key mapping `vim.keymap.set('n', 'gd', function() builtin.lsp_definitions{jump_type = 'tab'} end, bufopts)`:
Set a key mapping `vim.keymap.set('n', 'gr', function() builtin.lsp_references{jump_type = 'tab'} end, bufopts)`:
* Neovim version (nvim --version): NVIM v0.8.2
* Operating system and version: Ubuntu 20.04 …
=> feat: apply jump_type only if the definition file is different from the current file

README.md, doc/telescope.txt, lua/telescope/builtin/__files.lua, lua/telescope/builtin/init.lua
Use the visual selection for live_grep when in visual mode
Bind in both normal and visual mode and manually test. Test normal mode. Then
in visual mode text that multiple words work and that word_match is disabled by
selecting only part of a word.
```lua
vim.keymap.set({'n', 'v'}, '<leader>tg', require('telescope.builtin').grep_string)
```
NVIM …
=> feat: support selection for grep_string

lua/telescope/pickers.lua
=> fix: prefix color highlighting on nvim 0.9

lua/telescope/pickers.lua
=> fix: make preview cycling and titles work correctly after `:Telescope resume`

lua/telescope/actions/set.lua
closes #2386
When using pickers to open buffers, fallback on window's last cursor position for that buffer.
This preserves the cursor location (row and col) for previously opened buffers.
This only impacts the column location for the `buffers` picker. But currently also impact the line number as well for `find_files`. This last point might be too disruptive even though I believe the change is for the better. I can modify the PR to revert this however.
#2386
- New feature (non-breaking change which adds functionality) _MOSTLY_
* open a buffer and move the cursor to somewhere not [1,1]
* open a new split `:vnew`
* …
=> feat: utilize last window cursor position

lua/telescope/previewers/buffer_previewer.lua
I use `git_status` quite often and by default, if changes are staged they are not displayed on the preview. If all changes are staged, the preview is simply blank.
Change an existing file and stage it, run `:Telescope git_status` and see the diff (blank before, with the file after).
=> Make git_status diff works with stagged files

README.md
Remove extra `{` which was included in the snippet merged on https://github.com/nvim-telescope/telescope.nvim/pull/2377
- This change is a documentation update
* Neovim version (nvim --version): v0.8.3
* Operating system and version: macOS Ventura 13.2
=> [DOCs] Remove extra `{` from Lazy.nvim package manager directions

lua/telescope/builtin/__files.lua, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua, lua/telescope/utils.lua
Add new options `symbols` and `ignore_symbols` to the treesitter picker so that the user can filter the results similarly to lsp_* pickers that already support these options.
* Neovim version (nvim --version): 0.8.2
* Operating system and version: MacOS Big Sur 11.15.2
Dear Telescope maintainers and community! This is my first PR to this amazing project. I hope for your kind and honest feedback :)
I didn't quite understand the process of generating the documentation from the annotations. I pushed my commit to a non-master branch on my fork, but github action failed due to lack of permissions for github-actions bot.
=> feat(treesitter): symbols & ignore symbols options

doc/telescope.txt, lua/telescope/make_entry.lua, lua/telescope/utils.lua
Fix the highlight group width for devicons for various pickers' entry display.
Currently, certain entry makers fail to compensate for the icon widths not equal to 3.
Closes #2445 
Effects pickers using `gen_from_file` and `gen_from_vimgrep` make entries.
- `find_files`
- `git_files`
- `oldfiles`
- `live_grep`
- `grep_string`
* Neovim version (nvim --version): `NVIM v0.9.0-dev-1305+g83bfd94d1`
* Operating system and version: `Linux archlinux 6.2.8-arch1-1`
=> fix: icon hl width for various pickers

lua/telescope/builtin/__files.lua
vim.treesitter.get_query is deprecated use vim.treesitter.query.get
- [x ] My code follows the style guidelines of this project (stylua)
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation (lua annotations)
=> fix: `vim.treesitter.get_query` deprecated

lua/telescope/actions/set.lua
Regression bug from #2416 where `grep_string` results without column numbers where not respecting the row number on `select_default` when using `grep_string` with the command `:Telescope grep_string search=<CR>`
Closes #2444 
* use `:Telescope grep_string search=<CR>` to grep for anything that's not that on the first line of the file
* `select_default` on some entry - the file should open on the correct line
* also verify regular `:Telescop grep_string<CR>` works as expected taking you to the correct row/col of the file
* open a buffer and move the cursor to somewhere not …
=> fix(action): grep_string select_default with nil column

doc/telescope.txt, lua/telescope/config.lua
ripgrep has an argument that returns results in vim format
```man
--vimgrep
Show results with every match on its own line, including line numbers and column numbers. With this option, a line with more than one match will be printed more than once.
```
which would replace `"--color=never", "--no-heading", "--with-filename", "--line-number", "--column"` and still produce the same result
* Neovim version (nvim …
=> Simplify vimgrep_arguments args

lua/telescope/from_entry.lua
Adds support for viewing File Previews of paths with dollar symbols.
Eg. `./($lang)._index.tsx`
This is a new pattern supported by [Remix optional segments](https://remix.run/docs/en/v1/file-conventions/route-files-v2#optional-segments) file based routing.
Partially fixes downstream issue https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/244.
This fix also applies to many of the builtin pickers.
1. Create a file `touch "(\$lang)._index.ts"`
2. In that created file, enter some text `console.log('hello');`
3. With and without the PR checked out, use …
=> fix(from_entry): escape paths with `$` symbol

lua/telescope/_.lua
Using the `async_oneshot_finder` with cwd paths like `($lang)/` (used in [Remix](https://remix.run/docs/en/1.15.0/file-conventions/route-files-v2#optional-segments)) will error out due to the `$` being expanded by `vim.fn.expand`.
Fixes downstream issue https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/244
Created a directory `mkdir "(\$foo)"` and `cd` into it. From with that directory:
* Neovim version (nvim --version): `NVIM v0.10.0-dev-19+g339011f59`
* Operating system and version: `Linux archlinux 6.2.10-arch1-1`
=> fix: escape cwd symbols for `async_oneshot_finder`

plugin/telescope.lua
if there is extension_list, then the builtin_list would be replaced/overriden. e.g. if there are 3 items in extension_list, then first 3 items in builtin_list would be replaced when you type `:Telescope fi` and press tab to get completion list.
root cause: builtin_list/extension_list is list-like table, not map-like table, so vim.tbl_extend will not work in this case. we want to merge two list together actually in the case.
1. make sure there is at least one telescope extension.
2. when you type `:Telescope xx` and …
=> fix: some builtin functions missing in completion list

lua/telescope/health.lua
This PR allows to remove the warnings regarding deprecated API `vim.health.report_*`.
By running the `checkhealth` command should give no more warning about this API deprecation.
* Neovim version (nvim --version): NVIM v0.10.0-dev-102+g85bc9e897
* Operating system and version: macOS 13.3.1
=> fix(health): remove deprecated api warnings in health check

lua/telescope/actions/init.lua
It is inconvenient that commands containing strings such as `<CR>` cannot be edited using `<C-e>`.
Execute a command containing `<CR>` (e.g. `nnoremap <CR> <CR>`) to add it to the history, select the command in `Telescope command_history`, and press `<C-e>`.
This PR makes correctly enter the four characters `<CR>` into the cmdline.
=> fix(actions): support commands with special chars

doc/telescope.txt, lua/telescope/config.lua
This reverts commit cfe6df6257aa7ee691fb56305923e9fec6c83c97.
It appears that the commit above is causing issues in certain instances when using grepping pickers.
The `--vimgrep` option seems to be the culprit.
[BurntSushi](https://github.com/BurntSushi/ripgrep/issues/2505#issuecomment-1536422272) doesn't really recommend using `--vimgrep`:
> --vimgrep is itself a strange thing, and is IMO legacy. It would probably be better if text editor plugins used ripgrep's --json flag to get structured matches. This is what VS Code does, for example.
Issue is reproducible live grepping in this repo/directory: https://github.com/swagger-api/swagger-ui/tree/master/dist
Fixes #2482
Please describe the …
=> Revert "chore: simplify vimgrep_arguments args (#2440)"

lua/telescope/pickers.lua
Just adds an if around what I believe to be the appropriate version to start doing that refresh.
Feel free to rewrite / ignore.
Fixes #2461
Just manually tested on my neovim version
* Neovim version (nvim --version): 7.2
* Operating system and version: Debian bookworm
=> Prefix color highlighting reset only on nvim 9.0

lua/telescope/previewers/buffer_previewer.lua
Fix JSON files without file extensions being treated as non-text files as its MIME type is `application\json`.
The [current implementation](https://github.com/nvim-telescope/telescope.nvim/blob/f2645c13205abb9ee3dbcee68416645c69b863c8/lua/telescope/previewers/buffer_previewer.lua#L195) splits the output of the `file` command and only uses the first item of the split output to check if file reviewable.
Also manually setting `opt.ft` to `json` for syntax highlighting as [`plenary.filetype.detect`](https://github.com/nvim-telescope/telescope.nvim/blob/f2645c13205abb9ee3dbcee68416645c69b863c8/lua/telescope/previewers/buffer_previewer.lua#L165) is unable to recognize JSON files without file extension
Issue #2221
Create a JSON file with no …
=> fix(preview): update mime-type check for json files (#2221)

lua/telescope/builtin/__internal.lua
This PR removes directories from the `oldfiles` picker results
Run `:Telescope oldfiles` - after this commit directories (opened via netrw) should be removed from the results.
=> Exclude directories (netrw) from the `oldfiles` picker

lua/telescope/pickers.lua
Reverts nvim-telescope/telescope.nvim#2492
=> Revert "Prefix color highlighting reset only on nvim 9.0"

lua/telescope/actions/set.lua
=> fix: opening file starting with a plus

doc/telescope.txt, lua/telescope/config.lua, lua/telescope/previewers/buffer_previewer.lua
Adds a new previewer option (`ls_short`) to allow for the file previewer for directories to not use `--long` flag for `ls`.
With default previewer options:
With `{ preview = { ls_short = true } }` option:
This is a repeated request for downstream [`telescope-file-browser`](https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/267)
* Neovim version (nvim --version): `NVIM v0.10.0-dev-19+g339011f59`
* Operating system and version: `Linux archlinux 6.2.12-arch1-1`
=> feat(file_previewer): add option for `ls --short`

.github/workflows/ci.yml, .github/workflows/lint.yml, README.md, doc/telescope.txt, doc/telescope_changelog.txt, lua/telescope/builtin/__files.lua, lua/telescope/config.lua, lua/telescope/health.lua, lua/telescope/previewers/utils.lua, lua/telescope/utils.lua, plugin/telescope.lua
Use upstream vim.treesitter features for treesitter highlighting instead of requiring nvim-treesitter.
Note: This bumps the minimum Neovim version to 0.9.0; if you still want to support 0.8.0, this needs one or two minor compatibility shims to account for renamed functions.
Fixes #2498
=> feat(ts)!: use upstream treesitter implementation

lua/telescope/builtin/__lsp.lua
This is a really minor change that fixes a little issue introduced in #2324: many LSPs use the field `targetUri` instead of `uri`, so now it's compatible with (almost?) every LSP.
(I'm omitting everything else because I  literally changed 2 lines of code)
=> fix(lsp_definitions): compare file uri with `targetUri`

lua/telescope/builtin/__internal.lua, plugin/telescope.lua
I noticed that neovim wasn't sorting the list of autocomplete items when pressing tab in the command line.
In my very limited lua + nvim knowledge, there doesn't seem to be a way to create an autocommand that intercepts the completion list in the command popup.
So I decided to try my hand at brute-forcing the solution from telescope's side.
Here I sort the list of available commands for each of the 4 possible code paths.
The initial builtin list is also unsorted.
Let me know if this is useful or if you have any other recommendations for sorting the options. It's also ok if this feature is not wanted. 👍
(I messed up and renamed the branch on the closed PR #2515 not knowing GH would close it. Sorry for the double submission) …
=> feat: Patch sorting popup autocomplete items and initial builtin items

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
Adds new options `disable_coordinates` to the `diagnostics` picker.
Closes #2475 
* `:Telescope diagnostics` - base case
* `:Telescope diagnostics disable_coordinates=true` - new option
* `:Telescope diagnostics no_sign=true` - test existing option
* `:Telescope diagnostics disable_coordinates=true no_sign=true` - test together with existing option
* Neovim version (nvim --version): `NVIM v0.10.0-dev-19+g339011f59`
* Operating system and version: `Linux …
=> feat(diagnotics): add `disable_coordinates` option

lua/telescope/actions/set.lua
Fix the problem I reported in <https://github.com/nvim-telescope/telescope.nvim/issues/1725#issuecomment-1502548033>. Supporting the abbreviations of the commands to specify the direction makes too many combinations, so I added only their unabbreviated names.
In addition, make the error message more detailed for users that passes unsupported command.
Fix the problem I reported in <https://github.com/nvim-telescope/telescope.nvim/issues/1725#issuecomment-1502548033>.
- Bug fix
1. Run nvim with several files (e.g. `nvim .gitignore .luacheckrc .stylua.toml` at the root of this project).
2. Run `:Telescope buffers`
3. Hit `<C-p>` to  select a buffer different from the current one.
4. Hit `<C-h>`.
1. Run nvim with several files (e.g. `nvim …
=> Open buffers in various directions

doc/telescope.txt, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua
Added new option value "reuse_win".
so we can choose to reuse the existing window or not when the builtin.lsp_definitions, builtin.lsp_type_definitions and builtin.lsp_implementations only return one result.
* Neovim version (nvim --version): NVIM v0.8.3
* Operating system and version: Darwin Kernel Version 22.3.0
=> add 'reuse_win' for reuse window in lsp definition options

lua/telescope/finders.lua, lua/telescope/finders/async_job_finder.lua, lua/telescope/finders/async_oneshot_finder.lua
https://github.com/nvim-telescope/telescope.nvim/commit/59497d664086c4c7aa24a15a1c3b9ccf718ce9c7 introduced `sorters.fuzzy_with_index_bias`, which gives a scoring boost to earlier entries.
However, this sorter relies on an `index` key existing for the entry, which is only populated by the static finder currently. We should set it from the other finders, too.
This will allow us to use said sorter everywhere. It will also let us replicate the behaviour of `fzf --tiebreak=index`:
```
return pickers.new(opts, {
finder = finders.new_oneshot_job(...)
sorter = telescope.extensions.fzf.native_fzf_sorter(),
tiebreak = function(current_entry, existing_entry, _)
return current_entry.index < existing_entry.index
end
}):find()
```
This gives me better results for my "recently opened files" picker. …
=> Always add index to entry

doc/telescope.txt, lua/telescope/builtin/__git.lua, lua/telescope/builtin/init.lua
This commit adds a new param for git_* builtin pickers to find the git root *from* the current file. The root is found as the first parent repo of the current buffer.
It is useful when working on a project containing multiple git repos like 
```
src/   <-- neovim cwd
repo1/
.git/
file1
repo2/
.git/
file2
```
Calling `Telescope git_commits` on file1 buffer will open all commits of the first repo. 
This feature is inspired by the way [fugitive](https://github.com/tpope/vim-fugitive) looks for the git root 
Set your cwd to a directory containing multiple git repos. Open any file. Call a git picker with the `use_file_path` flag set to `true` in Telescope, the repo of the current file is …
=> Find git root from current buffer

README.md, lua/telescope/pickers.lua
I'm working on an extension which performs some actions after the picker is fully resumed. By "fully resumed" I mean that finder has shown the results. I didn't find the way to do it in the current codebase. Therefore I'm proposing to add a new user automcd called `TelescopeResumePost` which is triggered when resume action is fully completed. I named the autocmd by analogy with `TelescopeFindPre` which already exists in the codebase.
Fixes #2439
1. Launch any picker
2. Close the picker
3. Run
```lua
require('telescope.builtin').resume()
local prompt_bufnr = vim.api.nvim_get_current_buf()
vim.api.nvim_create_autocmd('User TelescopeResumePost', {
buffer = prompt_bufnr,
once = true,
callback = function()
print('User …
```
=> feat: add user autocmd TelescopeResumePost

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua
Previewers and some entry_makers currently has poor support for non UTF8 encoded files.
This PR looks to add a new option `file_encoding` to pickers with for previewers `file_previewer` & `grep_previewer`, `qflist_previewer`.
This new option is consumed by `buffer_previewer.file_maker` to do some string processing with `vim.iconv`. A similar thing also happens in `make_entry.gen_from_vimgrep`.
Fixes #2415 
This change impacts the following pickers:
`live_grep`
`grep_string`
`find_files`
`git_files`
`treesitter` …
=> fix: previewers & entry maker file encoding

README.md, lua/telescope/previewers/buffer_previewer.lua
This allows a user to use the buffer name and/or filetype to change settings in the previewer to change some aspect of the previewers behaviour. In this case deciding whether or not to show numbers in the previewer
This change converts the autocommand run when Telescope loads a preview in the `buffer_previewer` to also pass along extra information about the file e.g. the `bufname` or it's (plenary-detected) filetype.
The main motivation for this is that a user can do something like
```lua
vim.api.nvim_create_autocmd({
event = 'User',
pattern = 'TelescopePreviewerLoaded',
callback = function(args)
if args.data.filetype ~= "help" then
vim.opt_local.number = true
end
end,
})
```
- This change requires a …
=> feat(buffer_previewer): pass file details in TelescopePreviewLoaded autocmd

doc/telescope.txt, lua/telescope/config/resolve.lua
fixes #2508
this is technically a breaking change but i doubt anyone uses height/width 1 (absolute value). It makes more sense to treat 1 as 100%
=> feat!: allow full height, width by resolving 1 as a percentage rather than absolute val

lua/telescope/actions/init.lua, lua/telescope/pickers.lua
In some conditions such as when calling `man_pages` or `help_tags` the cursor
position in the original window is wrongly restored. This bug was introduced by
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 and seems to be caused by some weird
"race condition".
Fixes #2319
- Before introducing this change `man_pages` and `help_tags` move the cursor to
the right when you hit Enter. With this change this doesn't happen. The commit
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 that introduced this bug tried to fix
the fact that when you leave Telesope with <C-c> from insert mode the cursor …
=> fix: correctly restore cursor position in original window

doc/telescope.txt, lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua
There was a todo for more flexible filtering in `builtin.keymaps` ( https://github.com/nvim-telescope/telescope.nvim/blob/7141515a7cabde46449675a403ed564416363887/lua/telescope/builtin/__internal.lua#L1127 ). I implemented this by adding another `filter` option accepting a keymap as its argument. 
I wanted to use this to only filter keymaps with a `desc`. While this could be a separate flag, I feel like this is cleaner. `lhs_filter` is now somewhat redundant.
Setup a keymap with a description, and select it:
```
vim.keymap.set("n", "abc", "<CR>", { desc = "do something" })
vim.keymap.set("n", "def", "<CR>", { desc = "do something else" })
vim.keymap.set("n", "xyz", function() …
```
=> implement filter for keymaps

lua/telescope/previewers/buffer_previewer.lua
This is fixing an issue introduced in [this commit](https://github.com/nvim-telescope/telescope.nvim/commit/80eefd8ff00145ef6ca4b7c64ef355b224f6e630).
A fresh install of `NvChad` fails with following error:
```
Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:428: Error executing lua: ...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:55: attempt to index l
ocal 'filename' (a nil value)
...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:55: in function '_get_extension_parts'
...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:103: in function 'detect_from_extension'
...al/share/nvim/lazy/plenary.nvim/lua/plenary/filetype.lua:168: in function 'detect' …
```
=> Prevent pfiletype from failing when bufname is nil

lua/telescope/actions/init.lua
Upon making entry for git_bcommits picker, current file path is saved to `current_file` field of entry:
https://github.com/nvim-telescope/telescope.nvim/blob/6d3fbffe426794296a77bb0b37b6ae0f4f14f807/lua/telescope/make_entry.lua#L446
... but `git_checkout_current_buffer` action does attempt to read current file from wrong field of selected entry -- `file`:
https://github.com/nvim-telescope/telescope.nvim/blob/6d3fbffe426794296a77bb0b37b6ae0f4f14f807/lua/telescope/actions/init.lua#L783
No specific configuration needed to reproduce this issue. Just:
1. Open git tracked file in Neovim
2. Execute `:Telescope git_bcommits`
3. Pick any previous commit for current buffer
4. Notice that there is now …
=> fix(bcommits): wrong entry field is used

lua/telescope/mappings.lua
fix #2431
it only contains the fix for 2431, it does not completely refactor mappings. plan to do that in a separate branch. I also cant recall when `vim.keymap` was introduced and if it would break 0.7 support (we still have on 0.1.x). need to figure this out before merging ^^
=> fix: expr for insert mode

lua/telescope/builtin/__internal.lua
The builtin.registers picker had two copies of the black hole register ( "_ ) and didn't show the small delete register ( "- ) at all. I added the small delete register and since the black hole register never holds any information I removed that one. 
I used it to paste words from my small delete register.
* Neovim version (nvim --version): 0.9.1
* Operating system and version: EndeavourOS
=> fix registers: add small delete remove black hole

lua/telescope/actions/init.lua, lua/telescope/builtin/__internal.lua
Fixes https://github.com/nvim-telescope/telescope.nvim/issues/2142
Aligns the behavior with `vim.diagnostic.setqflist`. Vim's default behavior with `:copen` is kinda buggy. It opens the window below the last window in the layout (i.e. at the bottom right corner). Created an issue about that https://github.com/vim/vim/issues/12501.
=> fix: use `:botright` modifier for quickfix window open

README.md, doc/telescope.txt, doc/telescope_changelog.txt, lua/telescope/config.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua
CC @clason 
this would drop usage of `plenary.filetype`
still left todo
seems like vim.filetype match doesnt have support for modeline so we still do that manually
`:lua print(vim.filetype.match({ contents = { " vim:tw=78:ts=8:ft=help:norl:" } }))`
=> feat!(previewer): replace plenary.filetype with vim.filetype.match

lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua
ref: https://github.com/nvim-telescope/telescope.nvim/issues/2552 
removes usage of context_manager
=> refactor(previewer): remove with_preview_window

lua/telescope/previewers/utils.lua
In a previous commit the way telescope's previewer detected the filetype relied on plenary's filetype detection. Recently it appears this has been changed to a util function within telescope. Plenary's filetype detection always casted its input to a string before matching with `vim.filetype.match` but this new util function does not.
This caused a problem with octo's previewer where the `get_buffer_by_name` function returns an integer representing the Issue/PR number. Seeing as how the previous filetype detection function always casted to a string before matching, I believe its a telescope issue rather than a octo.nvim issue 🤔 
Closes #2564 
```
NVIM v0.9.1
```
=> fix(previewer): Cast filepath to string before matching for filetype

lua/telescope/builtin/__files.lua, lua/telescope/make_entry.lua
Fixes not being able to query/use patterns that were non-UTF8 by passing the existing `opts.file_encoding` option to ripgrep as `--encoding`.
=> fix(live_grep/grep_string): support non-utf8 patterns

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/actions/set.lua, lua/telescope/mappings.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua, lua/telescope/previewers/previewer.lua
This implements horizontal scrolling, e.g. to the left and the right, in both the previewer window, mapped to \<C-f> and \<C-k> by default, resp., and the results window, mapped to \<M-f> and \<M-k> by default.
Open ``Telescope live_grep`` or ``Telescope find_files``, etc., input query, scroll to the left or to the right in the previewer or the results window with the above key mappings.
* Neovim version (nvim --version): NVIM v0.7.2, Build type: Release, LuaJIT 2.1.0-beta3
* Operating system and version: Ubuntu 22.10 (kinetic)
=> Implements horizontal scrolling in previewer & results.

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/init.lua
The doc states that `lsp_dynamic_workspace_symbols` supports prefiltering using `<C-l>` mapping, but it doesn't.
This PR adds support for prefiltering after refining to fuzzy search.
Fixes #2089.
1. Execute command `:Telescope lsp_dynamic_workspace_symbols`.
2. Type something to start fetching symbols.
3. Press `<C-space>` to refine to fuzzy search.
4. Press `<C-l>` to do prefiltering:
* Neovim version (nvim --version): `NVIM v0.10.0-dev-551+ge27377e33`
* Operating system and version: arch
=> fix(lsp_dynamic_workspace_symbols): add prefilter as per documentation (after to_fuzzy_refine)

lua/telescope/builtin/__files.lua, lua/telescope/make_entry.lua
This makes buitin.tags respect tagrelative option. Instead of using `cat` command to show content of tags file `rg` or `grep` is used as they are able to print which file the line is from.
Fixes #1309
Create a tag which is **not** located in the directory you open nvim but in a subfolder. The tags in the tag file are then relative to the subfolder and not nvim's cwd. Run `:Telescope tags` when you have a file open in the subfolder, this should result in showing the tagpaths relative to nvim's cwd.
* Neovim version (nvim --version): 0.9.0
* Operating system and version: Ubuntu 22.04.2 LTS
=> Fix tagrelative option not considered in builtin.tags

README.md
Fix a small, but confusing typo in the README.
The previous values were incorrect. The new values reflect the correct way of using the branch, as showcased in the previous examples.
=> docs: fix the branch example for lazy.nvim

lua/telescope/builtin/init.lua
One of the builtins unconditionally requires `__lsp` module causing too many modules to load on startup by simple `require("telescope.builtins")`.
Before:
```
020.600  000.025  000.025: require('telescope._extensions')
020.604  000.072  000.047: require('telescope')
020.804  000.015  000.015: require('plenary.tbl')
020.809  000.037  000.022: require('plenary.vararg.rotate')
020.810  000.055  000.018: require('plenary.vararg')
020.826  000.015  000.015: require('plenary.errors')
020.847  000.019  000.019: require('plenary.functional')
020.850  000.118  000.030: require('plenary.async.async')
020.870  000.019  000.019: require('plenary.async.structs')
020.875  000.170  000.033: require('plenary.async.control')
021.154  000.022  000.022: require('plenary.bit')
021.175  000.013  000.013: …
```
=> fix: fix builtins lazy loading

lua/telescope/builtin/__lsp.lua
Added support for dynamic registration of capabilities to all the lsp pickers.
I also refactored the relevant code a bit to make it less verbose.
Any code that wants to check lsp capabilities should use `client.supports_method`.
That function includes checks for dynamically registered capabilities.
Just checking `server_capabilities` only includes caps that were advertised during init.
Fixes https://github.com/LazyVim/LazyVim/discussions/990
Fixes `goto definition` for a number of lsp servers like `jdtls` and `solargraph`
I've testes all the methods using several LSP servers including the one `solargraph` where go to definition was broken.
=> feat(lsp): added support for dynamic capabilities

lua/telescope/builtin/init.lua
Fixes #2612
Tested with the steps from #2612
=> fix: do not ignore mappings from `setup()` when attach_mappings provided

lua/telescope/_.lua, lua/telescope/actions/history.lua, lua/telescope/builtin/__files.lua, lua/telescope/from_entry.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/utils.lua
getting tired of unusual paths being over expanded by `vim.fn.expand` causing an assortment of issues (commonly in telescope-file-browser).
this might be overkill and have some edge cases where things being under expanded. 
i'll ride this branch for a few days to see how it goes.
partially closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/289
=> expand paths more smartly

lua/telescope/pickers.lua
Ensure that any keystrokes that are queued at picker launch are processed only
after the picker's mode (`insert` or `normal`) has been chosen, preserving
their intended meaning.
Previously the picker's mode was set by simulating keystrokes via `feedkeys()`.
In the absence of queued keystrokes, this works fine; but if the user is able
to queue keystrokes before the call to `feedkeys()`, those queued keystrokes
are processed before the simulated keystrokes that change the picker's mode.
Because of this unexpected ordering, the user's queued keystrokes may appear to
be ignored or may cause the picker to start in the wrong mode.
For example, consider the below normal-mode mapping:
```vim
:nnoremap <space>ff :Telescope find_files<CR>
```
Upon launching the picker via `<space>ff`, Neovim is …
=> fix: preserve queued keys at picker launch (#2274)

README.md, doc/telescope.txt, lua/telescope/builtin/__git.lua, lua/telescope/builtin/init.lua, lua/telescope/operators.lua
[fzf.vim](https://github.com/junegunn/fzf.vim#commands) has a feature where the `:BCommits` command shows only commits affecting the selected lines, if run from visual mode.
This functionality cannot be replicated in telescope with config options alone. Fzf.vim uses the [arguments](https://github.com/junegunn/fzf.vim/blob/dc71692255b62d1f67dc55c8e51ab1aa467b1d46/autoload/fzf/vim.vim#L1278) `git log --no-patch -L start,end:file`, which are not compatible with the filename that telescope appends to `git_commands`. (I tried some hacks like adding an argument to `git_commands` to make git ignore the filename argument, but they didn't work).
~~This PR only affects bcommits behavior when run in visual mode, so I think it's a minor change but could be considered breaking.~~
This PR adds …
=> feat(git): Add bcommits_range picker

doc/telescope.txt, lua/telescope/pickers.lua
Reverts nvim-telescope/telescope.nvim#2618
=> Revert "fix: preserve queued keys at picker launch (#2274)"

doc/telescope.txt, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/init.lua
I'm currently working on a telescope picker that exposes some `ast-grep` functionalities. Seeing that the match highlighting in the existing previewers is limited to full single line only, I implemented finer-grained range highlighting capabilities in the `vim_buffer_vimgrep` previewer to improve match visualization. This could benefit any existing match-based picker.
[](url)
In case this feature is accepted, I have some pending questions:
- In the current implementation, I’m overriding the existing `TelescopePreviewLine` highlights. Should the range highlight use a new hl group and be added on top of the existing `TelescopePreviewLine` highlight instead?
- Should the range highlight become a default for certain builtin pickers? Or should it be opt-in as a config option?
Closes #933 (if …
=> feat: highlight range in previewer

lua/telescope/builtin/__files.lua, lua/telescope/make_entry.lua
This reverts commit 6074847b6ee4b725747c8fc540d9b6b128ac8a12 due to performance regression.
Related PR https://github.com/nvim-telescope/telescope.nvim/pull/2583
closes #2627
=> Revert "Fix tagrelative option not considered in builtin.tags (#2583)"

README.md
The following `autocmd` example in README is wrong, since both `number` and `wrap` are window-scoped options.
https://github.com/nvim-telescope/telescope.nvim/blob/d2e17ba18a6840b7e7079764b282616c3188e0de/README.md?plain=1#L410-L421
Tests are not needed.
=> fix: autocmd example in README

doc/telescope.txt, lua/telescope/builtin/__diagnostics.lua, lua/telescope/builtin/init.lua
Adds a new `sort_by` option to the `diagnostics` picker.
This option takes one of the following strings to tweak the sort order of the diagnostics results.
- "buffer" [current/default]: order by bufnr (prioritizing current bufnr), severity, lnum 
- "severity": order by severity, bufnr (prioritizing current bufnr), lnum
Having this as a string option leave the door open for implementing other sorting functions.
Can also later be converted to also take a comparator function directly (`string|function`) if desired.
closes #2631
=> feat(diagnostics): add sort_by option

lua/telescope/builtin/__files.lua
For live_grep and grep_string pickers.
Still semi-regularly see comments on old issues about missing rg as a dependency for live_grep https://github.com/nvim-telescope/telescope.nvim/issues/506. 
I think adding a warning for these pickers when ripgrep is not found will probably save quite a few people some headache.
Backport to 0.1.2?
=> add missing dependency warning for ripgrep

lua/telescope/builtin/__files.lua
Reverts nvim-telescope/telescope.nvim#2623
On second thought, I guess some people might have custom some custom`vimgrep_arguments` that uses something other than `rg`. I'll redo this taking that into consideration.
Sorry.
=> Revert "add missing dependency warning for ripgrep"

lua/telescope/config.lua, lua/telescope/finders.lua, lua/telescope/finders/async_job_finder.lua, lua/telescope/pickers.lua
add a searching indicator `*` to prompt
when searching is done. it will dispear.
also fix the bug in `function Picker:get_selection_row()`
when `self.sorting_strategy == "ascending"` it should return 0 not `max_results`
#1713
* Neovim version (nvim --version):0.9.1
* Operating system and version:macOS 13.4
=> feat: add searching indicator (#1713)

developers.md
I fixed a small typo (`completly -> completely`) in `developers.md`. The motivation for fixing this issue is to help make the documentation typo-free.
N/A
N/A
=> Fixed small typo.

lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
Benchmarked against 80k+ unique paths, both Windows and Linux (macos should be close enough to llinux).
Approximately 13% faster for linux paths and 55% faster for windows paths.
```
hyperfine 'luajit current_linux.lua' 'luajit fast_linux.lua' --warmup 10
Benchmark 1: luajit current_linux.lua
Time (mean ± σ):      25.7 ms ±   0.8 ms    [User: 22.7 ms, System: 3.4 ms]
Range (min … max):    24.0 ms …  28.8 ms    87 runs
Benchmark 2: luajit fast_linux.lua
Time (mean ± σ):      22.7 ms ±   0.8 ms    [User: 19.4 ms, System: 3.6 ms]
Range (min … max):    21.4 ms …  26.0 ms    99 runs
Summary
luajit fast_linux.lua ran
1.13 ± 0.05 times faster than luajit current_linux.lua
hyperfine 'luajit current_win.lua' 'luajit fast_win.lua' --warmup 10
Benchmark 1: luajit current_win.lua
Time (mean ± σ): …
```
=> perf(utils): linear scan `is_uri`

lua/telescope/actions/init.lua
For some git actions pressing Esc for the dialog of action confirmation didn't cancel the action. I moved asking for confirmation to a separate function and a bit changed notifications about canceled action.
Fixes #2438. But it turns out it is possible to still use `vim.fn.input()`, so I didn't switch to `vim.ui.input()`. 
I opened neovim and manually checked that confirmations for all the possible actions in `:Telescope git_branches` work as expected.
* Neovim version (nvim --version): NVIM v0.9.1
* Operating system and version: MacOS Ventura 13.5
=> fix(actions): fix Esc in git actions confirmation

lua/telescope/pickers.lua
Fix #2667.
After process_complete, call `nvim_win_set_cursor` to redraw results win.
=> Redraw results win after process_complete

lua/telescope/builtin/__diagnostics.lua, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
Added new value "full" for line_width option in builtin.diagnostics. When "full" is set there are no restrictions on diagnostics message line width and so whole message is shown.
Until this change, line_width could only be number. Maximum line width was "one width" of picker window and longer messages were cut.
This was annoying since you generally want to read whole error message.
Fixes #2020
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list 
relevant details about your configuration
- in config defaults set `wrap_line = true`
- open project where there is error with long message
- open diagnostics with …
=> add 'full' for line_width in diagnostics options

lua/telescope/actions/init.lua, lua/telescope/builtin/__internal.lua, lua/telescope/utils.lua
When filtering builtin.pickers doesn't resume the correct picker or delete it.
Ran require('telescope.builtin').live_grep 10 times with different queries. Then search for specific entries and hit enter and verified that there resumed picker has the distinct text that I had selected. I also removed some of them from the beginning, middle and end.
=> fix(builtin.pickers): fix wrong picker resuming when using filtering

lua/telescope/builtin/__diagnostics.lua
https://github.com/neovim/neovim/pull/24736 has introduced a new syntax for severity format in `vim.diagnostic.get()`.
Fix #2661
- Neovim HEAD
```
NVIM v0.10.0-dev-3455+g18062f70d-Homebrew
```
* Operating system and version: macOS Ventura 13.4.1
=> fix: use nil for the default diagnostics severity

lua/telescope/pickers.lua, lua/telescope/state.lua
telescope.state.get_existing_prompts currently returns all the keys from TelescopeGlobalState, this includes the 'global' key. This function is only used in Picker:close_existing_pickers where we iterate through the  prompt_bufnr and call actions.close on each prompt_bufnr so it should only return keys that are numbers
Run
:lua =require('telescope.state').get_existing_prompts()
When there are no pickers opened. It should return and empty table. With a picker present it should return the bufnr for that picker's prompt.
=> fix(telescope.state.get_existing_prompts): it should only return keys that are numbers

CONTRIBUTING.md
Added a missing "." character in the spelling in CONTRIBUTING.md
=> Add missing "." character in CONTRIBUTING.md

lua/telescope/builtin/__internal.lua, lua/telescope/pickers.lua
In Picker:new there was
```lua
if obj.preview_title == nil or #obj.all_previewers > 1 then
obj.preview_title = obj.previewer:title(nil, config.values.dynamic_preview_title)
else
obj.fix_preview_title = true
end
```
so if a preview_title was not provided at creation it became static forever. This is a problem when you resume a picker as internal.resume calls Picker:new again and the same preview_title is populated during runtime by the dynamic_preview_title. So now that field is not nil and will become static forever.
To fix it add an additional check. If the picker is resumed and fix_preview_title is not already set by the first creation do not set it now.
This fixes https://github.com/nvim-telescope/telescope.nvim/issues/2689
- Bug fix …
=> fix(internal.resume): dynamic_preview_title was not respected and title became static

lua/telescope/actions/init.lua
Add `QuickFixCmdPre` and `QuickFixCmdPost` event triggers to `send_selected_to_qf` and `send_all_to_qf`
closes #2669
=> feat(actions): add quickfix list autocmd event exec

lua/telescope/command.lua
As a last resort if no other cmd is found in `run_cmd`, check if the command can be loaded as an extension.
I know pcall is a bit hacky, but not needing to load every extension on startup is nice.
Install extension `telescope-frecency`, but don't load it with `load_extension`. Then, run `:Telescope frecency`. Before this change, this would error. Now, the command runs as expected.
=> feat: check if cmd extension can be loaded

doc/telescope.txt, lua/telescope/pickers.lua
`prompt_prefix` with leading whitespace combined with the normal mode `cc` command was resulting in telescope getting the prompt text from the wrong line
More details: https://github.com/nvim-telescope/telescope.nvim/issues/2698#issuecomment-1718469405
Fixes #2698
=> fix: `prompt_prefix` leading whitespace normal mode cc

lua/telescope/builtin/__git.lua
closes #2707 
`tbl_islist` vs `tbl_isarray` shouldn't matter here
=> fix(git): `tbl_isarray` compat with nvim 0.9

lua/telescope/builtin/__diagnostics.lua
There was a small issue on the diagnostics builtin where if a single severity was set as a single string value, the execution would break due to a invalid check if that value was a table. Which should only be applicable when setting a range (limit and bound).
Just moved that validation where only a range is used and not a single severity.
Fixes #2708 
=> fix: only validate severity table when using a range

lua/telescope/pickers/layout_strategies.lua
The cursor layout uses winline() and wincol() to calculate the cursor position. Both these functions operate on the currently active window. The first time the calculations are performed, that happens to be the window active before showing the Telescope window. However, if the editor is then resized or the preview window is toggled, the active window changes. The result is that recalculating the position is then done using the wrong window, resulting in the Telescope window moving around in an erratic manner.
To fix this, we have to scope the winline() and wincol() calls to the original window ID.
To test, you'll need to use the `cursor` layout. If you then show Telescope, followed by either …
=> Fix resize/preview toggles of the cursor layout

doc/telescope.txt, lua/telescope/actions/generate.lua, lua/telescope/actions/layout.lua, lua/telescope/actions/set.lua, lua/telescope/builtin/__internal.lua, lua/telescope/config.lua, lua/telescope/pickers.lua, lua/telescope/pickers/entry_display.lua, lua/telescope/pickers/layout.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/previewer.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/testharness/helpers.lua, lua/telescope/utils.lua, scripts/gendocs.lua
Introduces a `create_layout` config. It enables plugging in completely separate UI components.
This also enables features like this to stay outside Telescope core: https://github.com/nvim-telescope/telescope.nvim/pull/2381
Telescope core can essentially stop caring about layout customization. It'll only require `create_layout` to return a specific structure. And the rest can be managed externally.
Related Issues/PRs:
- https://github.com/nvim-telescope/telescope.nvim/issues/2548
- https://github.com/nvim-telescope/telescope.nvim/issues/2508
- https://github.com/nvim-telescope/telescope.nvim/issues/1054
- https://github.com/nvim-telescope/telescope.nvim/pull/2381
```lua
local Layout = …
```
=> feat(pickers): fully customizable layout

doc/telescope.txt, lua/telescope/builtin/__files.lua, lua/telescope/builtin/init.lua
adds new option to the `current_buffer_fuzzy_find` picker `results_ts_highlight` to enable/disable treesitter highlight for result entries (default: true)
closes https://github.com/nvim-telescope/telescope.nvim/issues/2720
=> feat(current_buffer_fuzzy_find): `results_ts_highlight` option

lua/telescope/config.lua, lua/telescope/previewers/buffer_previewer.lua
Fixes #2247 - highlighting is not async (yet) so blocks input
BREAKING CHANGE: Default value will cause files > 1MB to not be highlighted. Removing this default would make this a non-breaking change.
The following Wiki section should also be updated to point out this new option: https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#disable-highlighting-for-certain-files
=> feat(preview)!: add `opts.preview.highlight_limit` with default 1MB

lua/telescope/actions/set.lua
Folding (with `foldexpr`) for files opened with Telescope is broken.
Fixes #699
=> fix(actions): fixes folding. Fixes #699

lua/telescope/builtin/__lsp.lua
I have noticed an issue with the `LSP Outgoing Calls`.
Below are the the `LSP Outgoing Calls` shown for the [InputContext](https://github.com/dagster-io/dagster/blob/25b72467251f6c51f73f71039c09de1f6fb1521d/python_modules/dagster/dagster/_core/execution/context/input.py#L39) Python class from the `dagster` package.
As it can be seen in the below screenshot, the highlighted line is different between `LSP Outgoing Calls`  and `Grep Preview`, which clearly highlights a different line:
Here is the same thing, but with the results in the `quickfix` window and the highlighted line in the upper window, to easily see that the problem is the returned line number:
Upon investigation, it turned out the problem was in the `call_hierarchy` function, …
=> Bugfix in LSP Outgoing Calls

lua/telescope/actions/init.lua
fixes actions.which_key for 0.9.4 
Related #2734 #2735 but ~~there is more work to be done to fix it for 0.1.x~~
=> fix: correctly create User autocmd in action.which_key

doc/telescope.txt, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua
Sometimes when I'm coding I want to jump to a definition using the command `builtin.lsp_definitions`, for example, and it adds a new buffer on top of the buffer I'm working on. This behavior is something I don't like, so I started reading the documentation for changing that behavior and I found a parameter called [`jump_type`](https://github.com/nvim-telescope/telescope.nvim/blob/74ce793a60759e3db0d265174f137fb627430355/lua/telescope/builtin/init.lua#L444) and I set it to `tab`. However, there is another problem: when I jump to a definition, it adds a new tab buffer, but, if that tab buffer is already opened, it does not jump to it, it adds a new one. So, the behavior that I was looking for only exists with the command `tab drop`, so I added it to the list of options for the `jump_type` …
=> feat(lsp-jump-type): `tab drop` as new `jump_type` option for `go-to` LSP pickers

lua/telescope/previewers/term_previewer.lua
This pull request fixes the following error:
```
E5108: Error executing lua: Vim:Can't send data to closed stream
[C]: in function 'chansend'
/lua/telescope/previewers/term_previewer.lua:224: in function '_send_input'
/lua/telescope/previewers/previewer.lua:85: in function 'send_input'
/lua/telescope/previewers/term_previewer.lua:238: in function '_scroll_fn'
/lua/telescope/previewers/previewer.lua:93: in function 'scroll_fn'
/lua/telescope/actions/set.lua:249: in function 'run_replace_or_original'
/lua/telescope/actions/mt.lua:65: in function 'scroll_previewer'
/lua/telescope/actions/init.lua:222: in function 'run_replace_or_original'
```
This error can be triggered using `new_termopen_previewer()`, in case its `get_command()` ends without pagination [(full …
=> fix: do not send data to closed stream

lua/telescope/previewers/buffer_previewer.lua
With this change we will check if the provided buffer number is valid, before querying its `buftype` option. This is necessary, because currently we would fail with:
```
Error executing vim.schedule lua callback:
...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:473:
Invalid buffer id: X
```
error, if we try to resume a jumplist picker after doing `:bwipeout`.
Fixes #2750
Use the steps to reproduce from #2750.
```
NVIM v0.9.2
```
* Operating system and version: Gentoo Linux, release 2.14
cc @Conni2461
=> Fix jumplist picker resume after bwipeout

lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua
…sues/2763
Added new mark_type option for the marks picker as suggested on the issue 
NVIM v0.9.2
fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"
Darwin PWJPG61VXG 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64
=> Implementation of #2783.  Add support for displaying marks according to the mark_type

lua/telescope/previewers/buffer_previewer.lua
Solves the problem of not scrolling horizontally when the preview buffer has arbitrary short and long lines by setting `virtual edit` as suggested here https://github.com/nvim-telescope/telescope.nvim/issues/2211#issuecomment-1358664622
This solution enables horizontal scrolling on the preview buffer regardless of its content.
Fixes https://github.com/nvim-telescope/telescope.nvim/issues/2243#issuecomment-1358474060
Horizontally scrolling preview buffers.
```
NVIM v0.10.0-dev-1045+g131a1ee82
LuaJIT 2.1.1693350652
```
```
OS: Ubuntu Linux x86_64
Kernel: 6.2.0-34-generic
```
**Also tested on OSX:**
* Neovim version …
=> fix(preview): allow arbitrary horizontal scrolling

lua/telescope/pickers.lua
Could be helpful. Currently there is an issue with using `vsp/sp` inside telescope(wrong execution)
Fixes #2781 
- Check issue
* Neovim version (nvim --version): v0.10.0-dev-98bb1d6
* Operating system and version: Fedora 38
=> fix: correct execution of vsp/sp commands

doc/telescope.txt, lua/telescope/actions/init.lua
This PR adds a `delete_mark` action, which can be used in conjunction with the `builtin.marks` picker. 
* Neovim version (nvim --version): `v0.9.4`
* Operating system and version: MacOS Sonoma
=> feat(actions): add delete_mark

lua/telescope/_.lua
fix the ayncjob:close not actualy close the process
Fixes #2797 
```
local uv = vim.loop
local _, pid = uv.spawn("bash", {
args = {
"-c",
"while true; do echo \"1\"; sleep 1; done"
}
})
uv.kill(pid, "SIGTERM")
vim.schedule(function()
local ret = uv.kill(pid, "sigterm")
if not ret then
print(pid.." not found")
else
print(pid.." closed")
end
end)
```
* Neovim version (nvim --version):v0.9.4
* Operating system and version:macOS
=> fix: async job close not working #2797

lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua
Adding `buffers_sort` option to `buffers` to sorts the buffers before displaying the picker.
This allows users to have control on how buffers are displayed in the picker.
It runs after sorting by `sort_mru` to avoid collision.
Users might have specific logic to sort buffers, as example, I want to sort the buffers that I marked (pin) in a global state
```lua
table.sort(bufnrs, function(bufnr_a, bufnr_b)
if state.is_buffer_pinned(bufnr_a) then
return true
end
return false
end)
```
This allows me to have a `harpoon-ish` behaviour.
Only manual test. I haven't found existing tests for the options of this specific picker.
* Neovim version (nvim --version): NVIM v0.9.4 …
=> feat(buffers): add buffers_sort option

lua/telescope/mappings.lua
This adds horizontal scrolling that was added from PR #2437 to normal mode key bindings.
Open `Telescope ...`,  input query, then scroll to the left or to the right in previewer or results window with added key bindings.
* Neovim version (nvim --version): NVIM v0.9.2
* Operating system and version: macOS Ventura v13.6.2
=> Add horizontal scrolling to normal mode

lua/telescope/builtin/__internal.lua
make the 0-args command could be repeated by `@:`
=> make the 0 args command could be repeated by `@:`

lua/telescope/builtin/__git.lua
Currently, `git_status` with a prompt that has zero matches closes the picker.
Only automatically close the picker if working tree is completely clean. If working tree is not clean, and a prompt is given but no matches are found, keep the picker open. This behavior is consistent with other pickers where lack of matches doesn't result in the picker closing.
closes #2815
=> fix(git_status): keep picker open with no matches

doc/telescope.txt, lua/telescope/actions/init.lua
Add autocmd to make `which_key` window close on prompt exit.
Currently `actions.which_key` supports a `close_with_action` option (default true). When this is set, the `which_key` window will close after any Telescope action is triggered. This makes sense. However, when it is false, the `which_key` window remains open even after Telescope
closes. This seems like a bug.
This PR fixes this by setting an autocommand when `close_with_action` is false to close on prompt exit.
Manually tested this by running `Telescope` and triggering `which_key` with `close_with_action` set to both true and false, observed expected behavior in both cases.
=> Close which key on prompt close

lua/telescope/builtin/__internal.lua
remove deprecated `nvim_exec` call and modernize `vim.cmd("colorscheme " .. "foobar")` to `vim.cmd.colorscheme("foobar")`
=> refactor(colorscheme): clean up `vim.cmd` colorscheme calls

lua/telescope/builtin/__internal.lua
fixes bad current colorscheme fetching which was resulting in an empty string entry.
closes #2836
=> fix(builtin.colorscheme): get current colorscheme

lua/telescope/pickers.lua
Recently noticed wrap_results option is not working and this pr fixes it.
No issue raised yet I believe. searched but couldn't find an open issue for the same
* Neovim version (nvim --version): NVIM v0.9.4
* Operating system and version: MacOS 14.2.1 Sonoma
=> Fix wrap option not set when wrap_results is true

lua/telescope/builtin/__internal.lua
closes #2843
Previously, bad partial matches between cwd and target buffer path would result in non-cwd buffers showing up in the picker despite using `only_cwd=true`.
eg.
cwd = `/foo/bar`
target buffer = `foo/bar1/baz.txt`
The target buffer starts with the cwd path.
This is fixed by appending a path separator before comparing/matching: eg.
cwd = `/foo/bar/`
target buffer = `foo/bar1/baz.txt`
=> fix(builtin.buffers): improve `only_cwd` handling with partial matches

lua/telescope/builtin/__internal.lua
Previously, using `string.find`, certain characters were taken as regex special characters leading to bad matches.
New approach takes bufname truncated to the length of cwd and compares the two strings.
ref: https://github.com/nvim-telescope/telescope.nvim/pull/2845#issuecomment-1876227314
=> fix(builtin.buffers): better buffer in cwd check

lua/telescope/builtin/__files.lua, lua/telescope/builtin/__git.lua, lua/telescope/pickers.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
Fixing the original issue: When selecting files in the telescope impossible to copy paths from the compiler, you need to clear the location from the path.
Fixes #2650
This fixes the problem by stripping out the location from the path (important: only for file pickers). And using the location to set the cursor when opening the file.
There is a new option `files_picker` for a `Picker` that needs to be set to true for all file pickers, for now, it basically enables location stripping which makes no sense in another type of pickers.
Watch the video:
https://github.com/nvim-telescope/telescope.nvim/assets/16926049/1ee3b507-4af9-4d0f-abe2-3c67254dfcd9
I didn't find another way to put the location stripping because it must happen right …
=> feat: Support Line Column in file pickers

lua/telescope/builtin/__files.lua
Fixes `builin.grepstring` in visual mode for users that have "\\"" or "y" remapped.
* Neovim version (nvim --version): NVIM v0.10.0-dev-2048+g367e52cc7
* Operating system and version: Linux 6.1.71-1-lts x86_64
=> fix(builtin): use 'normal!' instead of 'normal'

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
Fixes https://github.com/nvim-telescope/telescope.nvim/issues/2838 and https://github.com/nvim-telescope/telescope.nvim/issues/2121
- Hidden directory: 
* Neovim version (nvim --version): NVIM v0.10.0-dev-2021+gee2127363 
* Operating system and version: Ubuntu 22.04.3 LTS
Apologies if this is a bad solution, I'm still quite new to neovim development. This was something that periodically annoyed me about all of the lists that use the quickfix entry maker 😅 
Questions:
- Is it worth renaming the quickfix entry maker? IMO the name is a bit overloaded now
- Do we need tests for this? From a quick look, it doesn't seem like any of the existing (automated) tests verify display
=> fix(builtin): quickfix entry maker does not used fixed width for file

lua/telescope/builtin/__internal.lua
The `filename` value for quickfix lists expects a normalized/absolute path.
Was previously not normalizing `~/`.
=> fix(builtin.marks): normalize mark path

lua/telescope/builtin/__internal.lua
`vim.fn.matchstrpos({expr}, {pat})` doesn't handle all characters well since the pattern (cwd path in this case) is used as a regex pattern.
=> fix(builtin.oldfiles): cwd matching with special characters

lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
Fixes couple of regressions from #2791 when no line number info is given in the prompt (eg. `file.txt` rather than `file.txt:10`). 
Both issues stemming from the fact that when no line number info is given, the `entry.lnum` was set to `0`. `entry.lnum` is 1-index.
- Sending results to quickfix would send faulty results (closes #2864)
- Will no open the file on the correct (previous) line number
For this, setting the lnum to 1 is still undesirable since this overwrites the lnum priority handling in the `select` action.
=> fix(pickers): when no lnum given, don't set entry.lnum

lua/telescope/builtin/__internal.lua
Small fix to also include the file location option in recent files
Fixes #2862
I've used this in my config for a day, no issues.
* Neovim version (nvim --version): NVIM v0.10.0-dev-2048+g367e52cc7
* Operating system and version: Fedora 39
Extra: I also noticed this was the last place `file_previewer` was still used. Not sure if this means anything, but it's worth mentioning.
=> feat: support file location in Oldfiles

lua/telescope/builtin/__files.lua, lua/telescope/previewers/utils.lua
`nvim-treesitter` is in the middle of a rewrite, and will switch to the rewrite once Neovim 0.10 is released. In this rewrite, there is something that has changed with registering a language. This introduces an issue in telescope, where it is not always able to provide treesitter highlighting in the preview.
Reading the code in `nvim-treesitter`, it also uses `vim.treesitter.language.get_lang` and always fallback to the filetype if the function doesn't provide any language
Install the newest `nvim-treesitter` using the `main` branch. Try to open a picker with a previewer, and notice that some languages where the filetype name matches the parser name, and see that it is not properly …
=> fix: fallback to filetype for get_lang for treesitter highlight preview

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/mappings.lua, lua/telescope/pickers.lua
Store `<cword>` on picker:find and create new action `insert_original_cword` (maybe just `insert_cword`?) to insert/append the cword of the original window/buffer under telescope into the prompt buffer.
Allows for similar behaviors to `c_CTRL-R_CTRL-W`.
closes https://github.com/nvim-telescope/telescope.nvim/issues/2730
=> feat(picker): allow appending original window cword to prompt

lua/telescope/previewers/buffer_previewer.lua
When peviewing new files with git_status, binary files show noises.
This is because the current previewer does not inherit global- or user-options.
My PR passes the option to previewer.
This can be considered as fix and new feature at the same time.
```
NVIM v0.10.0-dev-1962+gc26dc1f77
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```
Manjaro Linux
=> feat(git_status): allow buffer_previewer_maker to receive options

doc/telescope.txt, lua/telescope/pickers/layout_strategies.lua
Reverts nvim-telescope/telescope.nvim#2887
This PR made `width` a non-valid option for the `bottom_pane` layout strategy (which it is).
But if you had
```lua
require("telescope").setup({
defaults = {
layout_config = {
width = 120,
}
}
})
```
since you want all layouts that support it to use width 120, you'd get an error using `bottom_pane`.
I think we should only throw errors if we're setting invalid options specific to the strategy being used.
ie
```lua
require("telescope").setup({
defaults = {
layout_config = {
bottom_pane = {
width = 120, -- invalid, throw error
},
width = 120, -- allow this since not strategy specific
}
}
})
```
Something to do later.
=> Revert "doc(layout_strategies): document shared options for `bottom_pane`"

doc/telescope.txt, lua/telescope/actions/state.lua
I have been trying for quite some time to find this method in docs, but it was nearly improssible. The description should contain either "input" or "prompt", because those are the keywords that most people would search for when trying to find this method.
No test, just docs update
NVIM v0.9.5
LuaJIT 2.1.1702233742
=> doc(action_state): improve description of action_state.get_current_line

doc/telescope.txt, lua/telescope/mappings.lua
Currently the `map` function in `attach_mappings` doesn't respect the `desc` option for `vim.keymap.set` which we use under the hood.
This results in anonymous functions to show up nameless, as `<anonymous>`,  in which-key regardless of whether a `desc` is passed.
```lua
attach_mappings = function(_, map)
map("i", "<C-f>", function() print("im anonymous") end, { desc = "hi" }) -- shows up as anonymous
end
```
closes #2888
=> fix(mappings): allowing passing `desc` to mappings

lua/telescope/previewers/buffer_previewer.lua
When you preview a terminal buffer for the first time after `:Telescope buffers`, the preview is not scrolled to and centered to the line the cursor is on, unlike normal buffers that have a file associated with them.
This PR fixes the issue so that the preview for a terminal buffer is correctly scrolled.
1. Start neovim
2. Create a terminal buffer (`:terminal`) and inside it, run `seq 1000` (or something else that produces lots of lines)
3. Open a random file
4. Run `:Telescope buffers`
- The first time you preview the terminal buffer, the preview is not scrolled to the line the cursor is on.
- Preview the other entry (the file you opened) and preview the terminal buffer again. Now the preview is correctly scrolled.
- After this PR is …
=> fix: terminal buffer previews not initially scrolled

lua/telescope/builtin/__files.lua, lua/telescope/previewers/buffer_previewer.lua
While using some Telescope commands that jump directly to a line in a file (like `tags`), the function first opens the file, then call `norm! gg` and search for the target line.
This will include the top of the file in the jumplist.
Since the top of the file is not jumped-to by user, it's not a position that the user cares about; it would make sense to not include this position in the jumplist.
To see this behaviour, open a file, call the `Telescope tags` command, select and confirm any tag that is in the middle of a big file (i.e. when the target tag is jumped-to, the top of the file (line 1) should ideally not be visible), then press `Ctrl-O` to go back in the first file you edited just before the `Telescope tags` invocation.
This will not set you back in the first file, but at the top …
=> fix: do not change the jumplist when using to a line in a file

lua/telescope/builtin/__internal.lua, lua/telescope/make_entry.lua
Better support for lua callback autocmds: you can now jump to the source/definition of these type of autocmds (as well). Simple change.
Fixes # (issue) (couldn't find any related issues?)
=> feat(builtin.autocommands): support jumping to lua callback src

lua/telescope/builtin/__files.lua
Currently the in buffer fuzzy search always jumps to the first character of the selected line. This PR enhances it to jump to the first same character on the line as the first character from the search. See demo below.
Motivation: I assume people use this helper as an enhanced version of <kbd>/</kbd> or <kbd>?</kbd>. Alternatively this is as useful as <kbd>cmd/ctrl</kbd><kbd>f</kbd> from modern GUI editors and IDEs. Both jump to the match instead of the beginning of the line.
1. Open any file
2. Run `:Telescope current_buffer_fuzzy_find`
3. Search for something that is not on the first character on the line that you want to go to
4. Expect …
=> feat(builtin.current_buffer_fuzzy_find): jump to first matched char

lua/telescope/previewers/buffer_previewer.lua
In repos with many commits, git log flag `--abbrev-commit` will increase the number of characters from 7 to 8 to ensure unicity. The git branches preview highlight is therefore off by one in this case.
Before and after:
* Neovim version (nvim --version): NVIM v0.10.0-dev-2361+ga376d979bd
* Operating system and version: Arch Linux
=> Fix highlight of commit hash in git branches preview

lua/telescope/builtin/__lsp.lua
Refactor the `list_or_jump` helper function a little bit so that `references` picker can also use it.
=> refactor(lsp): consolidate some picker jump logic

lua/telescope/builtin/__git.lua
Pass `core.quotepath=false` to achieve this.
Could alternatively pass `-z` but that uses `\0` line termination and complicates things.
I think this is minor enough to just use as default. Shouldn't impact most people anyways.
Closes #2900
=> feat(git_files): support emoji/unicode in filenames

lua/telescope/pickers.lua
Despite setting `wrap=true` for the prompt window earlier, after setting `filetype=TelescopePrompt` in the main loop, `wrap` gets set to false.
I haven't determined the root cause of this. I can't reproduce this with a simple neovim api only config. I suspect there's something funny going on with the async main loop.
Maybe this isn't worth fixing though. I think we've been using prompt window `wrap=false` for a while now and I don't see any issues with it.
=> fix(picker): actually set prompt win to text wrap

doc/telescope.txt, lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua
With the buffers picker I'd like the current buffer to be pre-selected, but I don't like the buffer list to be mru sorted.
So that I can either navigate to nearby buffers using arrow keys or do a fuzzy search as usual.
The change adds a select_current option to the buffers picker.
If select_current is true then the the buffers picker will pre-select the current buffer (%) instead of the first one. Useful if you want to use arrow keys to select a nearby buffer. Best used in combination with selection_strategy = 'closest' so that when you start typing the first option is selected.
Fixes #2917
how do I update the docs, running `make docgen` fails with:
```
nvim --headless --noplugin -u …
```
=> buffers picker: add select_current option

lua/telescope/actions/init.lua, lua/telescope/make_entry.lua
When calling `send_to_qflist` for `builtin.diagnostics`, this `text` field of the qf entry could be set to describe the error type.
before:
after:
=> feat(action): add `type` into qf entry when calling `entry_to_qf` function

lua/telescope/pickers.lua
the `vim.fn.expand <cword>`  was throwing error whenever any picker was invoked on an empty line,
The addition of this `pcall` would make sure that never happens.
---
```elixir
Error executing Lua callback: Vim:E348: No string under cursor
[C]: in function 'expand'
...vim/pack/plugins/opt/telescope/lua/telescope/pickers.lua:532: in function 'find'
.../plugins/opt/telescope/lua/telescope/builtin/__files.lua:392: in function 'v'
.../plugins/opt/telescope/lua/telescope/builtin/__files.lua:641: in function 'v'
...ack/plugins/opt/telescope/lua/telescope/builtin/init.lua:579: in function <...ack/plugins/opt/telescope/lua/telescope/builtin/init.lua:538>
...vim/pack/plugins/opt/telescope/lua/telescope/command.lua:188: in function 'run_command' …
```
=> fix(picker): wrap vim.fn.expand cword in pcall to avoid Vim:E348

lua/telescope/config.lua
Flip the default for `cache_picker.ignore_empty_prompt` to false owing to some finding it unintuitive with some pickers.
closes https://github.com/nvim-telescope/telescope.nvim/issues/2952
=> fix(config): set default `cache_picker.ignore_empty_prompt` to false

lua/telescope/previewers/buffer_previewer.lua
I was digging into why my colorscheme wasn't displaying the correct diff colours for Telescope buffers, and I found that it was using the regex highlighter instead of tree-sitter based highlighting. This lead to it using the deprecated `diffAdded` and `diffRemoved` highlight groups. Another fix would've been to add a link for these deprecated groups, and that's still an OK option for me. I just wasn't sure if it's maybe better to use the tree-sitter highlighter anyways? Why was it forced to regex in those cases?
(I'm not sure if this is a bug-fix or breaking change, is tree-sitter a bad default that might break people?)
- Breaking change (fix or feature that would cause …
=> No regex highlighting in previewers

lua/telescope/pickers.lua
Reverts nvim-telescope/telescope.nvim#2930
This might be causing strange vim interactions (it was already a strange vim interaction, requiring this to begin with) that's causing neovim to completely freeze up in some cases.
See: https://github.com/nvim-telescope/telescope.nvim/issues/2953
=> Revert "fix(picker): actually set prompt win to text wrap"

lua/telescope/actions/layout.lua
If you set config
```
defaults.layout_strategy = "flex"
defaults.layout_config.prompt_position = "top"
```
Then call `toggle_prompt_position` it will did nothing at first time, because old_pos return nil.
Set default config to
```
defaults.layout_strategy = "flex"
defaults.layout_config.prompt_position = "top"
```
* Neovim version: nvim v0.9.5
* Operating system and version: Any
- [ ✓] My code follows the style guidelines of this project (stylua)
- [ ✓] I have performed a self-review of my own code
=> fix: `action_layout.toggle_prompt_position`

lua/telescope/builtin/__internal.lua
Neovim 0.7 compatible version of https://github.com/nvim-telescope/telescope.nvim/commit/5550bbb1b6406926fa5b23768c0b0ca9242281bb
=> fix(builtin.marks): expand mark path

README.md
Minor change in the README file to remove unnecessary `<cr>` tag on an example usage command.
- Documentation improvement
=> Removed unnecessary tag from command example

lua/telescope/pickers.lua
The current stable version (v0.9.5) and the nightly version have different results for the cursor position on the displayed content, I don't know exactly why.
After debugging, I found that this line of code causes the cursor to move down(row+1) when `sorting_strategy=ascending`,this result is consistent in v0.9.5 and nightly.
https://github.com/nvim-telescope/telescope.nvim/blob/67c598fdd4fca113224281c85721c4d8a6df055e/lua/telescope/pickers.lua#L436
However, when the result is displayed, the highlighted row and the cursor position are not the same, so it cannot be displayed in nightly version(by default, the second result is displayed at the top, in the same position as the cursor.).
So I think putting the cursor to the first line (i.e. highest score) again in …
=> fix(picker): ensure that the selected result matches the screen display in ascending sort order

lua/telescope/builtin/__internal.lua
When using lazy.nvim's lazy loading colorscheme, Telescope's colorscheme cannot see the lazily loaded colorscheme. 
In this case, I used the colors parameter to add the colorscheme. 
```
require("telescope.builtin").colorscheme({
colors = {"rose-pine-dawn", "everforest", }
})
```
If I open the Telescope's colorscheme twice(first time select `rose-pine-dawn`), duplicate entries will appear.
=> fix: remove duplicate item in colorscheme

lua/telescope/builtin/__lsp.lua
Previous implementation uses the incorrect lsp result fields for generating call site locations resulting in incomplete and incorrect results.
closes https://github.com/nvim-telescope/telescope.nvim/issues/2939
=> fix(lsp): incoming/outgoing_call range locations

lua/telescope/builtin/__lsp.lua
closes https://github.com/nvim-telescope/telescope.nvim/issues/2368
Just needed to pass the filename to these window/tab opening commands so that they don't needlessly create an empty buffer.
=> fix(builtin.lsp): extra No Name buffer opening with jump_type

lua/telescope/builtin/__lsp.lua
addresses https://github.com/nvim-telescope/telescope.nvim/pull/2990#issuecomment-2004178710
=> fix(builtin.lsp): bad check for `jump_type` option

lua/telescope/_.lua, lua/telescope/actions/history.lua, lua/telescope/builtin/__files.lua, lua/telescope/builtin/__git.lua, lua/telescope/from_entry.lua, lua/telescope/make_entry.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/utils.lua, lua/tests/helpers.lua
There's a few areas where I believe we're over expanding paths.
We've done some quick fixes with `vim.fn.escape` here and there but I want to explore rather than escaping certain characters then expanding, only expanding when the provided "path" is worth expanding (starts with either '%', '#' or '<'). 
~The places where I'm made changes, it should be safe to assume that at that point, a $ in a path mean the literal $ rather than some shell variable and I'm not even sure _if_ they even ever need expanding.~
Edit: ^ this should largely not be a concern anymore. Unlike with `vim.fn.escape`, `vim.fs.normalize` only expands `$` if it's actually a shell variable. 
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/289
also relevant: …
=> expand paths more selectively

lua/telescope/sorters.lua, lua/tests/automated/sorters_spec.lua
ref https://github.com/nvim-telescope/telescope-frecency.nvim/pull/177
ref https://github.com/nvim-telescope/telescope-frecency.nvim/issues/36
[telescope-frecency][] has used `get_substr_matcher` to match input string. This matcher always makes display string be lower case, so we cannot match against upper case letters as it is.
[telescope-frecency]: https://github.com/nvim-telescope/telescope-frecency.nvim
I introduced a customized matcher to solve this problem. → nvim-telescope/telescope-frecency.nvim#177 This makes it match upper case letters only when `'smartcase'` is ON and input string includes one upper case letter at least. I think this change is useful also in telescope.nvim itself, so I created this PR.
When candidates …
=> Change get_substr_matcher's behavior with 'smartcase'

lua/telescope/previewers/buffer_previewer.lua
`vim.loop.fs_stat` takes file paths literally so no escaping special characters are need (eg spaces, `$`, etc)
closes https://github.com/nvim-telescope/telescope.nvim/issues/2994
=> fix(previewer): don't escape paths for fs_stat

lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
In order to maintain plenary compatibility (for now, and slightly for other edge case reasons), avoid converting backslashes to forward slashes.
Aside: would be nice to add windows as part of the ci testing.
=> fix(utils.path_expand): improve windows support

lua/telescope/previewers/utils.lua
Handles edge case where buffer preview window is of line height 2 or less. Current preview message is at 3 lines long.
The fix adds in a check to handle a line height of 2 or less and shows only the preview message on the first line.
Fixes #3001
Configuration can be referred to in issue #3001.
Testing steps:
- Navigate to a directory with non-text files
- Open file browser
- Navigate selection to non-text file
- Preview message should be shown on the first line without throwing any errors
NVIM v0.9.5
LuaJIT 2.1.1710088188
macOS 14.4
=> fix(set_preview_message): check line height of previewer before setting message

lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
Adds os-agnostic unit tests for `transform_path` testing and fixes a couple of general edge cases and Windows specific path separator related bugs.
I was able to run these tests against my CI changes in https://github.com/nvim-telescope/telescope.nvim/pull/3011 to confirm they pass for all OSs.
=> test(utils): add unit test for `transform_path`

lua/telescope/actions/init.lua, lua/telescope/mappings.lua, lua/telescope/pickers.lua
Make it possible to scroll the results and preview window and add general mouse support.
It adds the following:
- scroll the results and preview window
- select items on click in the results window
- clicking on the preview window opens the specific buffer
- double clicking on a result opens the specific result
It resolves issue https://github.com/nvim-telescope/telescope.nvim/issues/2680
This is a preliminary version. It needs to be refactored and improved
=> feat(scrolling and mouse support): support scrolling and selecting with the mouse

lua/telescope/actions/init.lua, lua/telescope/mappings.lua
The previous scrolling implementation (#2687) moved the result selection by one item at a time, which isn't technically scrolling (ie. moving the view) and feels quite slow.
Let the neovim builtin scrolling do its thing, so using the scroll wheel feels like scrolling and is functionally scrolling, too. Scrolling does not move the selection so after scrolling it typically makes sense to click. Moving the selection with keyboard takes you back to where you were. This is in line with typical desktop user interfaces.
(No issue created for this, as it was trivial to change. I'll make a bug report if you wish.)
Please describe the tests that you ran to verify your changes. Provide instructions so …
=> fix(scrolling): enhance and simplify scrolling

lua/telescope/builtin/__internal.lua, lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
Fixes issue #3023, use the approach suggested in pull request #3024.
This commit lets mark picker preserve `uri`. 
It firstly lets `utils.path_expand()` return early when input is `uri`, then it uses `utils.path_expand()` in mark picker.
Original marked oil and fugitive buffers are opened as expected.
```
NVIM v0.9.5
LuaJIT 2.1.1703358377
```
```
macOS 14.4.1
```
- [ n/a] I have commented my code, particularly in hard-to-understand areas
- [ n/a] I have made corresponding …
=> fix(utils, mark picker): preserve uri in path_expand, use it in mark picker

lua/telescope/actions/generate.lua
Using anonymous function is throwing warning "No name available for anonymous functions" when `action_generate.which_key` is used as shown in the docs.
closes #3033
=> fix(actions): set function name for `generate.which_key`

.github/workflows/ci.yml, .github/workflows/docgen.yml, .github/workflows/lint.yml, .github/workflows/release.yml, Makefile, doc/telescope.txt, lua/telescope/utils.lua, lua/tests/automated/pickers/find_files_spec.lua, lua/tests/automated/telescope_spec.lua, scripts/minimal_init.vim
- add windows runner as part of test ci and fix any windows sensitive tests
- tweak Makefile & minimal_init so running tests locally isn't dependent on local directory structure (I wanted to do this with docgen as well but it's so flaky and impossible on nightly neovim anyways)
close #3000 
ps. sorry if you got spammed by failed ci notifs
=> build: rework ci tests to include windows

lua/telescope/actions/generate.lua, lua/telescope/actions/init.lua
add zindex option for `action.which_key`. The current value is 50 which sometimes conflicted with picker window. 
Fixes #2976
```lua
local action_generate = require 'telescope.actions.generate'
defaults = {
mappings = {
i = { 
['<c-/>'] = action_generate.which_key {
zindex = 60,
},
},
},
},
}
```
* Neovim version (nvim --version): 0.9.5
* Operating system and version: darwin-arm64
=> add zindex option for popup `action.which_key`

doc/telescope.txt, lua/telescope/actions/init.lua
`nvim_buf_delete` is not allowed during text change or window change. Window switching with left mouse click was leading to race condition/error.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3034
=> fix(which_key): close window on mouse click action

.github/workflows/docgen.yml
`docgen` doesn't get ran on PRs from forks.
Not sure if this is on purpose.
=> chore: add `pull_request` trigger on `docgen`

lua/telescope/utils.lua
This fixes the issue where some of the other options that are composable didn't display correctly. For now, `filename_first` needs to be the last option.
=> Moves filename_first to last position to fix issues with composing other options

lua/telescope/previewers/buffer_previewer.lua
Not showing a preview with the new changes in the latest changes of [plenary.nvim PR
#575](https://github.com/nvim-lua/plenary.nvim/pull/575).
The error occurs when changing from `nomodifiable` to `modifiable`. Telescope itself works, but the previews don't render. Thanks to @Conni2461 for telling me where the error occurred.
Fixes #3076
> [!note]
> All the visual evidences are in #3076 and [plenary.nvim PR
#575](https://github.com/nvim-lua/plenary.nvim/pull/575)
<details>
<summary>Test results</summary>
```lua …
```
=> fix(#3076): no preview showing when `set nomodifiable`

lua/telescope/config.lua, lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
Allows returning optional second argument from `path_display` option that is the `path_style`.
Fixes #3073 
Added test for general function handling.
* Neovim version (nvim --version): 0.9.5
* Operating system and version: Debian 12
=> feat: support path_style in path_display option

lua/telescope/builtin/__internal.lua
If the user remapped `:`, the `builtin.commands` picker would use the remapped `:` instead of inserting a command, which would lead to unintended behavior. My configuration swaps `;` and `:` around, which would lead to the keys in the command being inputted as normal mode commands. To make sure a command is inputted as expected, adding the `n` flag to `feedkeys` makes sure nvim uses the defaults.
```
NVIM v0.9.5
LuaJIT 2.1.1692716794
```
* Operating system and version: Arch Linux x86_64, `6.8.5-arch1-1`
=> fix(builtin.commands): Don't remap feedkeys

doc/telescope.txt, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/previewers/utils.lua
Problem: mime type for a ts/js file can either return `text/plain` or `application/javascript` based on the contents of the file. Previously, this meant `application/javascript` would be considered "possibly binary". This, in conjunction with how `vim.filetype.match` does not give a result for a filename that ends in `.ts`, would lead to a typescript file taking the path of `check_mime_type` and eventually `mime_hook`.
Solution: Include `application/javascript` as a non-binary file type during mime type check.
closes #3068
=> fix(previewer): improve binary mime type check

lua/telescope/builtin/__internal.lua
Remove backslash escaping in oldfiles picker, which was needed before the code was changed to use substring comparison instead of regex matching. (Commit b3ff5f33)
When using the `cwd_only` option for the `builtin.oldfiles` picker, no results were returned under windows.
The broken code replaces all backslashes by `\\`. This is not needed anymore, as the cwd-check now uses a substring match instead of matching via `matchstrpos()`.
- Switch to some directory under windows
- edit some files
- call `:Telescope oldfiles cwd_only=true`
- No results appear …
=> fix(builtin.oldfiles): fix cwd_only for windows

lua/telescope/builtin/__lsp.lua
This change restores the possibility to exclude the current line when invoking the `lsp_references` picker.
- `opts.include_current_line` is by default unset, so the previous equality check would fail unless the option was set explicitly.
- `vim.api.nvim_win_get_cursor()` returns both line and column, so it can't be directly compared with the returned line number.
- The actual comparison was expecting quickfix-like items, when in actuality, we were dealing with raw LSP location objects.
- Triggering `lsp_references` on a symbol which is only referenced in one other location jumps directly to that location.
- Triggering `lsp_references` on a symbol which is referenced in multiple other locations lists reference locations. References on …
=> Fix jump regression in LSP references action handler

lua/telescope/health.lua
In Windows, if only `rg` without extension is installed and `rg.exe` is not for some reason, checkhealth had failed previously.
This PR allows binaries without extensions to be recognised in Windows.
**FIXME**: In Windows environment, `io.popen(binary .. " --version")` does not return any outputs. How can I fix it?
```plaintext
Checking external dependencies ~
- OK rg: found 
- OK fd: found 
```
* Neovim version (nvim --version): v0.9.5
* Operating system and version: Windows 11
=> :bug: Windows: allow binary without extension

doc/telescope.txt, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua
clean up `list_to_jump` to work mostly with `vim.lsp.util.locations_to_items` output from the get-go
=> refactor(lsp): simplify `list_to_jump`

lua/telescope/pickers.lua
Sets the `current_line` global state earlier in the event loop rather than in `get_results_completor`. This makes it safer to access `current_line` earlier (eg. for building an entry).
closes #3051
I'm not super confident this is safe to do without some unintended side effects. I've experienced some finicky race conditions with the `picker:_get_prompt` before so I'll use this branch for a bit.
=> fix(picker): set `current_line` state earlier

lua/telescope/make_entry.lua
Currently, the buffer name is normalized to the `cwd` option value. This buffer name is then used as the filename, which is used as the file path for the previewer. But if the `cwd` value is not the actual cwd, the buffer path can no longer be found by the previewer (relative to the true cwd).
This is fixed by adding a `path` value to the entry that's the full path of the buffer. The previewer will then use this full path to find the file to preview.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3102
=> fix(builtin.buffers): previews with specified `cwd` option

lua/telescope/builtin/__internal.lua
This fix aims to resolve the issue about the "enable_preview" feature that wasn't working. 
Now if you call:
`:Telescope colorscheme enable_preview=true`
while scrolling through the different color scheme options, the live preview is working (change color scheme accordingly)
Fixes #2966
I tried two different scenarios:
- :Telescope colorscheme enable_preview=true --> When scrolling through the different color schemes, the theme changes accordingly
- :Telescope colorscheme enable_preview=false -->  When scrolling through the …
=> fix: enable_preview true

lua/telescope/builtin/__files.lua, lua/telescope/builtin/__git.lua, lua/telescope/builtin/__internal.lua, lua/telescope/builtin/__lsp.lua, lua/telescope/config/resolve.lua, lua/telescope/finders/async_static_finder.lua, lua/telescope/pickers.lua, lua/telescope/previewers/term_previewer.lua, lua/telescope/utils.lua, plugin/telescope.lua
Fixes #3108
Note that `islist()` checks for a specific type of table: indexed by integers without holes (so `{ 1 = 'a', 3 = 'b' }` is _not_ a list); the intention is to ensure that `ipairs` and `#` (length) are well-defined. I did not check whether that is indeed intended in each case here; if not, consider simply replacing by `type(t) == 'table'`.
On a related note, the new `flatten()` only works correctly for lists; `{1,2,nil,3}` will _not_ be flattened to `{1,2,3}`. I don't know if that is an issue here, either. **EDIT** looks like it.
**EDIT2:** will be fixed upstream.
(Long-term, I would recommend moving to the new `vim.iter` API that allows efficiently chaining iterators. But this is of course a major refactoring effort.)
=> fix: adapt to Nvim deprecations in 0.10

lua/telescope/utils.lua, plugin/telescope.lua
vim.iter.flatten() is not a full replacement (does not support arrays
with `nil`); a fix may be backported but for now only use it on nightly
(0.10 has no warnings yet).
=> fixup: adapt to deprecations in Nvim 0.10

doc/telescope.txt, lua/telescope/builtin/init.lua, lua/telescope/make_entry.lua
This adds the same options which already exist for `gen_from_lsp_symbols` to control the allocated space for symbols in `make_entry.gen_from_treesitter`.
Added options:
* `symbol_width`: controls the space for the symbol (defaults to 25)
* Neovim version (nvim --version): 0.9.5
* Operating system and version: Linux
=> Add option to customize length of symbols for make_entry.gen_from_treesitter

lua/telescope/builtin/__internal.lua
This makes the telescope spellcheck picker more equivalent with a z= command. With the implementation before the misspelt word would end up in your register. This is not the behaviour of a z= in vim or neovim
Fixes # N/A
- Spell word wrong
- Fix it
- Paste - Buffer not overwritten
* Neovim version (nvim --version): Nightly
* Operating system and version: NixOS
=> fix: black hole zequals

.github/workflows/docgen.yml
Change `pull_request` -> `pull_request_target`
This should allow forks of non-members to generate docs with the docgen workflow.
Unlike the `pull_request` event which only grants read access to `GITHUB_TOKEN`, `pull_request_target` grants read/write. This should still be safe as unlike `pull_request`, `pull_request_target` runs in the context of the base of the pull request rather than the pull request itself. So someone can't update docgen.yml to something malicious in the PR and have that docgen workflow run.
=> chore(ci): tweak docgen event

lua/telescope/builtin/__internal.lua, lua/telescope/previewers/buffer_previewer.lua, lua/telescope/previewers/utils.lua, lua/telescope/utils.lua, lua/tests/automated/utils_spec.lua
On Windows, `builtin.help_tags` picker does not show any help tags.
To fix this, the following changes are needed:
1. `util.path_tail` checks unix separator `/` on Windows and leave the original implementation intact on unix systems.
2. Line endings should be taken carefully on Windows. `vim.split` with only newline `\n` character as separator may result in unexpected crash when parsing large files. When splits on lines are needed, call it with `\r?\n`, or even set up a wrapper function in utils is more prefered.
Fixes #3126
Fixes #3126 (issue)
Please describe the tests that …
=> fix(help_tags): show help tags on windows (#3126)

lua/telescope/builtin/__diagnostics.lua, lua/telescope/make_entry.lua
Few pickers with entry makers that relied on `entry_display.create` were not properly passing the highlight table returned by `transform_path`. This made the `filename_first` `path_display` option not work as expected for these pickers.
pickers touched:
- diagnostics
- lsp_workspace_symbols & lsp_dynamic_workspace_symbols
- tags & current_buffer_tags
- git_status
closes https://github.com/nvim-telescope/telescope.nvim/issues/3106
=> fix(make_entry): improve `filename_first` support

README.md, doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/mappings.lua, lua/telescope/pickers.lua
Store the `<cWORD>`, `<cfile>` and `cursor line` of the original window before showing up telescope window, and create new action to insert/append the them into the telescope prompt buffer.
Allows for similar behaviors to c_CTRL-R_CTRL-W.
follows: #2878 
=> feat(picker): allow appending original window `<cWORD>`, `<cfile>` and `cursor line` to prompt

doc/telescope.txt, lua/telescope/builtin/__lsp.lua, lua/telescope/builtin/init.lua
follow up to https://github.com/nvim-telescope/telescope.nvim/pull/3099
> clean up `list_to_jump` to work mostly with `vim.lsp.util.locations_to_items` output from the get-go
and closes https://github.com/nvim-telescope/telescope.nvim/issues/3118
=> fix(lsp.reference): single reference direct jump

lua/telescope/builtin/__lsp.lua
Following up on my comment in #3137 regarding the broken jump to Java classes such as `java.lang.String` because the JDT URI is not a file name. With `item.filename` being `jdt://contents/java.base/java.lang/String.class...`, the call `vim.uri_from_fname(item.filename)` in `item_to_location` would convert the JDT URI into an invalid URI by adding `file://` in front of `jdt://` and encode the already encoded URI again. The jump would fail as a result.
This is an attempt to fix the issue by applying filename to URI transformation only if `item.filename` is not a URI.
Error message:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1136: Cursor position outside buffer
[C]: in function 'nvim_win_set_cursor' …
```
=> fix(lsp): handle URI in `item_to_location`

lua/telescope/builtin/__lsp.lua
fix(lsp.reference): Only filter the current line of the current filname when include_current_line=false
Lsp references with the same number of lines in different files will be filtered when include_current_line=false
- Lsp references have the same number of lines in different files (with gopls)
NVIM v0.10.0
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
MacOs (14.5)
=> fix(lsp.reference): Only filter the current line of the current filname

lua/telescope/builtin/__internal.lua
When using builtin.buffers with `select_current = true`, it is not selecting current buffer.
This is because the current implementation tries to set the `default_selection_idx` using buffer number instead of buffer index.
The solution is to set `default_selection_idx` using buffer index.
Fixes #2917
```
:lua require('telescope.builtin').buffers({ select_current = true })
```
```
NVIM v0.10.0
LuaJIT 2.1.1713484068
```
* Operating system and version: Windows 11 / WSL
=> fix(buffers): select_current not selecting current buffer index

lua/telescope/builtin/__lsp.lua
This adds notifications when no results are found for LSP references/definitions etc. Similarly to the existing notification for `lsp_document_symbols`.
I tried `lsp_references` on things that had results and things that didn't and saw the correct notification.
* Neovim version (nvim --version): 0.10.0
* Operating system and version: arch linux
=> feat(lsp): notify list_or_jump when no results

lua/telescope/utils.lua
I've cleaned up `transform_path`:
- Extracted code into functions: `path_filename_first`, `path_truncate`, etc.
- By returning early for `smart` we would not be able to run `filename_first` afterwards.
The directory can now be separated with the following configuration:
```
path_display = {
"smart",
"filename_first",
},
```
- Feature: allowing `smart` to be used in conjunction with `filename_first`
> NVIM v0.10.0
> Build type: Release
> LuaJIT 2.1.1716656478
OSX Sonoma 14.4.1
=> feat: refactors transform_path and allow `smart` to be used in conjunction with `filename_first`

developers.md
This is a small change in developers.md documentation. 
the table `results` in 
```
results = {
{ "red", "#ff0000" },
{ "green", "#00ff00" },
{ "blue", "#0000ff" },
},
```
contains the name AND the hex code. With the previous text, it seemed that the table had a "color", a "name" and the "hex code" and I found it confusing.
I understand that this is an extremely small nit picking so its up to you guys if you want to move ahead and skip this PR :)
- Just a documentation update
N/A
* Neovim version (nvim --version): NVIM v0.11.0-dev+212-gd8e384b7b
* Operating system and version: Fedora 40
=> chore(developers.md): change comma typo

lua/telescope/pickers/layout_strategies.lua
This PR fixes an issue with the flex layout by changing the default values for `flip_columns` and `flip_lines` to match the `preview_cutoff` values for the horizontal and vertical layouts. This should improve the user experience for users who have their default layout set to 'flex'. See the issue description linked below for more information.
Fixes #3138
The change implemented in this PR was tested using the following two tests:
* Neovim version (nvim --version): NVIM v0.10.0
* Operating system and version: Linux 6.8.1
=> fix(layout_strategies): odd flex layout default behavior

doc/telescope.txt, lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua
Add an option `ignore_builtins` for the builtin colorscheme picker. Can't seem to find one in the issue search, but I remember that this topic regularly came up, e.g., on reddit.  
- New feature
```lua
-- run this
require("telescope.builtin").colorscheme { ignore_builtins = true }
```
* Neovim version (nvim --version): NVIM v0.10.0
* Operating system and version: macOS 14.4.1 (arm)
=> feat(builtin.colorscheme): add option `ignore_builtins`

doc/telescope.txt, lua/telescope/actions/init.lua, lua/telescope/builtin/__internal.lua, lua/telescope/builtin/init.lua, lua/telescope/pickers.lua
Binds the `delete_buffer` action to `<C-x>` by default for the `buffers` pickers.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3128
Also enhances the `delete_buffer` action to have a "cleaner" behavior for deleting the current buffer (the buffer under telescope). Previously, when deleting the current buffer, the buffer would be removed from the buflist but closing the picker would put you right back into the buffer you just deleted.
From `:h bdelete`:
> If buffer [N] is the current buffer, another buffer will be displayed instead.  This is the most recent entry in the jump list that points into a loaded buffer.
Since the telescope prompt buffer is technically the current buffer, this "another buffer will be displayed behavior" wasn't actually triggering.
With this newest …
=> feat(builtin.buffers): enhance and bind `delete_buffer` action

lua/telescope/builtin/__internal.lua
closes https://github.com/nvim-telescope/telescope.nvim/issues/3171
=> fix(builtin.buffers): missing return in attach_mappings

lua/telescope/builtin/__files.lua
Whenever a picker, that can jump to a different location in the same buffer does so it should have `push_cursor_on_edit` otherwise the jump won't be recorded.
Maybe this affects other pickers too, but I only noticed it on grep and treesitter since I use those two a lot.
=> fix(builtin.live_grep, builtin.treesitter): not adding jumps to jumplist

lua/telescope/builtin/__lsp.lua
Adds support for respecting `file_ignore_patterns` option before any jumps are made in the following pickers utilizing the `list_or_jump` helper.
Without this, you can get a picker with only one result, so it should've jumped rather than opening the picker.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3168
=> fix(builtin.lsp): respect `file_ignore_patterns` opt for direct jumps

lua/telescope/config/resolve.lua, lua/telescope/pickers/layout_strategies.lua, lua/tests/automated/resolver_spec.lua
This PR adds a new option to layout_config called anchor_padding. When set to a positive integer, it adds 
additional lines of padding around the anchor of a layout.
Fixes #2851
- Test for anchor south and with high padding:
```lua
local telescope = require("telescope")
local vertical_config = {
config = {
vertical = { width = 0.5 },
anchor = "S",
prompt_position = "bottom",
width = { padding = 0 },
height = 0.5,
anchor_padding = 10,
},
}
telescope.setup({
pickers = {},
extensions = {},
defaults =config,
})
```
This results in the following layout:
The result we care about is the ten lines of additional space between the bottom of the screen and the start of the layout.
- Test for anchor north and with low padding:
```lua
local …
```
=> feat(layout_config) Adds the option to configure additional lines of padding around the anchor of the layout (#2851)

lua/telescope/actions/init.lua, lua/telescope/pickers.lua
Previously, when having window splits, with deleting a buffer involving deleting a window, getting the jumplist for said deleted window would result in an invalid jumplist. Trying to iterate over this invalid jumplist would error out.
When there are split, there's no need to find a valid buffer to switch the current window to (as the window is deleted). Instead, what's needed is the updating of telescope's `picker.original_win_id` state. This is important for when chaining buffer deletes (ie. closing many splits).
Also improve behavior when the "current" buffer is the only valid buffer -> it will now open an empty buffer (same as when doing `:bdelete`).
closes https://github.com/nvim-telescope/telescope.nvim/issues/3193
=> fix(action.delete_buffer): enhance behavior with splits

doc/telescope.txt, lua/telescope/builtin/init.lua
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/__files.lua#L298
It seems the default value is `false`, and unlike other options, the default value of `follow` option is not mentioned.
Documentation improvement.
=> Mention default value of `follow` option for `find_files`

lua/telescope/actions/init.lua
Cursor position stuff after closing picker should pretty much always be `vim.schedule`d.
related: https://github.com/nvim-telescope/telescope.nvim/pull/2850
closes #3217
=> fix(actions.insert_symbol): schedule to insert in correct position

lua/telescope/builtin/__files.lua
Setting `push_cursor_on_edit = true` wasn't actually doing anything as the picker replaces `select_default`.
Instead, call `normal! m'` manually in the replacement `select_default`.
=> fix(current_buffer_fuzzy_find): push cursor on edit

lua/telescope/actions/set.lua
C-o behaves unintuitively when same file is selected at diffrent position.
Jumplist is not updated when moving to different position in same file. 
When absolute paths are used in entry maker it causes `:edit` to be skipped for same file.
Check here -
https://github.com/nvim-telescope/telescope.nvim/blob/bfcc7d5c6f12209139f175e6123a7b7de6d9c18a/lua/telescope/actions/set.lua#L198
Since `:edit` is skipped, jumplist is not updated. 
This patch updates jumplist when moving to diff position in same file
- tested with
```
NVIM v0.10.0
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```
Fedora 40
=> fix(edit action): update jumlist when moving in same file

lua/telescope/builtin/__internal.lua
Without scheduling, lots of vim state will be related to the builtin picker when the new picker is opened despite closing the builtin picker first and then opening a new picker.
This impacts state like `vim.fn.mode()`. If the builtin picker was closed in insert mode, the closing action _should_ put you back in normal mode. But without scheduling, the next picker is opened before it does. So doing `vim.fn.mode()` in the subsequent picker will tell you, you're still in insert mode. Typically, when chaining pickers, you want the pre-telescope state, making the transitions between pickers seemless.
closes #3217
=> fix(builtin.builtin): schedule opening next picker

lua/telescope/previewers/init.lua, lua/telescope/previewers/term_previewer.lua
I'm trying to use [difft](https://github.com/Wilfred/difftastic/tree/master) for a custom picker and regular git diff on another. 
Using the global `set_env` for telescope becomes too aggressive, just like in `utils.job_maker` I'd like to be able to pass `env` in the same format to do this: 
```lua
previewer = prev.new_termopen_previewer({
title = "Difft preview",
env = { ['GIT_EXTERNAL_DIFF'] = '~/.local/bin/difft' },
get_command = function(entry)
local merge_base = git.git_show_merge_base()
return { "git", "diff", merge_base, entry.value }
end
})
```
Since it's a term command, being able to pass custom envs seems appropriate, the implementation is trivial and similar to what's done in `utils.job_maker`.
- This change requires …
=> Allow passing env to `new_termopen_previewer`

doc/telescope.txt, lua/telescope/previewers/init.lua
for https://github.com/nvim-telescope/telescope.nvim/pull/3224
seems like docgen still not working for non-maintainers
=> docs(previewer): term_preview `env` option

lua/telescope/builtin/__lsp.lua
Fixes https://github.com/nvim-telescope/telescope.nvim/pull/2342
Right now, when you have two LSPs connected to one buffer and you want to, let's say, go to a definition, there's a race condition / non-deterministic behavior in which Telescope uses the answer of the first LSP that responds
As an example (and the actual reason for me submitting this change), if you have a ruby application that uses sorbet, and you're running the Sorbet LSP and RubyLSP for the same buffer (which is pretty useful), what you'll see for `telescope.builtin.lsp_definitions` will be:
The first two times, it used the locations from RubyLSP, and the third one from Sorbet
With this change applied, …
=> Fetch results from multiple LSPs

lua/telescope/builtin/__internal.lua
This PR fixes a couple of issues I found with the current implementation of `builtin.colorscheme`. Currently two problems can be observed:
- The color scheme changes when searching, even when `enable_preview` is false. Shifting the selection behaves as expected however.
- Color schemes cannot be previewed by clicking with the mouse when `enable_preview` is set to true.
The code is modified to fix these issues.
1. Run `:Telescope colorscheme enable_preview=false`
2. Start searching for something
3. Note that the color scheme is not changed until the enter key is pressed
1. Run `:Telescope colorscheme enable_preview=true`
2. Use the mouse to click on one of the options
3. Observe that the color scheme is changed
4. Exit Telescope and the …
=> Fix some issues with builtin.colorscheme

lua/telescope/previewers/buffer_previewer.lua
The merged table returned from `vim.tbl_deep_extend` was not being utilized/assigned.
=> fix(buffer_previewer): save state from `opt.setup` call

lua/telescope/previewers/term_previewer.lua
The merged table return from `vim.tbl_deep_extend` was not being utilized/assigned.
Related: https://github.com/nvim-telescope/telescope.nvim/pull/3253
=> fix(term_previewer): save state from `opt.setup` call

lua/telescope/previewers/term_previewer.lua
Using `bat` would result in the command being a nested list.
eg. using `:Telescope plaents` with `bat` installed
```
{
"bat",
{ "--pager", "less -RS" },
"--style=plain",
"--color=always",
"--paging=always",
"--",
"/home/jt/projects/telescope.nvim/data/memes/planets/earth",
}
```
This would cause `vim.fn.termopen` to throw an error as the command is expected to be a flat list or string.
=> fix(term_preview): bad `bat` command generation

lua/telescope/previewers/term_previewer.lua
In some cases terminals from `new_termopen_previewer` don't close.  I think I've figured why this happens, here's some repro steps
1. Run a termopen previewer that results in more than 1 preview with terminals running interactively
2. Select (don't enter) multiple of the choices, so that the previews load, then go back to one of the previous ones
3. Close telescope without picking a choice
4. Try to quit with :wqa
Results are that nvim complains about an open buffer and won't close. 
This is only noticable on things like `less` or `git` with a pager (in my testing).
This happens because `old_bufs` wasn't properly updated in the case that a selection was bade back to a previous buffer, 
if telescope is exited at that point, the terminal connected to the last buffer won't be closed on …
=> Ensure terms close

lua/telescope/previewers/buffer_previewer.lua
Adds `--max-count=1000` flag to the `git log` command in the `git_branch_log` previewer. This prevents potential fork bombing issues with large repositories.
closes https://github.com/nvim-telescope/telescope.nvim/issues/2933
=> fix(previewers): limit git log entries to prevent fork bomb

lua/telescope/pickers.lua
ipairs won't find find all results if entry_maker happens to return nil for a line.
Fixing Pickers:delete_selection so it finds all results even if entry_maker returns nil
Fixes #3265
NVIM v0.10.1
LuaJIT 2.1.1720049189
macOS 14.6
=> fix: #3265 use pairs in Pickers:delete_selection

lua/telescope/builtin/__lsp.lua
- Added a check for empty call hierarchy items using vim.tbl_isempty.
- Fixed the return value to correctly return the chosen item from the list.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3267
=> fix(lsp): handle empty call hierarchy items

lua/telescope/builtin/__internal.lua
Bad condition led to the selection being stuck at idx = 2 until only one result is left, despite idx = 1 result being a better match.
Neither `sort_lastused` or `ignore_current_buffer` should affect the position of the selection.
Former is used simply to sort the buffer list. The latter is used to filter out the current buffer.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3262
=> fix(buffers): bad `sort_lastused` result selection

lua/telescope/builtin/__internal.lua
Reverts nvim-telescope/telescope.nvim#3289
`sort_lastused` and `ignore_current_buffer` options impacting the initial selection was intended behavior based off of fzf.vim.
https://github.com/nvim-telescope/telescope.nvim/pull/3289#issuecomment-2345252200
=> Revert "fix(buffers): bad `sort_lastused` result selection"

lua/telescope/builtin/__internal.lua
When oldfiles is configured to only show files in the current working directory and the current working directory is root, no results will be displayed because a slash is appended to a path string that already ends with a slash. The line that does this is not needed because the `buf_in_cwd` function already does this (and only adds it if needed).
1. Launch nvim from the root directory
2. Start the oldfiles picker
3. Observe that nothing will be shown
* Neovim version (nvim --version): v0.10.1
* Operating system and version: Linux 6.9.3
=> fix(builtin.oldfiles): no output when cwd is root

lua/telescope/builtin/__internal.lua
This extends the built in `help_tags` and `colorscheme` pickers to support selecting from plugins that are not yet loaded by the Lazy plugin manger as described by the developer (https://github.com/ibhagwan/fzf-lua/discussions/1296). I have fully tested this and it works great even if the user doesn't use `lazy.nvim` and is a non-breaking change.
* Neovim version (nvim --version): Nvim 0.10.1
* Operating system and version: Arch Linux, latest
=> feat(builtin): allow picking help pages and colorschemes not yet loaded by Lazy.nvim

README.md
In the readme, I think it would be nice to add human readable descriptions to the keymaps.
See: https://neovim.io/doc/user/lua.html#vim.keymap.set()
and documentation for the `desc` parameter:
https://neovim.io/doc/user/api.html#nvim_set_keymap()
This makes the output for tools like [which-key.nvim](https://github.com/folke/which-key.nvim) look nicer.
- use [which-key.nvim](https://github.com/folke/which-key.nvim) to look at the keymaps …
=> docs(README.md): Add human readable description to keymap

lua/telescope/pickers.lua
When typing fast at neovim startup on Windows, error message
```txt
E5108: Error executing lua: .../nvim-data/lazy/telescope.nvim/lua/telescope/pickers.lua:960: attempt to index field 'manager' (a boolean value)
.../nvim-data/lazy/telescope.nvim/lua/telescope/pickers.lua:960: in function 'toggle_selection'
...-data/lazy/telescope.nvim/lua/telescope/actions/init.lua:155: in function 'run_replace_or_original'
...im-data/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
```
may occur if …
=> fix(picker): check nil before calling get_entry

lua/telescope/builtin/__internal.lua
- Problems
Problem with slash and backslash being mixed up is chronic issue of neovim in Windows. it makes telescope prompt perceive same path differently when it execute to oldfiles picker.
some function like `nvim_buf_get_name()` or `vim.v.oldfiles` give paths which are mixed up with slash and backslash.
- What it did For windows, 
it always needs to change slash(/) to backslash(\) when function which deal with path because entry_maker works properly only the case that path string has \ not /.
- Effect
1) oldfiles picker doesn't show duplicated list
2) `defaults.path_display` configuration feature will works well at oldfiles pikcer
Fixes #1683
It is related with PR #3103 what i submitted but opened 
- Bug fix (non-breaking change which fixes …
=> fix(__internal) : fix slash problem in oldfiles

lua/telescope/builtin/__internal.lua, lua/telescope/make_entry.lua
The current builtin picker `vim_options` did not correctly get the current value of all options. This PR fixes that.
1. `nvim test.lua`
2. `:Telescope vim_options`
3. Search for `'filetype`
Result before change: 
Result after change:
* Neovim version (nvim --version): NVIM v0.11.0-dev-611+g615f7bbff
* Operating system and version: Windows 11
=> fix(builtin.vim_options): fix getting current option values

lua/telescope/pickers.lua, lua/tests/automated/pickers/live_grep_spec.lua, lua/tests/fixtures/live_grep/a.txt
With `sorting_strategy='ascending'`, the results buffer should never have lines beyond the `max_results` count OR the number of available results, whichever is smaller.
closes #3282
=> fix(pickers): sorting_strategy=asc stale result clearing

doc/telescope.txt, lua/telescope/make_entry.lua
The current tags picker will not show the kind
Current tags picker: 
With this changes the picker will show the kind (`method`, `field`, `package`, `class` , etc): 
It augments the regex match in the existing picker to get the `extensions_fields` that may be present on each line of the `tags` file (see [TAG FILE FORMAT](https://docs.ctags.io/en/latest/man/ctags.1.html#tag-file-format)).
That `extension_fields` may contain a `kind:xxx` field, if it does it will be picked up and added to the entry otherwise the `unknownkind` will be used.
To generate a `tags` file that includes kinds use 
```
git ls-files .  |  $(brew --prefix universal-ctags)/bin/ctags --fields=+zK -L - -f tags
```
where the `--fields=+zK` is the part that adds the kinds. 
Fixes #3233
Please delete options that are not …
=> Add kind to builtin.tags picker

lua/telescope/previewers/buffer_previewer.lua
Fixes a bug in the builtin highlights picker where the selected highlight won't be displayed in the previewer if the selected highlight is a suffix of another highlight and that other highlight occurs first in the list of highlights. For example, having `Comment` selected in the picker shows `SpecialComment` in the previewer. Another example is 'Cursor'/'TermCursor'
The fix is trivial, just match at the start of the line (in addition to requiring a space after)
NVIM v0.10.1 …
=> fix(highlights): preview may (rarely) show wrong highlight

lua/telescope/utils.lua
In Nvim 0.11, `vim.treesitter.language.add()` returns `true` on success or `nil,errmsg` on failure instead of throwing an error. This allows using `add()` directly as a check for available treesitter parsers.
See https://github.com/neovim/neovim/pull/30379
=> fix(treesitter): adapt to upstream change

lua/telescope/builtin/__files.lua
When using the vim command API and passing a number to the `search` option of `grep_string` (eg. `:Telescope grep_string search=3`), the number is passed as a number. This eventually causes a type error at `string.gsub` as the `search` value is expected to be a string.
We'll just cast `search` value to a string.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3310
=> fix(grep_string): cast `search` value to string

lua/telescope/builtin/__git.lua, lua/telescope/make_entry.lua
The previous implementation of `self.manager:num_results()` could return 0 despite having results due to suspected async/event loop issues (#3316). This change counts valid entries manually to ensure accurate result count.
closes #3316
=> fix(git_status): correctly count result on_complete

lua/telescope/builtin/__lsp.lua
Switch the following pickers to use the native neovim lsp handler functions using the `on_list` option:
- `references` -> `vim.lsp.buf.references`
- `definitions` -> `vim.lsp.buf.definition`
- `type_definitions` -> `vim.lsp.buf.type_definition`
- `implementations` -> `vim.lsp.buf.implementation`
This offloads the request and response handling off the neovim. 
This also let's responses pass through any custom handlers registered via `vim.lsp.handlers` (currently not functional on neovim nightly).
This only affects users on neovim 0.11+. The `on_list` option was introduced in nvim 0.10 but only recently in 0.11, has neovim's `vim.lsp.buf.*` functions added improved support for responses from multiple language servers.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3336
=> feat(lsp): use native lsp handlers for some pickers

lua/telescope/builtin/__lsp.lua
Adapt to the upstream change https://github.com/neovim/neovim/commit/629483e24eed3f2c07e55e0540c553361e0345a2 to get rid of the warning message "warning: offset_encoding is required, using the offset_encoding from the first client".
Since the commit https://github.com/neovim/neovim/commit/2dcbfe78fcec5f73ce061bb24b718187b9c6b134, `params` in `buf_request` can accept a function that takes the client as a parameter. So instead of sending the same params to all servers, the params with correct offset_encoding will send to each single server.
=> fix: offset_encoding is required now in `make_position_params`

lua/telescope/previewers/buffer_previewer.lua
When picking buffers, when filtering, if there is one left, I have my telescope configured to pick the last remaining entry automatically:
```lua
pickers = {
-- Default configuration for builtin pickers goes here:
-- picker_name = {
--   picker_config_key = value,
--   ...
-- }
-- Now the picker_config_key will be applied every time you call this
-- builtin picker
find_files = {
--theme = "ivy"
hidden = true,
},
buffers = {
--theme = 'ivy',
on_complete = {
function(picker)
local index = 0
for _ in picker.manager:iter() do
index = index + 1
if index > 1 then
break
end
end
if index == 1 then
local bufno = tonumber(picker.prompt_bufnr)
local to_call = require('telescope.actions').select_default
local _ = pcall(to_call, bufno)
end
end
}
},
},
```
see full setup …
=>  Check for nil where nil was giving me problems

lua/telescope/utils.lua
Previously, filter_symbols returned nil in certain cases, which could lead to unexpected behavior. This change ensures that an empty table is always returned, maintaining consistency.
closes https://github.com/nvim-telescope/telescope.nvim/issues/3380
=> fix(utils): `filter_symbols` return table consistently

lua/telescope/builtin/__git.lua
Fixes # (https://github.com/nvim-telescope/telescope.nvim/issues/3414)
1. create git repo, commit all, make pwd clean.
```sh
git init && git add --all && git commit --message=add
```
2. `nvim -nu minimal.lua`
3. use command to open git_status picker.
```vim
Telescope git_status
```
Expect behavier:
1. Send a `INFO` message.
2. Remain picker panel open.
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
vim.fn.system …
```
=> fix(git_status): keep picker open if pwd is clean

lua/telescope/builtin/__lsp.lua
neovim/neovim#30860 introduced the `position_encoding` parameter in `symbols_to_items()`. This breaks `:Telescope lsp_document_symbols`, `lsp_workspace_symbols`, and `lsp_dynamic_workspace_symbols` for anyone running nightly Neovim.
EDIT: draft status removed. Should be a bug-fix only now.
Manual testing of the `Telescope` commands above.
NVIM v0.11.0-nightly+4a2a54f
macOS 15.3.1
=> fix(lsp): add position encoding when calling `symbols_to_items()`'

lua/telescope/builtin/__lsp.lua
Detailed description and repro in #3432. When `telescope.builtin.lsp.definitions()` is invoked and the target is an empty file, invalid (negative) position values are supplied to nvim's `vim.lsp.util.show_document()` function resulting in an error. This change clamps the `line` and `character` values to a minimum of 0. 
Fixes #3432
- I wasn't sure how else to test this, but would be happy to spend some more time on this if anyone has some ideas :).
NVIM v0.11.0-dev-2016+gf5714994bc
LuaJIT …
=> fix(lsp): don't return negative values from `item_to_location`

lua/telescope/builtin/__lsp.lua
Function `client.supports_method` was deprecated in v0.11 and replaced with `client:supports_method`. This commit starts using `client:supports_method` for newer version of Neovim, and keeps the deprecated `client.supports_method` for older versions
Fixes #3467 
I went through the same process as I described in issue #3467 but using a Telescope version with my patch applied
* Neovim version (nvim --version): v0.12.0-dev-292+g03d378fda6
* Operating system and version: Arch Linux
=> fix(lsp): stop using deprecated `client.supports_method` function
