README.md

popup.vim is a required dependency.

Add popup.vim as a dependency in installation

---

lua/telescope/pickers.lua

This adds a common interface with insert and normal mode.

Add arrow key mappings for insert and normal mode.

---

lua/telescope/actions.lua
lua/telescope/builtin.lua
lua/telescope/make_entry.lua

@Conni2461 Hey, can you check out this PR?
I actually was playing around w/ buffers this morning.
Can you tell me what you think of this?

feat: add buffers

---

lua/telescope/builtin.lua
lua/telescope/make_entry.lua
lua/telescope/previewers.lua

adds a treesitter builtin to search treesitter nodes in the locals query file

added treesitter builtin

---

lua/telescope/pickers.lua

Rounded corners for the window borders

---

README.md
lua/telescope/builtin.lua

feat: Add support for ripgrep in "find_files" builtin

---

lua/telescope/previewers.lua

Fixes #89.
I'm not sure about this fix. Please tell me if something else should be done instead.

fix: Add nil checks for state when preview hasn't been initialized yet

---

lua/telescope/pickers/layout_strategies.lua
lua/telescope/themes.lua

This is to fix some of the default layout so it looks better with borders.

fix: Resolve many display issues with the dropdown theme

---

lua/telescope/pickers.lua

Set your highlight `TelescopeBorder` to change the color.

feat: Add TelescopeBorder Highlight

---

lua/telescope/pickers/layout_strategies.lua

Made the prompt 1 tall instead.

fix: Tighten up prompt on dropdown theme

---

lua/telescope/actions.lua

run filetypedetect on edit

---

lua/telescope/actions.lua
lua/telescope/builtin.lua
lua/telescope/config.lua
lua/telescope/debounce.lua
lua/telescope/entry_manager.lua
lua/telescope/finders.lua
lua/telescope/init.lua
lua/telescope/log.lua
lua/telescope/pickers.lua
lua/telescope/pickers/layout_strategies.lua
lua/telescope/sorters.lua
lua/tests/automated/find_and_sort_spec.lua
lua/tests/automated/telescope_spec.lua
lua/tests/manual/auto_picker.lua
lua/tests/manual/large_search.lua
lua/tests/manual/slow_oneshot.lua
plugin/telescope.vim
scratch/how_long_does_time_take.lua
scratch/new_index.lua
scratch/old_perf_debug
scratch/simple_rg.lua
scratch/slow_proc.sh
scratch/temp_goals.txt

WIP for multi select.
Didn't want to merge yet because I haven't been able to test the changes much yet.

[WIP]: Multi Select

---

lua/telescope/builtin.lua
lua/telescope/make_entry.lua

messed up the previous PR.
here's a clean version.

feat: builtin - lua package reloader

---

lua/telescope/builtin.lua
lua/telescope/make_entry.lua
lua/telescope/previewers.lua

feat: Manpages finder (output of apropos)

---

lua/telescope/pickers/layout_strategies.lua

Reverts nvim-lua/telescope.nvim#157
I made a mistake as this old code should work.

Revert "fix picking height as width"

---

lua/telescope/builtin.lua
plugin/telescope.vim

Add Colorscheme and Marks Support and Telescope Commands

---

README.md
lua/telescope/builtin.lua
lua/telescope/config.lua
lua/telescope/pickers.lua
plugin/telescope.vim

Refactoring `prompt` to `prompt_title` which is consistent with `results_title` and `previewer_title` and `prompt_prefix` to `prompt_text`

refactor: prompt->prompt_title ; prompt_prefix->prompt_text

---

README.md
plugin/telescope.vim

@tjdevries  now the usage like `Telescope find_files`. `Telescope grep_string`, If want change some options, like this 
`Telescope find_files prompt_prefix=ssss` .
current can't get theme option in viml, so does not support add theme option in command .

rewrite command of telescope

---

lua/telescope/builtin.lua
lua/telescope/make_entry.lua
lua/telescope/pickers.lua
lua/telescope/pickers/entry_display.lua
lua/telescope/utils.lua

WIP: options menu

---

README.md
lua/telescope/builtin.lua

Adding an additional buitlin for search keymaps.

Add built-in to search keymaps

---

lua/telescope/actions/init.lua
lua/telescope/actions/mt.lua
lua/telescope/builtin.lua
lua/telescope/pickers.lua
lua/telescope/state.lua
lua/tests/automated/action_spec.lua

@Conni2461 Does this work for you?
If so, I will merge.
Probably will merge later today after  a bit more testing either way :)

feat: Allow overriding actions from mappings

---

lua/telescope/previewers.lua

Continuation of #230.
I don't use previews, which explains why I didn't include this in the original PR.

[RFC] Fix help_tags previewer

---

lua/telescope/actions/init.lua
lua/telescope/builtin/git.lua
lua/telescope/builtin/init.lua
lua/telescope/make_entry.lua
lua/telescope/previewers.lua

Close #49
Just putting this up here, so that people can i see that i am working on this.
Command that will be here:
- `commits`: with diff preview and checkout action
- `bcommits`: for current buffer with diff preview and checkout action
- `buffers`: with log preview(not sure about this) and checkout branch
- `git_status`: with diff preview and add on action (maybe multiselection would be great for this)
Should work, so please give it a try and report back :)

git builtins

---

README.md
lua/telescope/builtin/init.lua

Update attach_mappings to use new api

---

lua/telescope/builtin/git.lua

We should check if opts.cwd is a git directory, not opts

check opts.cwd if it's a git directory, not opts

---

README.md
lua/telescope/builtin/init.lua

https://github.com/nvim-telescope/telescope.nvim/issues/255#issuecomment-729303825 can be deleted or hidden when this PR is merged.
@tamago324 please test it out and report back thanks :)

Add filetypes builtin

---

README.md

I noticed that the builtin table seems broken so I fixed it. I also added period to every items because I saw some items have it but some others don't and it triggers me :p

docs: fix builtin table formatting

---

.github/ISSUE_TEMPLATE/bug_report.md

I *assume* this is what the intention here is? I.e. to say to use the test.vim as the config.
I don't think `-N` does anything either, but let me know if I'm wrong.

Fix the bug report template to suggest -u

---

README.md
lua/telescope/builtin/init.lua
lua/telescope/builtin/lsp.lua

https://github.com/neovim/neovim/pull/12962

feat: add lsp range code actions

---

lua/telescope/previewers.lua

Followup less fixes for previewer

---

lua/telescope/builtin/init.lua
lua/telescope/builtin/internal.lua
lua/telescope/make_entry.lua
lua/telescope/previewers.lua

new builtin - autocommands

---

lua/telescope/builtin/internal.lua

This will allow for customization.
Thank you!

fix: pass the options to pickers

---

lua/telescope/pickers.lua

Fix file_ingore_patterns for tags and lsp

---

.github/workflows/ci.yml
Makefile
lua/tests/automated/action_spec.lua
lua/tests/automated/resolver_spec.lua
lua/tests/automated/telescope_spec.lua

It actually runs: https://github.com/Conni2461/telescope.nvim/actions/runs/409082452

Add test ci

---

.github/workflows/ci.yml

ci fix: don't cache git repos

---

lua/telescope/previewers.lua

Fix #323
I was reading though your report on gitter @p00f. Does this fix your issue? 
Also thanks for reporting.
Also @tami5 you could have told me that fennel is broken. I would have fixed this immediately 😆

Fix filetype guesser. At least for fennel

---

README.md

- Add back prior intro line
- Add What is Telescope? 
_(saw multiple people read the intro line, then it has a image, then there is a block of text about what it does. This directs it before the image.)_
- Add Theme image to encourage people to play with their layouts more. 
- Added all the sections to the ToC and renamed some of the built in redundancies 
_(We can be more specific of external commands instead of saying everything is builtin.)_

Lots of README changes

---

lua/telescope/make_entry.lua

This is a small tidyup to make the finder more usable for me.
Just noticed that there's another quickfix branch active; If this is already taken care of, feel free to close.

change quickfix make_entry to use column displayer

---

lua/telescope/previewers.lua

This pr should fix preview scrolling issue when using less 😄.

Fix preview scrolling

---

lua/telescope/path.lua
lua/telescope/previewers.lua

requires: https://github.com/nvim-lua/plenary.nvim/pull/29

Use plenary.filetype.detect and remove own filetype detect

---

lua/telescope/builtin/internal.lua
lua/telescope/previewers.lua
plugin/telescope.vim

I didn't break it this time :)
Lets no longer use quickfix to generate the entries because we no longer have lnum and col
CC @cempassi

Fix builtin.builtin again.

---

lua/telescope/pickers.lua

fixes https://github.com/nvim-telescope/telescope.nvim/issues/311

fix results count padding

---

lua/telescope/pickers.lua
lua/telescope/pickers/highlights.lua
scratch/digia_init.vim

Related: #190
Closes: #233
Closes: #335
Could use a bit of other people testing as well, but should work. Does add a bit of performance overhead but it's very small. It only calls sorting on one extra item, and displaying on one extra item... so.... that's like nothing :)

fix: Better highlights

---

lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/init.lua
lua/telescope/previewers/previewer.lua
lua/telescope/previewers/term_previewer.lua
lua/telescope/previewers/utils.lua

Need to test with `bat`/`cat` to make sure i did not mess up something.
New structure:
```
previewers
├── buffer_previewer.lua
├── init.lua
├── previewer.lua
├── term_previewer.lua
└── utils.lua
```

Refactor previewers

---

lua/telescope/builtin/lsp.lua
lua/telescope/make_entry.lua

added colours for git hashes in relevant finders and converted it to use displayer.
more work on LSP/TS colors.
Restoration of filename for workspace finder and addition of inline symbol preview for document view (as filename is not useful).

More colours

---

lua/telescope/builtin/internal.lua
lua/telescope/make_entry.lua
lua/telescope/pickers/entry_display.lua
plugin/telescope.vim

~~Will remove the filename fix asap~~
CC @sunjon

Displayer hl_chars and TelescopeResults hlgroups

---

lua/telescope/builtin/lsp.lua

Checks supported capabilities before issuing any unnecessary LSP requests.

LSP check capabilities

---

lua/telescope/actions/init.lua

Fixes the bug I introduced with #289. I tested normal, insert mapping for regular staging, move and conflicted.

fix: normal mode toggle issue

---

lua/telescope/builtin/files.lua

(Allows including hidden files in file findin'.)

Add hidden to find_files file findin'.

---

lua/telescope/pickers/scroller.lua

Fix bug in scroller.create.

---

lua/telescope/previewers/utils.lua

Fix has ts

---

lua/telescope/builtin/files.lua
lua/telescope/make_entry.lua
lua/telescope/previewers/buffer_previewer.lua

Hasktags fix

---

lua/telescope/make_entry.lua
lua/telescope/previewers/term_previewer.lua

Fix powershell issue

---

data/options/options.lua
lua/telescope/actions/init.lua
lua/telescope/make_entry.lua

The options finder was broken for an unknown amout of time.
This fixes it and improves the styling.

Fix missing global

---

lua/telescope/builtin/files.lua
lua/telescope/finders.lua

fix: live_grep will now accept cwd

---

lua/telescope/builtin/git.lua
lua/telescope/make_entry.lua
plugin/telescope.vim

I would like to add colors to builtin.git_status results. 
I made a basic implementation from what is already existing. Is there any improvements i can make?

Add colors to builtin.git_status results

---

lua/telescope/previewers/term_previewer.lua

Use "dir" to list the content of directories in Windows

fix: directory handle in windows

---

lua/telescope/builtin/internal.lua

Make devicons visible for `oldfiles`

Use the same maker as other file pickers

---

README.md
lua/telescope/builtin/init.lua
lua/telescope/builtin/internal.lua

Spell suggestions picker as requested on Gitter

Spell suggestions

---

README.md
lua/telescope/command.lua
plugin/telescope.vim

Now support config telescope theme from command line.

refactor telescope command

---

plugin/telescope.vim

check the extensions table is empty

---

lua/telescope/make_entry.lua

@clason 
```lua
map_tele('<space>gw', 'grep_string', {
short_path = true,
word_match = '-w',
only_sort_text = true
})
```
Use `only_search_text` for `grep_string` and it should do what you want. Plz ignore highlighting, as that is something for another day.

feat: only_sort_text

---

lua/telescope/builtin/git.lua
lua/telescope/builtin/internal.lua
lua/telescope/pickers/_test.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/term_previewer.lua
lua/telescope/utils.lua

feat: show git log for remote branches

---

lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/term_previewer.lua

fix: preview for unnamed buffers

---

lua/telescope/command.lua

support convert custom command arg

---

lua/telescope/builtin/git.lua
lua/telescope/utils.lua

I need to be able to list files in git submodules, and probably this would be useful for someone else.
Please note that:
- this is my first lua code ever
- I also changed the default to `show_untracked` to `false`. Was it a mistake? If it was intended (but seems counterintuitive to me) I will switch it back

Allow to list files in git submodules

---

lua/telescope/command.lua

improve convert_user_opts function readable

---

README.md
lua/telescope/config.lua
lua/telescope/pickers.lua

Add option to set initial_mode

---

lua/telescope/sorters.lua

Moved the substring matcher from frecency upstream.
I find it useful for some of the other finders too

Substring matcher

---

lua/telescope/path.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/term_previewer.lua

Better error message for too many open files

---

lua/telescope/builtin/files.lua

closes #440
adds search_dirs and vimgrep_arguments opts.

support multiple dirs (grep)

---

lua/telescope/previewers/buffer_previewer.lua

~~Currently requires https://github.com/nvim-lua/plenary.nvim/pull/45~~
Also fix attempt to index field state
Also related issue #410
CC @timbedard

feat: add vim buffer directory viewer. Using plenary ls

---

lua/telescope/builtin/internal.lua

When `helplang` is set, it searches `tags-XX` and takes priority to them over `@en` entries.

Preview translated help

---

README.md
lua/telescope/actions/init.lua
lua/telescope/builtin/files.lua
lua/telescope/builtin/git.lua
lua/telescope/builtin/internal.lua
lua/telescope/builtin/lsp.lua
lua/telescope/config.lua
lua/telescope/mappings.lua

add actions.select

---

README.md

Improves documentation by fixing spelling mistake

---

lua/telescope/previewers/utils.lua

fix: no TS highlight if it gets loaded after Telescope

---

lua/telescope/command.lua
lua/telescope/utils.lua
plugin/telescope.vim

try to close #447  cc @Conni2461

support custom table type keyword

---

README.md

Hope this is useful and thanks for this amazing plugin!

Add new community extension: asynctasks

---

lua/telescope/previewers/term_previewer.lua

close #488  @kristijanhusak can you test this patch ? If works fine. I will merge.
cc @Conni2461

remove bat env theme variable

---

README.md
lua/telescope/pickers.lua

Add user autocmd Telescope that do it before create Telescope window
cc @Conni2461

Add user autocmd TelescopeFindPre

---

lua/telescope/actions/init.lua
lua/telescope/builtin/git.lua
lua/telescope/make_entry.lua
lua/telescope/pickers.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/utils.lua
lua/telescope/utils.lua

Fix https://github.com/nvim-telescope/telescope.nvim/issues/516
Please don't be mad if i don't merge that today :) I am planing to go to sleep soon. But would be great if you can test it and report back if some things don't work. I already found issues i haven't considered in my previous attempt to fix that so i might have missed to pass in one cwd :) I am currently not sure about it tho :rofl: 
CC @mroavi

fix: all git builtin respect cwd now

---

lua/telescope/builtin/files.lua

This will add possibility to follow symlinks
Closes #394

feat: add 'follow' opt to find_files

---

README.md

Thanks for the cool plugin!
I've created a picker for ROS and ROS2 workspace packages. Maybe someone finds it useful.

Update Extensions README section

---

README.md

#539 has an unfortunate typo...

[Readme] typo in extension section

---

README.md
developers.md
lua/telescope/actions/init.lua
lua/telescope/builtin/files.lua
lua/telescope/builtin/git.lua
lua/telescope/builtin/init.lua
lua/telescope/config.lua
lua/telescope/pickers.lua

File browser. Currently navigating works. We need a redraw as suggested in #276 to remove the flickering.
Edit: For anyone interesed. `Picker:refresh` is done https://streamable.com/v79mjb
Edit 2: Requires https://github.com/nvim-lua/plenary.nvim/pull/59
Edit 3: I think i wanna do some other things in that PR as well 🤔 
CC @rafcamlet

Add file browser

---

lua/telescope/actions/init.lua
lua/telescope/actions/set.lua
lua/telescope/mappings.lua
lua/telescope/pickers/scroller.lua
lua/tests/automated/scroller_spec.lua

Close #466
Ref #403
Works only for the current screen because we can not yet scroll through all results.
Sorry it take me that long
CC @hoob3rt

Advanced normal mode

---

lua/telescope/actions/init.lua
lua/telescope/mappings.lua
lua/telescope/pickers/scroller.lua
lua/tests/automated/scroller_spec.lua

continuing https://github.com/nvim-telescope/telescope.nvim/pull/463
Adds `M` mapping in normal mode for consistency with `H` and `L` mappings

feat: adds M mapping in normal mode

---

lua/telescope/actions/init.lua
lua/telescope/actions/set.lua
lua/telescope/pickers/scroller.lua
lua/tests/automated/scroller_spec.lua

#545 https://github.com/nvim-telescope/telescope.nvim/issues/545#issuecomment-784914549
cc @Conni2461 
edit: forgot to test it locally before pushing it :laughing: I'll fix the failing test in a moment

fix: scroll misbehaving + fixed jump to middle

---

doc/telescope.txt
lua/telescope/actions/init.lua
lua/telescope/mappings.lua
lua/telescope/pickers.lua
lua/telescope/pickers/highlights.lua
lua/telescope/pickers/multi.lua
lua/telescope/pickers/scroller.lua
lua/tests/automated/pickers/scrolling_spec.lua
lua/tests/automated/scroller_spec.lua
scripts/gendocs.lua

OK, I think I've fixed highlighting bugs, written code better and made the selection keep track of the order you saved them.

fix: Hopefully get multi selection working correctly

---

README.md

Little thing I noticed while reading :)

Fix formatting in README to show keybinding

---

lua/telescope/builtin/git.lua

feat(git): delete bindings in the action_mappings

---

lua/telescope/builtin/git.lua

Will merge in 5
Edit: Current branch will always be on index 1. And has the `*` in front of it. You can also search for it with `*`
CC @ThePrimeagen

feat: better display for git_branches

---

lua/telescope/make_entry.lua
lua/telescope/utils.lua

Moved transform_devicons & get_devicons from make_entry.lua to utils.lua

---

lua/telescope/command.lua
plugin/telescope.vim

close #581 cc @Conni2461  @sunjon @singlexyz @elianiva

Enhance Telescope command

---

lua/telescope/utils.lua

Make sure devicons are loaded

---

lua/telescope/builtin/internal.lua
lua/telescope/builtin/lsp.lua

remove gotos because we don't need to use them

---

.github/workflows/docgen.yml
CONTRIBUTING.md
doc/telescope.txt
lua/telescope/builtin/init.lua
lua/telescope/config.lua
lua/telescope/init.lua
lua/telescope/pickers/layout_strategies.lua
lua/telescope/previewers/init.lua
scripts/gendocs.lua

Because tbh nobody knows how they work not even I remember.
I don't like that i need to manually make sure that each line has the correct length. I will provide a pr for tree-sitter-lua docgen that makes sure that max line length is 80.
Edit: Tami will review this :D
Edit 2: I will only document 15 functions, because of the max query bug. After that one is sorted out i am happy to document the rest of the file.

document previewers

---

README.md
lua/telescope/builtin/init.lua
lua/telescope/builtin/lsp.lua

checkout [this](https://github.com/nvim-telescope/telescope.nvim/issues/629) issue for more info

feat: lsp definitions

---

lua/telescope/actions/init.lua

close #634 
I didn't bind them because I've no idea what is the *good* default mapping, I personally use `<C-q>` and `<A-q>` for `smart_send` and `smart_add` respectively.
cc @Conni2461 @timsofteng

feat: add `add_to_qflist`, `add_selected`, and `smart_add`

---

lua/telescope/builtin/internal.lua

See https://github.com/neovim/neovim/pull/13875 for details.
Yes, this is commented code - but person uncommenting it will surely be sad for itt not to work.

Prefer vim.api over vim.fn

---

lua/telescope/actions/init.lua
lua/telescope/builtin/internal.lua

closes #646 #649
cc @Conni2461 am I missing something?

feat & fix: Command History Picker

---

doc/telescope.txt
lua/telescope/actions/init.lua

fix: related to #13 telescope-project, enter insert mode on prompt close

---

lua/telescope/builtin/files.lua
lua/telescope/builtin/git.lua

Fix prompt titles. Closes #OCD. 😁

Fix prompt titles

---

lua/telescope/builtin/lsp.lua

Fixes issue #707
Fixes issue where lsp_workspace_symbols stops if there are no results
from LSP client with id 1. This is an issue if you have multiple
clients, and only one of them returns results.

Fix #707: lsp_workspace_symbols add support for multiple clients.

---

lua/telescope/actions/init.lua

Very tiny PR that fixes input message when git rebasing branches. 😅 
I was wondering if I should try to also add current branch info like`... rebase master into feat-branch` but was afraid to make it too large for an input message.

Fix git rebase input message

---

README.md

Just wanted to fix a couple of small typos, grammar errors, and broken links I've noticed in the README 😃

Fixed broken links and spelling errors in readme

---

lua/telescope/builtin/internal.lua
lua/telescope/make_entry.lua

Enhance builtin commands picker to display rich information.

feat: enhance builtin commands

---

lua/telescope/builtin/init.lua
lua/telescope/builtin/lsp.lua

feat: Implement lsp.implementations similar to lsp.definitions

---

doc/telescope.txt
lua/telescope/builtin/git.lua

fix checking for git dir in a bare repo

---

lua/telescope/actions/init.lua
lua/telescope/builtin/git.lua

Sorry, there's a typo in https://github.com/nvim-telescope/telescope.nvim/pull/798
git-branches not works
fix: https://github.com/nvim-telescope/telescope.nvim/pull/798

fix: rename `actions.git_switch` to `git_switch_branch`

---

doc/telescope.txt
lua/telescope/actions/init.lua

Add documentation for quickfix actions

---

doc/telescope.txt
lua/telescope/actions/init.lua
lua/telescope/mappings.lua

Pretty simple all in all. Tested and appears to work.
I'm not sure about the mappings, though; I overwrote the `complete_tag` insert mode mapping. Please advise :)

Send to loclist

---

doc/telescope.txt
lua/telescope/builtin/files.lua
lua/telescope/builtin/init.lua

Prefiltering for treesitter picker for completeness :)

feat: add prefiltering to treesitter picker

---

lua/telescope/builtin/git.lua

fix: correctly check output of git worktree command

---

lua/telescope/builtin/files.lua

Closes  https://github.com/nvim-telescope/telescope.nvim/issues/881

Fix search_dirs in builtin grep_search

---

lua/telescope/builtin/files.lua

This at least fixes things for linux.
I don't know whats wrong with mac.
See https://github.com/nvim-telescope/telescope.nvim/issues/907

fix: ripgrep 13

---

doc/telescope.txt
lua/telescope/actions/init.lua
lua/telescope/builtin/git.lua
lua/telescope/builtin/init.lua
lua/telescope/config.lua
lua/telescope/make_entry.lua
lua/telescope/pickers.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/init.lua
lua/telescope/previewers/previewer.lua
lua/telescope/previewers/term_previewer.lua

Closes #307
Closes #627
Look at it here: https://streamable.com/sxi8fz
Continuation of #314
Edit: would be cool if we could somehow show the context of the previewer. Idk how we would do this.

Cycle previewers with git commit and bcommit already using it

---

README.md

Fixed a few typos / expressions and cleaned up inconsistencies (due to different contributors).

docs: Normalize README, fix typos

---

doc/telescope.txt
lua/telescope/actions/init.lua

fix: pasting multiline register content

---

doc/telescope_changelog.txt
lua/telescope/utils.lua

chore: changelog for 473

---

doc/telescope.txt
lua/telescope/builtin/init.lua
lua/telescope/builtin/internal.lua

Preview the selected theme, applies it on <cr> or restore original theme
automatically.

feat: enable to preview themes

---

lua/telescope/previewers/buffer_previewer.lua

This got swept under the rug from closing #965 and turning it into a telescope extension :sweat_smile:

fix: error from hopping faster than buffer preview

---

doc/telescope.txt
lua/telescope/builtin/init.lua
lua/telescope/builtin/internal.lua

Close #791
Finish it tomorrow. Its sunday and i wanna eat my well deserved black pepper ramen.
I am missing docs

feat: buffers opts.sort_mru

---

lua/telescope/previewers/utils.lua

I dont like this fix that much tbh
Close #1033

fix: unknown filetype bug

---

doc/telescope.txt
lua/telescope/builtin/init.lua
lua/telescope/builtin/lsp.lua

feat: add option jump_type to lsp_definitions and lsp_implementations

---

lua/telescope/command.lua

Fix issue from [this](https://github.com/nvim-telescope/telescope.nvim/pull/1075#issuecomment-901371701) comment.
@gizmo385 could you let me know if this fixes the issue on your end?

fix(command parser): discard invalid lua expressions

---

lua/telescope/command.lua
lua/tests/automated/command_spec.lua

Yet another fix for the command parser 😅 
Fixes [this comment](https://github.com/nvim-telescope/telescope.nvim/pull/1128#issuecomment-902682662)
@jonathannerat could you have a look/test this to make sure it works on your machine?

fix(command_parser): pcall for the loadstring

---

lua/telescope/builtin/files.lua

refactor(pickers): remove additional fileopen

---

lua/telescope/builtin/git.lua

Closes: #1170
I didn't finish all of them yet because I didn't have time this morning, but this should make the one mentioned in the issue fast

fix: Should not block on git commands

---

lua/telescope/pickers.lua

`initial_mode=normal` currently has two side effects:
- `default_text` is not set, because `vim.api.nvim_feedkeys` is slower than needed (or from `initial_mode=insert` perspective, `vim.cmd[[startinsert!]]` was faster)  essentially. 
- the cursor is not at the right position: as is, the prompt is empty and the cursor is on the first offset, whereas with this PR, the prefix is shown and cursor in normal mode at first valid text position
I didn't want to meddle with `picker:set_prompt` as is, but of course the fix could be also implemented there.
Fixes last glitches before #1051 should be fine to be merged, but of course happy to get more testers/feedback on that PR :sweat_smile: .

fix: initial normal mode

---

lua/telescope/previewers/buffer_previewer.lua

closes #1193 
@akinsho does this fix the issue for you? :)

fix: string `display` for builtin.pickers

---

lua/telescope/make_entry.lua

fix https://github.com/nvim-telescope/telescope.nvim/issues/1126
Comparing absolute path vs relative path in action/set.lua caused :edit to run anyway. So `:set hidden` didnt fix it. So we do something similar to files where we get the absolute path on `<cr>` with `.path`. But we should only do this once so metatable.
@ViViDboarder can you confirm that fixes the issue? Thanks

fix: jump to tag if buffer has unsaved changes

---

doc/telescope.txt
lua/telescope/actions/init.lua
lua/telescope/builtin/git.lua
lua/telescope/builtin/init.lua

Hi! I noticed having to leave vim to merge branches, so I added the merge branch action to the git actions :)
Also added a default mapping `C-m` in `git.branches`.

feat: git merge branch action

---

autoload/health/telescope.vim
lua/telescope/_extensions/init.lua
lua/telescope/health.lua

PR to add some health checks to sanity check common user issues.

feat: checkhealth

---

lua/telescope/actions/init.lua

Should close #1218
@benfrain -- could you please a) test this and b) give me confirmation this should not make anything worse (I cannot think of anything)? 
I'm not really a quickfix user yet (though I admittedly should acquire some mastery ;).

fix: make qf commands possible from any picker

---

doc/telescope.txt
lua/telescope/builtin/git.lua
lua/telescope/builtin/init.lua

Wanted to add the support for using \<pattern\> for [git-for-each-ref](https://git-scm.com/docs/git-for-each-ref)

feat: support <pattern> for git-for-each-ref

---

lua/telescope/pickers/layout_strategies.lua

Adjustment of positioning indexing for after [this plenary PR](https://github.com/nvim-lua/plenary.nvim/pull/227) is merged.

fix: adjust layout positioning for new indexing

---

doc/telescope.txt
lua/telescope/config.lua
lua/telescope/utils.lua

followup to #1254 and implementation of[@Conni2461's idea](https://github.com/nvim-telescope/telescope.nvim/pull/1254#issuecomment-922527270)

feat(defaults) :enable customization of path_display.truncate

---

lua/telescope/make_entry.lua
lua/telescope/previewers/buffer_previewer.lua

fix: tags now also support suppercollider tags

---

lua/telescope/builtin/internal.lua

fix: print error mesage and dont close telescope if nothing is selected

---

autoload/health/telescope.vim
lua/telescope/health.lua

New healthcheck pattern in master requires the renaming of the function :) https://github.com/neovim/neovim/pull/15259 this of course keeps compatibility with current stable 0.5.1

feat(healthcheck): migrate to new lua pattern

---

lua/telescope/pickers.lua

Resolves #1389
@FollieHiyuki does this fix things for you?

fix: check if caret is present before removal

---

doc/telescope.txt
lua/telescope/config.lua
lua/telescope/pickers/highlights.lua

Reverts nvim-telescope/telescope.nvim#1312

Revert "Changed the results window highlight to always be full width"

---

lua/telescope/builtin/git.lua

This PR introduces one tiny new function to cover a git corner case. It's somewhat of an extension of #757.
If you work with `git-worktree` a lot, along with ThePrimeagen's [git-worktree.nvim](https://github.com/ThePrimeagen/git-worktree.nvim) there's one corner case you run into a lot: when you're in a bare repo, but NOT in an actual working tree. If you're in this situation, `git` actually still supports some operations, such as `git log` and `git branch`.  
The way Telescope worked before, it checked solely for the working tree, and if it didn't exist, it complained the directory was not a git directory, when it in fact was, but just a bare repo. This also invalidated any operations that you could conduct in the bare repo (like the ones talked about above). This PR changes that. …

feat(worktrees): added support for bare repo git operations

---

lua/telescope/actions/init.lua
lua/telescope/actions/layout.lua
lua/telescope/pickers.lua

fix #1474
fix #1482
CC @l-kershaw @johnybx 
Why was the closing stuff changed?
Also found this funny bug
https://user-images.githubusercontent.com/15233006/142928898-04c41afa-583d-4668-ba5d-d0f7867fa64a.mp4
This happens on current master and this branch. I leave the fix to one of you guys :)

fix: cleanup actions layout

---

lua/telescope/actions/mt.lua
lua/telescope/mappings.lua
lua/telescope/pickers.lua
lua/tests/automated/action_spec.lua

fix #1482
fix #1485
Reverts nvim-telescope/telescope.nvim#1143

Revert "fix: action mt so we can again concat actions from two different tables"

---

ftplugin/TelescopePrompt.lua
ftplugin/TelescopeResults.lua
lua/telescope/previewers/buffer_previewer.lua

fix: issue when scrollbind is set

---

ftplugin/TelescopePrompt.lua

fix: set `nowrap` in prompt buffer

---

doc/telescope.txt
lua/telescope/pickers/layout_strategies.lua

chore: layout strategy tidying

---

lua/telescope/pickers.lua
plugin/telescope.vim

add Normal highlights for prompt and results

---

lua/telescope/builtin/lsp.lua

This PR tries to make the lsp requests async. I've implemented this for `references()` and `list_or_jump()` for now and would like feedback before doing the rest.
before:
https://user-images.githubusercontent.com/36493671/143772352-46c064bc-0c71-497a-8d30-e230e01940d9.mp4
after:
https://user-images.githubusercontent.com/36493671/143771369-e9bc7cb2-4419-4d31-a1db-496844ee83cb.mp4

Async lsp requests

---

doc/telescope.txt
lua/telescope/pickers/layout_strategies.lua

Add usage example for adjusting layout

docs: layout strategy usage

---

lua/telescope/make_entry.lua

Regression introduced in b50b364ae1eaf41feb88c11dc3e69d6e39f3ac04
My bad
fix #1547

fix: regression with grep. We already pass in t.value

---

lua/telescope/_.lua
lua/telescope/builtin/git.lua

chore: better uv.spawn error handling

---

lua/telescope/previewers/buffer_previewer.lua

fix: git_branch previewer should no longer error

---

lua/telescope/pickers.lua

This is almost entirely copied from #927, but that PR was so out of date it was easier to just make a new one than to deal with the merge conflicts 😅 
I decided it wasn't worth doing docs for `entry_manager.lua` and `linked_list.lua` at the moment, since there have been discussions about reimplementing things in that area.

docs: functions in `pickers.lua`

---

lua/telescope/builtin/files.lua

fix current_buffer_fuzzy_find in vue files

---

lua/telescope/actions/init.lua

No fold on which_key windows by default.

fix: `which_key` action `foldenable=false` by default

---

lua/telescope/sorters.lua

Re-creating #781 from the correct branch
---
I use this sorter to do things like bias terminal history towards those that are newer when using _Telescope_ to query it, etc. as you'd expect. I noticed that this finder isn't broken, but throws a handful of warnings due to the `sorter:sort` not being called with the new `cb_add`, etc. functions.
If we use the locally-defined sorter, we get double the results back so I just ended up calling `:sorting_function` directly.
Not sure if this is the best way to do this, but looking for feedback.

[RFC]: Ensure 'cb_filter' defined when creating new index-bias sorter

---

lua/telescope/_extensions/init.lua

@clason does that fix your issue? 
I'll quickly check that this doesn't interfere with previous commit

fix: setup solely on access as well

---

lua/telescope/_extensions/init.lua

Closes #1632 
Apologies for trouble caused. Could please anyone confirm that it fixes the associated issue?
cc @clason @yigothu @GreatestOfAllTimee @ikerurda @queensferryme

fix: return extension exports on load

---

lua/telescope/pickers.lua

Resolves #1656
@max397574 does this fix this problem on your machine?

fix: check if `status.preview_bufnr` is `nil` before checking if valid

---

lua/telescope/builtin/files.lua

fix: allow find_command along with options

---

lua/telescope/actions/init.lua

Resolves #1667 
@prurph does this fix the problem for you?

fix: allow `which_key` action without preview

---

lua/telescope/actions/set.lua
lua/telescope/actions/utils.lua

fix #559 
fix #699 
As outlined [here](https://github.com/nvim-telescope/telescope.nvim/issues/559#issuecomment-1002803413) the reason for #559 is not leaving insert mode when opening the file.
This just wraps the opening logic in autocmd InsertLeave

Fix folding when a file is opened

---

lua/telescope/actions/set.lua
lua/telescope/actions/utils.lua

Reverts nvim-telescope/telescope.nvim#1643

Revert "Fix folding when a file is opened"

---

doc/telescope.txt
lua/telescope/actions/init.lua
lua/telescope/pickers.lua
lua/telescope/pickers/highlights.lua

Resolves #1663
@SimonMandlik does this fix your issue?

fix: update `multi_icon` with `select/drop/toggle_all` actions

---

lua/telescope/pickers.lua

Resolves #1692
@anuvyklack can you check if this fixes things for you?

fix: always update preview when `_selection_entry` changes

---

lua/telescope/builtin/files.lua

fix(treesitter): with lua defintions (and probably more)

---

lua/telescope/_.lua
lua/telescope/builtin/internal.lua
lua/telescope/finders/async_job_finder.lua
lua/telescope/finders/async_oneshot_finder.lua
lua/telescope/make_entry.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/utils.lua

fix: putils writer use rather than using PAGER

---

ftplugin/TelescopePrompt.lua
ftplugin/TelescopeResults.lua
lua/telescope/previewers/buffer_previewer.lua

fix: layout issues if signcolumn is set

---

lua/telescope/actions/mt.lua
lua/telescope/mappings.lua
lua/telescope/pickers.lua
lua/tests/automated/action_spec.lua

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
i am going crazy ..............................................
pressing revert and realize whats the problem was

fix: action mt again

---

lua/telescope/pickers.lua

fix #1538 #1539
CC @mroavi would be cool if you could test this. Also for other regressions

fix: selection strategy madness when its not reset

---

doc/telescope.txt
lua/telescope/builtin/init.lua

A tiny improvement to the documentation.

Update picker docs. there -> their

---

doc/telescope.txt
lua/telescope/actions/init.lua

Resolves #1799
Attempt number 2 hopefully added the docs in the correct place this time around '-.-

doc: help for select_{default,tab,vertical,horizontal}

---

lua/telescope/actions/mt.lua
lua/tests/automated/action_spec.lua

fix #1809 
Continuation of #1487
I am so sorry @tjdevries every time i fix a bug in actions/mt i make it worse (introduce a new bug) and make the code worse. At least the interface is pretty :laughing:

fix: action replace/enhance if the replaced/enhanced action as combined

---

doc/telescope.txt
lua/telescope/actions/init.lua

Might merge tomorrow. I'll need to think about it over night. If i wanna add more
Close #587
Ref #1827

docs: document more actions and add introduction to actions

---

lua/telescope/pickers.lua

Closes #1859.
Simple solution I (hopefully correctly) guess :)

fix: extra finder loop on refresh w/ reset prompt

---

lua/telescope/actions/init.lua
lua/telescope/builtin/git.lua
lua/telescope/mappings.lua
lua/telescope/pickers.lua

This replaces autocmds with lua autocmds. We may want to support both until 0.7 is released with hopefully lua autocmds. 
Requires neovim/neovim#14661

Lua autocmds

---

doc/telescope.txt
lua/telescope/config.lua

docs(smart_path): add negative performance warning

---

lua/telescope/_.lua

fix: closing process handle after termination

---

lua/telescope/previewers/term_previewer.lua

CC @bluz71
This solves this issue for me

fix: termpreviewer scrolling

---

doc/telescope.txt
lua/telescope/builtin/init.lua
lua/telescope/make_entry.lua

fix(builtin.tags): custom filename width (#1820)

---

lua/telescope/make_entry.lua

Closes #1927 
Does this work for you @drybalka ? Very minimal diff and I'm not really a `builtin.keymaps` user.

feat: show lua fn name if available

---

developers.md
doc/telescope.txt
lua/telescope/init.lua

Following telecorp a very simple overview powered by https://github.com/jbyuki/venn.nvim
Maybe we should refer somewhere that the vimdocs then comprise a proper overview of telescope.
Of course any suggestions welcome, just a first half an hour crack at it.

docs: simplified architecture flow chart

---

lua/telescope/actions/set.lua

Fix regression from #1202 
Closes #1949 #1950
I like to think that this is the most elegant way to go about it :sweat_smile: but maybe I'm missing something
@emilienlemaire @ribelo could you please confirm that this fix works for you and maybe test quickly whether no regression in your typical workflow is visible?

fix: wrong win on selection

---

doc/telescope.txt
lua/telescope/config.lua
lua/telescope/utils.lua
scripts/gendocs.lua

docs: document limitations of file_ignore_patterns and transform_path

---

lua/telescope/make_entry.lua

feat(vim_options): show scope information in display

---

.github/FUNDING.yml

chore: update FUNDING.yml

---

lua/telescope/actions/init.lua

fix(git_branch): fix typo in action notification

---

README.md

Hello! I believe this fix should be self-explanatory.

fix: fix quotes in README.md

---

lua/telescope/previewers/buffer_previewer.lua

fix: TelescopePreviewerLoaded

---

README.md

https://thepugautomatic.com/2014/08/login-setup/

README: "setup/"set up" grammar

---

doc/telescope.txt
lua/telescope/config/resolve.lua
lua/tests/automated/resolver_spec.lua

feat: add min max boundary to width, hight resolver

---

doc/telescope.txt
lua/telescope/builtin/git.lua
lua/telescope/builtin/internal.lua
lua/telescope/make_entry.lua
lua/telescope/pickers/entry_display.lua
scripts/gendocs.lua

cherry picked and rebased from https://github.com/nvim-telescope/telescope.nvim/pull/1473/commits/8b433235d0b7763376fbeaca3b9de1c1824dc252 because of unrelated changes
I will add some documentation here as well

feat: Add entry_index for entry_makers

---

lua/telescope/builtin/__files.lua
lua/telescope/make_entry.lua

I am thinking about "lying" to our users and changing a `search=` query to an inverted query that removes empty lines (which are imo useless). This would make `Telescope grep_string search=` at least more useful for me. It needs a little bit of changing to the parser matching because we no longer have a column.
Thoughts?
CC @tjdevries @fdschmidt93 

feat: invert_match for search=""

---

lua/telescope/make_entry.lua
lua/telescope/previewers/buffer_previewer.lua

Fixes #2045
* Neovim version (nvim --version): 0.7.2
* Operating system and version: nixos 22.05

fix: autocmd, show desc if available

---

lua/telescope/make_entry.lua

https://github.com/nvim-telescope/telescope.nvim/issues/2045#issuecomment-1177987095

fix: more autocmds desc fixes

---

lua/telescope/from_entry.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/term_previewer.lua

fix: from_entry escape and validation

---

lua/telescope/pickers.lua

basically to improve performance for 0.1

perf: limit scrolling size

---

doc/telescope.txt
lua/telescope/config.lua
lua/telescope/mappings.lua
scripts/gendocs.lua
scripts/minimal_init.vim

mapping doc changes from https://github.com/nvim-telescope/telescope.nvim/pull/1473 pulled out

docs: mappings documentation overhaul

---

lua/telescope/pickers/layout_strategies.lua

fix: cursor theme if winbar is set

---

lua/telescope/pickers/layout_strategies.lua

followup for #2066
CC @anstadnik does this work for you?

fix: cursor for nvim 0.7

---

developers.md

docs: extension bundling

---

lua/telescope/pickers.lua

chore: reduce log level to trace in pickers.lua

---

doc/telescope.txt
lua/telescope/init.lua

Fix: typo in docs

---

lua/telescope/actions/init.lua
lua/telescope/mappings.lua

fix: nop i_<c-j> because we dont want allow new line

---

lua/telescope/previewers/utils.lua

fix: previewer if custom_captures are set

---

developers.md

This updates documentation for adding a new oneshot job finder, per the function's signature at https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/finders.lua#L174
lsp was barking at me about it :)

docs: update oneshot finder example

---

lua/telescope/builtin/__files.lua
lua/telescope/make_entry.lua

fix: rg invert and files-with-matches res line parsing

---

lua/telescope/builtin/__git.lua

Reverts nvim-telescope/telescope.nvim#2181

Revert "feat(git): notify when not in a git repo instead of error"

---

lua/telescope/actions/generate.lua

@bangedorrunt does this solve your issue, described here https://github.com/nvim-telescope/telescope.nvim/pull/2034#issuecomment-1304780598?

fix: generate.refine with border=false

---

README.md

docs: Fixed a typo

---

doc/telescope.txt
lua/telescope/config.lua

Fix unfinished sentence in docs

Fix unfinised sentence in docs

---

lua/telescope/builtin/__git.lua
lua/telescope/make_entry.lua

Reverts nvim-telescope/telescope.nvim#2288
Fixes #2350 
Reasoning: https://github.com/nvim-telescope/telescope.nvim/pull/2357#issuecomment-1409881169

Revert "feat(git): git_commits shows the current branch graph"

---

README.md

I added the configuration/addition directions for using the [lazy.nvim package manager](https://github.com/folke/lazy.nvim).
Didn't see the request in issues.
Sort of, this change is a documentation update to the main README.
Used MarkdownPreview to test and ensure correct spacing and stylistic alignment.
* Neovim version (nvim --version): 0.8.3
* Operating system and version: Mac M1 - Ventura 13.0.1
- [ X ] My code follows the style guidelines of this project (stylua)
- [ X ] I have performed a self-review of my own code
- [ X ] I have commented …

Added config directions for Lazy.nvim package manager

---

lua/telescope/builtin/__files.lua

fix: current_buffer_fuzzy_find push cursor

---

lua/telescope/pickers.lua

fixes https://github.com/nvim-telescope/telescope.nvim/issues/2101#issuecomment-1436031459

fix: previewer = true

---

lua/telescope/builtin/__files.lua

fix: current_buffer_fuzzy_find highlighter

---

README.md

Add to readme available git branch actions.

Add more git branch actions to README

---

lua/telescope/actions/init.lua

fix(actions): send_to_* and smart_send_to_* now append to history

---

lua/telescope/pickers.lua

fix: make sure buf is valid before updating highlighting

---

lua/telescope/pickers.lua

fix: make sure that prompt_win is valid bevore closing it

---

lua/telescope/actions/init.lua
lua/telescope/pickers.lua

Reverts nvim-telescope/telescope.nvim#2336
Closes #2532
Closes https://github.com/nvim-telescope/telescope.nvim/issues/2534

Revert "fix: correctly restore cursor position in original window"

---

lua/telescope/previewers/buffer_previewer.lua

still need to resolve binary warning
CC @clason

fix(previewer): ft detect for filetypes defined as functions

---

lua/telescope/previewers/utils.lua

fix(previewer): only run ftdetect for files

---

lua/telescope/previewers/buffer_previewer.lua

fix(previewer): dont treat unknown filetypes as binary file

---

README.md

docs: update install instructions with latest tag

---

lua/telescope/previewers/buffer_previewer.lua

- split apart functions
- replace magic numbers with named constants
- reorganize functions for better grouping

refactor(previewer): clean up file_maker

---

lua/telescope/_.lua
lua/telescope/actions/history.lua
lua/telescope/builtin/__files.lua
lua/telescope/from_entry.lua
lua/telescope/make_entry.lua
lua/telescope/previewers/buffer_previewer.lua
lua/telescope/previewers/term_previewer.lua
lua/telescope/utils.lua

Reverts nvim-telescope/telescope.nvim#2599

Revert "expand paths more smartly"

---

lua/telescope/utils.lua
lua/tests/automated/utils_spec.lua

let `is_uri` function handle bad paths better
closes #2670

fix(utils): `is_uri` empty path

---

lua/telescope/actions/init.lua

Adds a new git action `git_rename_branch`.
For context, I usually don't delete branches, I just rename them and search for specific branch names when I want to find something easily.
```
require('telescope').setup { 
pickers = {
git_branches = {
mappings = {
i = {
["<c-r>"] = actions.git_rename_branch 
},
}
},
}
}
```
Now doing `<c-r>` when the picker is active on a branch will prompt the user to input the new name for said branch. 
_Note: this is just an example mapping to test this feature, this PR doesn't include adding …

Add git_rename_branch git action

---

README.md

Added more clarity to read the documentation.
Not applicable
Not applicable
Not applicable

added more detail to the documentation

---

lua/telescope/pickers.lua

fix: always reset prompt highlighting

---

lua/telescope/builtin/__git.lua

Convert the git status from being a synchronous job that had timeout issues on low-performance networks or really large repos. To sue async_oneshot_job
Requested the reporter to perform tests on his machine. I also tested locally with a git wrapper that introduced fake latency,
NVIM v0.9.2
fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"

Make git_status picker async Fixes #2714

---

doc/telescope.txt
lua/telescope/builtin/__git.lua
lua/telescope/builtin/init.lua

add missing docs for option added in https://github.com/nvim-telescope/telescope.nvim/pull/591

docs(git_status): add missing opt `expand_dir`

---

lua/telescope/builtin/__git.lua

relevant #2825
cleaning up an earlier hack that was bothering me

refactor(git_status): clean up prompt retrieval for `on_complete`

---

lua/telescope/make_entry.lua

fix(builtin.keymaps): escape newline chars in desc

---

doc/telescope.txt
lua/telescope/actions/init.lua
lua/telescope/config.lua
lua/telescope/pickers.lua

fix!: fallback to vim.o.winblend

---

lua/telescope/make_entry.lua

closes https://github.com/nvim-telescope/telescope.nvim/issues/2712
closes https://github.com/nvim-telescope/telescope.nvim/issues/2658

fix(git_status): support `path_display`

---

CONTRIBUTING.md

better reflect stance on feature additions specifically around new pickers

docs(contrib): update contribution guide

---

developers.md

Fix incorrect file paths
Docs
N/A
N/A

docs(developers): fix incorrect file paths

---

lua/telescope/actions/set.lua

fixes https://github.com/nvim-telescope/telescope.nvim/issues/2914

fix(action): horizontal scroll after preview toggling

---

lua/telescope/builtin/__files.lua

Previous implementation of placing the cursor on the first column of the highlight failed to take into account that the highlighter can return more than one data structure.
closes #2941

fix(current_buffer_fuzzy_find): error on select

---

lua/telescope/config.lua

There's a limitation with extmark's `right_align` virtual text and how it handles side scrolling. This causes text entered to be hidden behind the virtual text rather than begin the side scroll.
An issue is opened upstream https://github.com/neovim/neovim/issues/27540 
But this could take a while before it's fixed as it's considered `complexity:high`.
This PR adds a temporary workaround of just hiding the status text if the prompt is long enough to interfere with it.
closes #2929

fix(picker): prevent status text from hiding prompt

---

lua/telescope/builtin/__internal.lua

Notify when there is no items in quickfix or loclist

Notify on empty quickfix and loclist

---

doc/telescope.txt
lua/telescope/builtin/__lsp.lua
lua/telescope/builtin/init.lua

Reverts nvim-telescope/telescope.nvim#3099
uses nightly api.

Revert "refactor(lsp): simplify `list_to_jump`"

---

lua/telescope/builtin/__lsp.lua
plugin/telescope.lua

fixup: adapt to deprecations in Nvim 0.10

---

.github/FUNDING.yml

:money_mouth_face: :money_mouth_face: :money_mouth_face:

chore: updating FUNDING

---

README.md

The version that is listed in the README is behind by several versions (0.1.6) and this changes brings it up to the latest stable release (0.1.8 at the time of this writing).
- This change is only a documentation update
N/A
N/A

Update version in README to reflect stable release

---

lua/telescope/builtin/__lsp.lua

closes https://github.com/nvim-telescope/telescope.nvim/issues/3183

fix(lsp): `if_nil` <0.10 compat

---

lua/telescope/builtin/__lsp.lua

Switch to use `vim.lsp.buf_request_all`.
This should allow for requests sent to multiple servers to be handled.
closes #3242

fix(lsp): support multiple servers for dynamic symbols

---

doc/telescope.txt
lua/telescope/builtin/init.lua

ref: https://github.com/nvim-telescope/telescope.nvim/pull/3235

Show kind docs

---

lua/telescope/builtin/__lsp.lua
lua/telescope/utils.lua

This will be required when/if https://github.com/neovim/neovim/pull/30915 is merged
Ping @clason

fix: nightly removal of vim.lsp.util._str_byteindex()

---

doc/telescope.txt
lua/telescope/builtin/__lsp.lua

Reverts nvim-telescope/telescope.nvim#3335

Revert "feat(lsp): use native lsp handlers for some pickers"
